language: python
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: '3.7'
      dist: xenial
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  allow_failures:
    - os: windows
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libsndfile1
  homebrew:
    packages:
      - pipenv
      - libsndfile
install:
  - pip3 install --upgrade pip
  - pip3 install pipenv
  - pipenv install
script:
  - PYTHONPATH=./src/main/python pipenv run pytest --cov=./src/main/python
