language: python
cache:
  pip: true
sudo: required
python:
    - "3.6"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - libsndfile1
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy colorcet scipy qtpy mkl==2018.0.2 qtawesome
  - source activate test
  - pip install -q -U pyqt5 matplotlib ffmpeg-python soundfile resampy
script:
  - PYTHONPATH=./src/main/python unittest
