language: python
cache:
  directories:
  - "$PIP_CACHE_DIR"
  - "$PIPENV_CACHE_DIR"
env:
  global:
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
  - PIPENV_VENV_IN_PROJECT=yes
matrix:
  include:
  - name: Python 3.7.1 on Xenial Linux
    python: '3.7'
    dist: xenial
    env:
    - PYINST_DIST_NAME=beqdesigner
    - PIPENV_VERBOSITY=-1
    - COVERAGE_ARGS="--cov=./src/main/python"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - name: Python 3.7.2 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    env:
    - PYINST_DIST_NAME=BEQDesigner.app.zip
  - name: Python 3.7.3 on Windows
    os: windows
    language: shell
    before_install:
    - choco install miniconda3
    - PATH=/c/tools/miniconda3:/c/tools/miniconda3/Scripts:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy scipy
    - conda activate test
    env:
    - PYINST_DIST_NAME=beqdesigner.exe
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libsndfile1
    - upx
  homebrew:
    packages:
    - pipenv
    - upx
install:
- pip3 install --upgrade pip
- pip3 install pipenv
- pipenv install -d
- pip3 list
- pipenv run pip3 list
script:
- PYTHONPATH=./src/main/python pipenv run pytest $COVERAGE_ARGS
before_deploy:
- pipenv run pip3 install pyinstaller
- pipenv run pyinstaller --clean --log-level=INFO -F beqdesigner.spec
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pushd dist; zip -r BEQDesigner.app.zip BEQDesigner.app; popd; fi
deploy:
  provider: releases
  api_key:
    secure: a2Ju6IVLQjD2RTNlIhDe9saFGcNfdr+F9P2LO1q4zT8Bke8EGlDlBeE5xKmMhD7KWiS5IJDJz9djXlqI0JG3D2Tve2VhpYrLUD7mABTxIZqKReYXL5b/p4B4mkg0KLlUHleyu4t2GWZ1+PNPmCO3Q0G1k7aNl8NQb2wZMBujaKFM/HHf9PBS7ioROrnJjW2VlNg86YDCKZKUYOGc1tOgIYrwX0h4HqE0/oHj7ZNAxLqi2OYr22To4NFJCnMPXxF81n95N2o7AlwLUElaSdHC5D2OPgCVATDzkX7MzD2cpkI1ca0a5exqo3pdX3q0wofygWj3zNwVWKbub+poLtKFV2BowCWrr89UPZYPXlmnivolD5cfFRpgO8SABYnVWzXWhsaxdS2xEBL/SZ0ssuuPiJRSWjsiunjTPQBDoqxBYPSPlUcKbvrE6mcmfjCREQKdXVSnJRtEGhA/JD91oDtNbOr2Vk+u3hSwpNcSr1oXmG/J2PCGgsjcY+RKv/aGF4CzFdBYya4PGqODhiaZKKSW8rKub5ZW+c+8ELCRk5Fu3DAWVvJN7ZhVVuR+gYPG+avKDYwXF1/NwX/IXumS5a8LAwnZTVtzPRwntQr9rIJfXqNaCV1sFFJ+MDaf8K4u0P8T3yGtRO1BtfTYyO+YXRrBMCn4VZ2dN7Qv5L1YdIpbm1M=
  file: dist/$PYINST_DIST_NAME
  on:
    repo: 3ll3d00d/beqdesigner
    branch: travis
#    tags: true
  skip_cleanup: true
  draft: true