language: python
cache:
  directories:
  - "$PIP_CACHE_DIR"
  - "$PIPENV_CACHE_DIR"
env:
  global:
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
  - PIPENV_VENV_IN_PROJECT=yes
matrix:
  include:
  - name: Python 3.7.1 on Xenial Linux
    python: '3.7'
    dist: xenial
    env:
    - PIPENV_VERBOSITY=-1
    - COVERAGE_ARGS="--cov=./src/main/python"
    - PBIN=pip3
    before_install:
    - pip3 install --upgrade pip
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - name: Python 3.7.2 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    env:
    - PBIN=pip3
    before_install:
    - pip3 install --upgrade pip
  - name: Python 3.7.3 on Windows
    os: windows
    language: shell
    env:
    - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH"
    - PBIN=pip
    before_install:
    - choco install miniconda3 openssl.light nsis
    - conda config --set always_yes yes --set changeps1 no
    - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy scipy
    - source activate test
    - python -m pip install --upgrade pip
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libsndfile1
  homebrew:
    packages:
    - pipenv
install:
- $PBIN install pipenv
- pipenv install -d
- $PBIN list
- pipenv run $PBIN list
script:
- PYTHONPATH=./src/main/python pipenv run pytest $COVERAGE_ARGS
before_deploy:
- pipenv run $PBIN install pyinstaller
- pipenv run pyinstaller --clean --log-level=INFO -F beqdesigner.spec
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]
  then
    pushd dist
    rm beqdesigner
    zip -r beqdesigner.app.zip beqdesigner.app
    rm -Rf beqdesigner.app
    popd
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]
  then
    export USE_NSIS=Y
    mv dist/beqdesigner.exe dist/bak.exe
    pipenv run pyinstaller --clean --log-level=INFO -D beqdesigner.spec
    "/c/Program Files (x86)/NSIS/makensis.exe" src/main/nsis/Installer.nsi
    mv dist/bak.exe dist/beqdesigner.exe
  fi
deploy:
  provider: releases
  api_key:
    secure: a2Ju6IVLQjD2RTNlIhDe9saFGcNfdr+F9P2LO1q4zT8Bke8EGlDlBeE5xKmMhD7KWiS5IJDJz9djXlqI0JG3D2Tve2VhpYrLUD7mABTxIZqKReYXL5b/p4B4mkg0KLlUHleyu4t2GWZ1+PNPmCO3Q0G1k7aNl8NQb2wZMBujaKFM/HHf9PBS7ioROrnJjW2VlNg86YDCKZKUYOGc1tOgIYrwX0h4HqE0/oHj7ZNAxLqi2OYr22To4NFJCnMPXxF81n95N2o7AlwLUElaSdHC5D2OPgCVATDzkX7MzD2cpkI1ca0a5exqo3pdX3q0wofygWj3zNwVWKbub+poLtKFV2BowCWrr89UPZYPXlmnivolD5cfFRpgO8SABYnVWzXWhsaxdS2xEBL/SZ0ssuuPiJRSWjsiunjTPQBDoqxBYPSPlUcKbvrE6mcmfjCREQKdXVSnJRtEGhA/JD91oDtNbOr2Vk+u3hSwpNcSr1oXmG/J2PCGgsjcY+RKv/aGF4CzFdBYya4PGqODhiaZKKSW8rKub5ZW+c+8ELCRk5Fu3DAWVvJN7ZhVVuR+gYPG+avKDYwXF1/NwX/IXumS5a8LAwnZTVtzPRwntQr9rIJfXqNaCV1sFFJ+MDaf8K4u0P8T3yGtRO1BtfTYyO+YXRrBMCn4VZ2dN7Qv5L1YdIpbm1M=
  file_glob: true
  file: dist/beqdesigner*
  on:
    repo: 3ll3d00d/beqdesigner
    branch: travis
#    os: linux
#    tags: true
  skip_cleanup: true
  draft: true