site_name: BEQDesigner
site_url: 'https://beqdesigner.readthedocs.io'
copyright: 'Copyright &copy; 2019 Matt Khan'
theme:
  name: 'material'
  logo: 'img/icon.png'
  favicon: 'img/icon.ico'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.superfences
extra:
  disqus: beqdesigner
nav:
  - Introduction: index.md
  - Core Concepts: concepts.md
  - User Guide:
      - 'Getting Started': install.md
      - 'User Interface':
        - 'The Main Window': ui/main_window.md
        - 'Loading Signals': ui/load_signal.md
        - 'Creating Filters': ui/add_filter.md
        - 'Looking at Waveforms': ui/waveform.md
        - 'Sharing Content': ui/report.md
      - 'Import/Export': 
        - 'Projects, Signals and Filters': ui/load_save.md
        - 'Managing Presets': ui/presets.md
        - 'Export Biquads': ui/export_biquads.md
      - 'Tools':
        - 'Extract Audio': ui/extract_audio.md
        - 'Batch Extract': ui/batch_extract.md
        - 'Remux Audio': ui/remux_audio.md
        - 'Analyse Audio': ui/spectrum.md
        - 'Merge Minidsp XML': ui/merge_minidsp_xml.md
      - 'Preferences': ui/preferences.md
  - Workflow:
      - 'A Worked Example': workflow/beq.md
      - 'Remuxing': workflow/remux.md
      - 'Simulating Bass Management': workflow/bass_management.md
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
