[tool.poetry]
name = "beqdesigner"
version = "1.1.0"
description = "A Qt based app for designing BassEQ filters"
authors = ["3ll3d00d <mattkhan+beqdesigner@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://beqdesigner.readthedocs.io/"
repository = "https://github.com/3ll3d00d/beqdesigner"

[tool.poetry.dependencies]
python = "^3.12"
pyqt5 = "^5.15.10"
pyqt5-qt5 = "5.15.2"
matplotlib = "*"
ffmpeg-python = "*"
soundfile = "*"
resampy = "*"
pyqtgraph = "*"
numpy = "*"
scipy = "*"
qtpy = "*"
qtawesome = "*"
sortedcontainers = "*"
pillow = "*"
requests = "*"
semver = "*"
markdown = "*"
plumbum = "*"
graphviz = "*"
sanitize-filename = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
distro = "*"
atomicwrites = "*"
pyqt5-stubs = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
