# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_analysisDialog(object):
    def setupUi(self, analysisDialog):
        analysisDialog.setObjectName("analysisDialog")
        analysisDialog.resize(1369, 720)
        analysisDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(analysisDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.analysisGridLayout = QtWidgets.QGridLayout()
        self.analysisGridLayout.setObjectName("analysisGridLayout")
        self.showLimitsButton = QtWidgets.QToolButton(analysisDialog)
        self.showLimitsButton.setObjectName("showLimitsButton")
        self.analysisGridLayout.addWidget(self.showLimitsButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.analysisGridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.analysisTabs = QtWidgets.QTabWidget(analysisDialog)
        self.analysisTabs.setObjectName("analysisTabs")
        self.spectrumTab = QtWidgets.QWidget()
        self.spectrumTab.setObjectName("spectrumTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.spectrumTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spectrumChart = MplWidget(self.spectrumTab)
        self.spectrumChart.setObjectName("spectrumChart")
        self.gridLayout_3.addWidget(self.spectrumChart, 3, 0, 1, 1)
        self.spectrumControlsLayout = QtWidgets.QGridLayout()
        self.spectrumControlsLayout.setObjectName("spectrumControlsLayout")
        self.colourRangeLabel = QtWidgets.QLabel(self.spectrumTab)
        self.colourRangeLabel.setObjectName("colourRangeLabel")
        self.spectrumControlsLayout.addWidget(self.colourRangeLabel, 0, 4, 1, 1)
        self.colourUpperLimit = QtWidgets.QSpinBox(self.spectrumTab)
        self.colourUpperLimit.setMinimum(-99)
        self.colourUpperLimit.setMaximum(0)
        self.colourUpperLimit.setProperty("value", -10)
        self.colourUpperLimit.setObjectName("colourUpperLimit")
        self.spectrumControlsLayout.addWidget(self.colourUpperLimit, 0, 5, 1, 1)
        self.colourLowerLimit = QtWidgets.QSpinBox(self.spectrumTab)
        self.colourLowerLimit.setMinimum(-120)
        self.colourLowerLimit.setMaximum(0)
        self.colourLowerLimit.setProperty("value", -40)
        self.colourLowerLimit.setObjectName("colourLowerLimit")
        self.spectrumControlsLayout.addWidget(self.colourLowerLimit, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.spectrumControlsLayout.addItem(spacerItem1, 0, 10, 1, 1)
        self.magUpperLimit = QtWidgets.QDoubleSpinBox(self.spectrumTab)
        self.magUpperLimit.setDecimals(2)
        self.magUpperLimit.setMinimum(-99.0)
        self.magUpperLimit.setMaximum(0.0)
        self.magUpperLimit.setSingleStep(0.001)
        self.magUpperLimit.setProperty("value", -10.0)
        self.magUpperLimit.setObjectName("magUpperLimit")
        self.spectrumControlsLayout.addWidget(self.magUpperLimit, 0, 2, 1, 1)
        self.updateChart = QtWidgets.QToolButton(self.spectrumTab)
        self.updateChart.setObjectName("updateChart")
        self.spectrumControlsLayout.addWidget(self.updateChart, 0, 9, 1, 1)
        self.upperLimitLabel = QtWidgets.QLabel(self.spectrumTab)
        self.upperLimitLabel.setObjectName("upperLimitLabel")
        self.spectrumControlsLayout.addWidget(self.upperLimitLabel, 0, 0, 1, 1)
        self.showSpectroButton = QtWidgets.QToolButton(self.spectrumTab)
        self.showSpectroButton.setObjectName("showSpectroButton")
        self.spectrumControlsLayout.addWidget(self.showSpectroButton, 0, 11, 1, 1)
        self.magLimitType = QtWidgets.QComboBox(self.spectrumTab)
        self.magLimitType.setObjectName("magLimitType")
        self.magLimitType.addItem("")
        self.magLimitType.addItem("")
        self.magLimitType.addItem("")
        self.spectrumControlsLayout.addWidget(self.magLimitType, 0, 1, 1, 1)
        self.markerSize = QtWidgets.QComboBox(self.spectrumTab)
        self.markerSize.setObjectName("markerSize")
        self.markerSize.addItem("")
        self.markerSize.addItem("")
        self.markerSize.addItem("")
        self.spectrumControlsLayout.addWidget(self.markerSize, 0, 8, 1, 1)
        self.magLowerLimit = QtWidgets.QDoubleSpinBox(self.spectrumTab)
        self.magLowerLimit.setMinimum(-120.0)
        self.magLowerLimit.setMaximum(-1.0)
        self.magLowerLimit.setSingleStep(0.01)
        self.magLowerLimit.setProperty("value", -22.0)
        self.magLowerLimit.setObjectName("magLowerLimit")
        self.spectrumControlsLayout.addWidget(self.magLowerLimit, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.spectrumTab)
        self.label_2.setObjectName("label_2")
        self.spectrumControlsLayout.addWidget(self.label_2, 0, 7, 1, 1)
        self.gridLayout_3.addLayout(self.spectrumControlsLayout, 0, 0, 1, 1)
        self.analysisTabs.addTab(self.spectrumTab, "")
        self.waveformTab = QtWidgets.QWidget()
        self.waveformTab.setObjectName("waveformTab")
        self.gridLayout = QtWidgets.QGridLayout(self.waveformTab)
        self.gridLayout.setObjectName("gridLayout")
        self.waveformChart = MplWidget(self.waveformTab)
        self.waveformChart.setObjectName("waveformChart")
        self.gridLayout.addWidget(self.waveformChart, 1, 0, 1, 1)
        self.waveformControls = QtWidgets.QGridLayout()
        self.waveformControls.setObjectName("waveformControls")
        self.magnitudeDecibels = QtWidgets.QCheckBox(self.waveformTab)
        self.magnitudeDecibels.setObjectName("magnitudeDecibels")
        self.waveformControls.addWidget(self.magnitudeDecibels, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.waveformControls.addItem(spacerItem2, 0, 3, 1, 1)
        self.headroomLabel = QtWidgets.QLabel(self.waveformTab)
        self.headroomLabel.setObjectName("headroomLabel")
        self.waveformControls.addWidget(self.headroomLabel, 0, 1, 1, 1)
        self.headroom = QtWidgets.QDoubleSpinBox(self.waveformTab)
        self.headroom.setEnabled(True)
        self.headroom.setDecimals(3)
        self.headroom.setMinimum(-100.0)
        self.headroom.setMaximum(100.0)
        self.headroom.setSingleStep(0.001)
        self.headroom.setObjectName("headroom")
        self.waveformControls.addWidget(self.headroom, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.waveformControls, 0, 0, 1, 1)
        self.analysisTabs.addTab(self.waveformTab, "")
        self.analysisGridLayout.addWidget(self.analysisTabs, 0, 2, 2, 1)
        self.frame = QtWidgets.QFrame(analysisDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QGridLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.addWidget(self.line, 5, 1, 1, 2)
        self.copyFilter = QtWidgets.QComboBox(self.frame)
        self.copyFilter.setObjectName("copyFilter")
        self.formLayout.addWidget(self.copyFilter, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.addWidget(self.label, 6, 1, 1, 1)
        self.file = QtWidgets.QLineEdit(self.frame)
        self.file.setEnabled(False)
        self.file.setObjectName("file")
        self.formLayout.addWidget(self.file, 0, 2, 1, 1)
        self.startTime = QtWidgets.QTimeEdit(self.frame)
        self.startTime.setObjectName("startTime")
        self.formLayout.addWidget(self.startTime, 2, 2, 1, 1)
        self.loadButton = QtWidgets.QPushButton(self.frame)
        self.loadButton.setObjectName("loadButton")
        self.formLayout.addWidget(self.loadButton, 4, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.addItem(spacerItem3, 10, 1, 1, 3)
        self.channelSelectorLabel = QtWidgets.QLabel(self.frame)
        self.channelSelectorLabel.setObjectName("channelSelectorLabel")
        self.formLayout.addWidget(self.channelSelectorLabel, 1, 1, 1, 1)
        self.endTime = QtWidgets.QTimeEdit(self.frame)
        self.endTime.setObjectName("endTime")
        self.formLayout.addWidget(self.endTime, 3, 2, 1, 1)
        self.endLabel = QtWidgets.QLabel(self.frame)
        self.endLabel.setObjectName("endLabel")
        self.formLayout.addWidget(self.endLabel, 3, 1, 1, 1)
        self.fileLabel = QtWidgets.QLabel(self.frame)
        self.fileLabel.setObjectName("fileLabel")
        self.formLayout.addWidget(self.fileLabel, 0, 1, 1, 1)
        self.filePicker = QtWidgets.QToolButton(self.frame)
        self.filePicker.setObjectName("filePicker")
        self.formLayout.addWidget(self.filePicker, 0, 3, 1, 1)
        self.channelSelector = QtWidgets.QComboBox(self.frame)
        self.channelSelector.setObjectName("channelSelector")
        self.formLayout.addWidget(self.channelSelector, 1, 2, 1, 1)
        self.startLabel = QtWidgets.QLabel(self.frame)
        self.startLabel.setObjectName("startLabel")
        self.formLayout.addWidget(self.startLabel, 2, 1, 1, 1)
        self.analysisGridLayout.addWidget(self.frame, 0, 0, 2, 1)
        self.analysisGridLayout.setColumnStretch(2, 1)
        self.gridLayout_2.addLayout(self.analysisGridLayout, 0, 0, 1, 1)

        self.retranslateUi(analysisDialog)
        self.analysisTabs.setCurrentIndex(0)
        self.filePicker.clicked.connect(analysisDialog.select_wav_file)
        self.loadButton.clicked.connect(analysisDialog.load_file)
        self.analysisTabs.currentChanged['int'].connect(analysisDialog.show_chart)
        self.showLimitsButton.clicked.connect(analysisDialog.show_limits)
        self.magnitudeDecibels.clicked.connect(analysisDialog.show_chart)
        self.showSpectroButton.clicked.connect(analysisDialog.show_spectro)
        self.copyFilter.currentIndexChanged['int'].connect(analysisDialog.show_chart)
        self.magLimitType.currentIndexChanged['QString'].connect(analysisDialog.set_mag_range_type)
        self.updateChart.clicked.connect(analysisDialog.update_chart)
        self.markerSize.currentIndexChanged['int'].connect(analysisDialog.update_chart)
        QtCore.QMetaObject.connectSlotsByName(analysisDialog)

    def retranslateUi(self, analysisDialog):
        _translate = QtCore.QCoreApplication.translate
        analysisDialog.setWindowTitle(_translate("analysisDialog", "Dialog"))
        self.showLimitsButton.setText(_translate("analysisDialog", "..."))
        self.colourRangeLabel.setText(_translate("analysisDialog", "Colour Range"))
        self.updateChart.setText(_translate("analysisDialog", "..."))
        self.upperLimitLabel.setText(_translate("analysisDialog", "Magnitude Range"))
        self.showSpectroButton.setText(_translate("analysisDialog", "..."))
        self.magLimitType.setItemText(0, _translate("analysisDialog", "Constant"))
        self.magLimitType.setItemText(1, _translate("analysisDialog", "Peak"))
        self.magLimitType.setItemText(2, _translate("analysisDialog", "Average"))
        self.markerSize.setItemText(0, _translate("analysisDialog", "Small"))
        self.markerSize.setItemText(1, _translate("analysisDialog", "Medium"))
        self.markerSize.setItemText(2, _translate("analysisDialog", "Large"))
        self.label_2.setText(_translate("analysisDialog", "Marker Size"))
        self.analysisTabs.setTabText(self.analysisTabs.indexOf(self.spectrumTab), _translate("analysisDialog", "Peak Spectrum"))
        self.magnitudeDecibels.setText(_translate("analysisDialog", "Waveform in dBFS?"))
        self.headroomLabel.setText(_translate("analysisDialog", "Headroom (dB)"))
        self.analysisTabs.setTabText(self.analysisTabs.indexOf(self.waveformTab), _translate("analysisDialog", "Waveform"))
        self.label.setText(_translate("analysisDialog", "Filter"))
        self.startTime.setDisplayFormat(_translate("analysisDialog", "HH:mm:ss.zzz"))
        self.loadButton.setText(_translate("analysisDialog", "Load"))
        self.channelSelectorLabel.setText(_translate("analysisDialog", "Channel"))
        self.endTime.setDisplayFormat(_translate("analysisDialog", "HH:mm:ss.zzz"))
        self.endLabel.setText(_translate("analysisDialog", "End"))
        self.fileLabel.setText(_translate("analysisDialog", "File"))
        self.filePicker.setText(_translate("analysisDialog", "..."))
        self.startLabel.setText(_translate("analysisDialog", "Start"))

from mpl import MplWidget
