# Form implementation generated from reading ui file 'batch_design.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_batchDesignDialog(object):
    def setupUi(self, batchDesignDialog):
        batchDesignDialog.setObjectName("batchDesignDialog")
        batchDesignDialog.resize(760, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(batchDesignDialog)
        self.mainLayout.setObjectName("mainLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.designerLabelText = QtWidgets.QLabel(parent=batchDesignDialog)
        self.designerLabelText.setObjectName("designerLabelText")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.designerLabelText)
        self.designerCombo = QtWidgets.QComboBox(parent=batchDesignDialog)
        self.designerCombo.setObjectName("designerCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.designerCombo)
        self.queueDirLabelText = QtWidgets.QLabel(parent=batchDesignDialog)
        self.queueDirLabelText.setObjectName("queueDirLabelText")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.queueDirLabelText)
        self.queueDirLayout = QtWidgets.QHBoxLayout()
        self.queueDirLayout.setObjectName("queueDirLayout")
        self.queueDirEdit = QtWidgets.QLineEdit(parent=batchDesignDialog)
        self.queueDirEdit.setReadOnly(True)
        self.queueDirEdit.setObjectName("queueDirEdit")
        self.queueDirLayout.addWidget(self.queueDirEdit)
        self.browseQueueDirButton = QtWidgets.QToolButton(parent=batchDesignDialog)
        self.browseQueueDirButton.setObjectName("browseQueueDirButton")
        self.queueDirLayout.addWidget(self.browseQueueDirButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.queueDirLayout)
        self.workDirLabelText = QtWidgets.QLabel(parent=batchDesignDialog)
        self.workDirLabelText.setObjectName("workDirLabelText")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.workDirLabelText)
        self.workDirLayout = QtWidgets.QHBoxLayout()
        self.workDirLayout.setObjectName("workDirLayout")
        self.workDirEdit = QtWidgets.QLineEdit(parent=batchDesignDialog)
        self.workDirEdit.setReadOnly(True)
        self.workDirEdit.setObjectName("workDirEdit")
        self.workDirLayout.addWidget(self.workDirEdit)
        self.browseWorkDirButton = QtWidgets.QToolButton(parent=batchDesignDialog)
        self.browseWorkDirButton.setObjectName("browseWorkDirButton")
        self.workDirLayout.addWidget(self.browseWorkDirButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.workDirLayout)
        self.mainLayout.addLayout(self.formLayout)
        self.fileButtonsLayout = QtWidgets.QHBoxLayout()
        self.fileButtonsLayout.setObjectName("fileButtonsLayout")
        self.addFilesButton = QtWidgets.QPushButton(parent=batchDesignDialog)
        self.addFilesButton.setObjectName("addFilesButton")
        self.fileButtonsLayout.addWidget(self.addFilesButton)
        self.removeFileButton = QtWidgets.QPushButton(parent=batchDesignDialog)
        self.removeFileButton.setObjectName("removeFileButton")
        self.fileButtonsLayout.addWidget(self.removeFileButton)
        self.mainLayout.addLayout(self.fileButtonsLayout)
        self.filesList = QtWidgets.QListWidget(parent=batchDesignDialog)
        self.filesList.setObjectName("filesList")
        self.mainLayout.addWidget(self.filesList)
        self.runLayout = QtWidgets.QHBoxLayout()
        self.runLayout.setObjectName("runLayout")
        self.runButton = QtWidgets.QPushButton(parent=batchDesignDialog)
        self.runButton.setObjectName("runButton")
        self.runLayout.addWidget(self.runButton)
        self.runProgress = QtWidgets.QProgressBar(parent=batchDesignDialog)
        self.runProgress.setProperty("value", 0)
        self.runProgress.setObjectName("runProgress")
        self.runLayout.addWidget(self.runProgress)
        self.mainLayout.addLayout(self.runLayout)

        self.retranslateUi(batchDesignDialog)
        QtCore.QMetaObject.connectSlotsByName(batchDesignDialog)

    def retranslateUi(self, batchDesignDialog):
        _translate = QtCore.QCoreApplication.translate
        batchDesignDialog.setWindowTitle(_translate("batchDesignDialog", "Batch Design"))
        self.designerLabelText.setText(_translate("batchDesignDialog", "Designer"))
        self.queueDirLabelText.setText(_translate("batchDesignDialog", "Queue directory"))
        self.browseQueueDirButton.setText(_translate("batchDesignDialog", "..."))
        self.workDirLabelText.setText(_translate("batchDesignDialog", "Work directory"))
        self.browseWorkDirButton.setText(_translate("batchDesignDialog", "..."))
        self.addFilesButton.setText(_translate("batchDesignDialog", "Add Files..."))
        self.removeFileButton.setText(_translate("batchDesignDialog", "Remove"))
        self.runButton.setText(_translate("batchDesignDialog", "Run"))
