# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beq.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1511, 956)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetGridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.widgetGridLayout.setObjectName("widgetGridLayout")
        self.panes = QtWidgets.QHBoxLayout()
        self.panes.setSpacing(9)
        self.panes.setObjectName("panes")
        self.leftPane = QtWidgets.QGridLayout()
        self.leftPane.setObjectName("leftPane")
        self.filterChart = MplWidget(self.centralwidget)
        self.filterChart.setObjectName("filterChart")
        self.leftPane.addWidget(self.filterChart, 1, 0, 1, 4)
        self.referenceSeriesLabel = QtWidgets.QLabel(self.centralwidget)
        self.referenceSeriesLabel.setObjectName("referenceSeriesLabel")
        self.leftPane.addWidget(self.referenceSeriesLabel, 0, 0, 1, 1)
        self.updateChart = QtWidgets.QPushButton(self.centralwidget)
        self.updateChart.setObjectName("updateChart")
        self.leftPane.addWidget(self.updateChart, 0, 3, 1, 1)
        self.referenceSeries = QtWidgets.QComboBox(self.centralwidget)
        self.referenceSeries.setObjectName("referenceSeries")
        self.leftPane.addWidget(self.referenceSeries, 0, 1, 1, 1)
        self.limitsButton = QtWidgets.QToolButton(self.centralwidget)
        self.limitsButton.setObjectName("limitsButton")
        self.leftPane.addWidget(self.limitsButton, 0, 2, 1, 1)
        self.leftPane.setColumnStretch(1, 1)
        self.panes.addLayout(self.leftPane)
        self.rightPane = QtWidgets.QGridLayout()
        self.rightPane.setObjectName("rightPane")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.rightPane.addWidget(self.label_2, 0, 0, 1, 3)
        self.signalView = QtWidgets.QTableView(self.centralwidget)
        self.signalView.setObjectName("signalView")
        self.rightPane.addWidget(self.signalView, 2, 0, 1, 3)
        self.editSignalButton = QtWidgets.QPushButton(self.centralwidget)
        self.editSignalButton.setEnabled(False)
        self.editSignalButton.setObjectName("editSignalButton")
        self.rightPane.addWidget(self.editSignalButton, 1, 1, 1, 1)
        self.loadPreset2 = QtWidgets.QPushButton(self.centralwidget)
        self.loadPreset2.setEnabled(False)
        self.loadPreset2.setObjectName("loadPreset2")
        self.rightPane.addWidget(self.loadPreset2, 4, 1, 1, 1)
        self.loadPreset3 = QtWidgets.QPushButton(self.centralwidget)
        self.loadPreset3.setEnabled(False)
        self.loadPreset3.setObjectName("loadPreset3")
        self.rightPane.addWidget(self.loadPreset3, 4, 2, 1, 1)
        self.loadPreset1 = QtWidgets.QPushButton(self.centralwidget)
        self.loadPreset1.setEnabled(False)
        self.loadPreset1.setObjectName("loadPreset1")
        self.rightPane.addWidget(self.loadPreset1, 4, 0, 1, 1)
        self.addFilterButton = QtWidgets.QPushButton(self.centralwidget)
        self.addFilterButton.setEnabled(True)
        self.addFilterButton.setObjectName("addFilterButton")
        self.rightPane.addWidget(self.addFilterButton, 5, 0, 1, 1)
        self.editFilterButton = QtWidgets.QPushButton(self.centralwidget)
        self.editFilterButton.setEnabled(False)
        self.editFilterButton.setFlat(False)
        self.editFilterButton.setObjectName("editFilterButton")
        self.rightPane.addWidget(self.editFilterButton, 5, 1, 1, 1)
        self.deleteFilterButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteFilterButton.setEnabled(False)
        self.deleteFilterButton.setObjectName("deleteFilterButton")
        self.rightPane.addWidget(self.deleteFilterButton, 5, 2, 1, 1)
        self.filterView = QtWidgets.QTableView(self.centralwidget)
        self.filterView.setObjectName("filterView")
        self.rightPane.addWidget(self.filterView, 6, 0, 1, 3)
        self.deleteSignalButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteSignalButton.setEnabled(False)
        self.deleteSignalButton.setObjectName("deleteSignalButton")
        self.rightPane.addWidget(self.deleteSignalButton, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.rightPane.addWidget(self.label, 3, 0, 1, 3)
        self.addSignalButton = QtWidgets.QPushButton(self.centralwidget)
        self.addSignalButton.setObjectName("addSignalButton")
        self.rightPane.addWidget(self.addSignalButton, 1, 0, 1, 1)
        self.showIndividualFilters = QtWidgets.QCheckBox(self.centralwidget)
        self.showIndividualFilters.setChecked(True)
        self.showIndividualFilters.setObjectName("showIndividualFilters")
        self.rightPane.addWidget(self.showIndividualFilters, 7, 0, 1, 3)
        self.panes.addLayout(self.rightPane)
        self.panes.setStretch(0, 3)
        self.panes.setStretch(1, 1)
        self.widgetGridLayout.addLayout(self.panes, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1511, 31))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuPresets = QtWidgets.QMenu(self.menuSettings)
        self.menuPresets.setObjectName("menuPresets")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionShow_Logs = QtWidgets.QAction(MainWindow)
        self.actionShow_Logs.setObjectName("actionShow_Logs")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExtract_Audio = QtWidgets.QAction(MainWindow)
        self.actionExtract_Audio.setObjectName("actionExtract_Audio")
        self.actionPresets = QtWidgets.QAction(MainWindow)
        self.actionPresets.setObjectName("actionPresets")
        self.actionSave_Preset_1 = QtWidgets.QAction(MainWindow)
        self.actionSave_Preset_1.setObjectName("actionSave_Preset_1")
        self.actionClear_Preset_1 = QtWidgets.QAction(MainWindow)
        self.actionClear_Preset_1.setObjectName("actionClear_Preset_1")
        self.actionSave_Preset_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_Preset_2.setObjectName("actionSave_Preset_2")
        self.actionClear_Preset_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_Preset_2.setObjectName("actionClear_Preset_2")
        self.actionSave_Preset_3 = QtWidgets.QAction(MainWindow)
        self.actionSave_Preset_3.setObjectName("actionSave_Preset_3")
        self.actionClear_Preset_3 = QtWidgets.QAction(MainWindow)
        self.actionClear_Preset_3.setObjectName("actionClear_Preset_3")
        self.menuHelp.addAction(self.actionShow_Logs)
        self.menuPresets.addAction(self.actionSave_Preset_1)
        self.menuPresets.addAction(self.actionSave_Preset_2)
        self.menuPresets.addAction(self.actionSave_Preset_3)
        self.menuPresets.addSeparator()
        self.menuPresets.addAction(self.actionClear_Preset_1)
        self.menuPresets.addAction(self.actionClear_Preset_2)
        self.menuPresets.addAction(self.actionClear_Preset_3)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuPresets.menuAction())
        self.menuFile.addAction(self.actionExtract_Audio)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.addFilterButton.clicked.connect(MainWindow.addFilter)
        self.deleteFilterButton.clicked.connect(MainWindow.deleteFilter)
        self.updateChart.clicked.connect(MainWindow.display)
        self.showIndividualFilters.clicked.connect(MainWindow.changeVisibilityOfIndividualFilters)
        self.editFilterButton.clicked.connect(MainWindow.editFilter)
        self.addSignalButton.clicked.connect(MainWindow.addSignal)
        self.editSignalButton.clicked.connect(MainWindow.editSignal)
        self.deleteSignalButton.clicked.connect(MainWindow.deleteSignal)
        self.referenceSeries.currentIndexChanged['int'].connect(MainWindow.normaliseMagnitude)
        self.limitsButton.clicked.connect(MainWindow.showLimits)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BEQ Designer"))
        self.referenceSeriesLabel.setText(_translate("MainWindow", "Reference: "))
        self.updateChart.setText(_translate("MainWindow", "Redraw"))
        self.limitsButton.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Audio"))
        self.editSignalButton.setText(_translate("MainWindow", "Edit"))
        self.loadPreset2.setText(_translate("MainWindow", "Preset 2"))
        self.loadPreset3.setText(_translate("MainWindow", "Preset 3"))
        self.loadPreset1.setText(_translate("MainWindow", "Preset 1"))
        self.addFilterButton.setText(_translate("MainWindow", "Add"))
        self.addFilterButton.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.editFilterButton.setText(_translate("MainWindow", "Edit"))
        self.deleteFilterButton.setText(_translate("MainWindow", "Delete"))
        self.deleteFilterButton.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.deleteSignalButton.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Filters"))
        self.addSignalButton.setText(_translate("MainWindow", "Add"))
        self.addSignalButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+="))
        self.showIndividualFilters.setText(_translate("MainWindow", "Show Individual Filters"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuPresets.setTitle(_translate("MainWindow", "Presets"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionShow_Logs.setText(_translate("MainWindow", "Show Logs"))
        self.actionShow_Logs.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionExtract_Audio.setText(_translate("MainWindow", "Extract Audio"))
        self.actionExtract_Audio.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionPresets.setText(_translate("MainWindow", "Presets"))
        self.actionSave_Preset_1.setText(_translate("MainWindow", "Save Preset 1"))
        self.actionSave_Preset_1.setShortcut(_translate("MainWindow", "Ctrl+Shift+1"))
        self.actionClear_Preset_1.setText(_translate("MainWindow", "Clear Preset 1"))
        self.actionSave_Preset_2.setText(_translate("MainWindow", "Save Preset 2"))
        self.actionSave_Preset_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+2"))
        self.actionClear_Preset_2.setText(_translate("MainWindow", "Clear Preset 2"))
        self.actionSave_Preset_3.setText(_translate("MainWindow", "Save Preset 3"))
        self.actionSave_Preset_3.setShortcut(_translate("MainWindow", "Ctrl+Shift+3"))
        self.actionClear_Preset_3.setText(_translate("MainWindow", "Clear Preset 3"))

from mpl import MplWidget
