# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beq.ui',
# licensing of 'beq.ui' applies.
#
# Created: Sat Jun 29 23:16:13 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1569, 968)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetGridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.widgetGridLayout.setObjectName("widgetGridLayout")
        self.panes = QtWidgets.QHBoxLayout()
        self.panes.setSpacing(9)
        self.panes.setObjectName("panes")
        self.leftPane = QtWidgets.QGridLayout()
        self.leftPane.setObjectName("leftPane")
        self.showValuesButton = QtWidgets.QToolButton(self.centralwidget)
        self.showValuesButton.setObjectName("showValuesButton")
        self.leftPane.addWidget(self.showValuesButton, 0, 6, 1, 1)
        self.filterReference = QtWidgets.QComboBox(self.centralwidget)
        self.filterReference.setObjectName("filterReference")
        self.filterReference.addItem("")
        self.leftPane.addWidget(self.filterReference, 0, 2, 1, 1)
        self.limitsButton = QtWidgets.QToolButton(self.centralwidget)
        self.limitsButton.setObjectName("limitsButton")
        self.leftPane.addWidget(self.limitsButton, 0, 7, 1, 1)
        self.signalReference = QtWidgets.QComboBox(self.centralwidget)
        self.signalReference.setObjectName("signalReference")
        self.signalReference.addItem("")
        self.leftPane.addWidget(self.signalReference, 0, 1, 1, 1)
        self.referenceLabel = QtWidgets.QLabel(self.centralwidget)
        self.referenceLabel.setObjectName("referenceLabel")
        self.leftPane.addWidget(self.referenceLabel, 0, 0, 1, 1)
        self.chartSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.chartSplitter.setLineWidth(1)
        self.chartSplitter.setOrientation(QtCore.Qt.Vertical)
        self.chartSplitter.setObjectName("chartSplitter")
        self.mainChartContainer = QtWidgets.QFrame(self.chartSplitter)
        self.mainChartContainer.setObjectName("mainChartContainer")
        self.mainChartLayout = QtWidgets.QHBoxLayout(self.mainChartContainer)
        self.mainChartLayout.setObjectName("mainChartLayout")
        self.mainChartLeftTools = QtWidgets.QFrame(self.mainChartContainer)
        self.mainChartLeftTools.setLineWidth(0)
        self.mainChartLeftTools.setObjectName("mainChartLeftTools")
        self.mainChartLeftToolLayout = QtWidgets.QVBoxLayout(self.mainChartLeftTools)
        self.mainChartLeftToolLayout.setSpacing(0)
        self.mainChartLeftToolLayout.setContentsMargins(0, 0, 0, 0)
        self.mainChartLeftToolLayout.setObjectName("mainChartLeftToolLayout")
        self.mainChartLeftToolTopLayout = QtWidgets.QVBoxLayout()
        self.mainChartLeftToolTopLayout.setObjectName("mainChartLeftToolTopLayout")
        self.y1MaxPlus10Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MaxPlus10Button.setObjectName("y1MaxPlus10Button")
        self.mainChartLeftToolTopLayout.addWidget(self.y1MaxPlus10Button)
        self.y1MaxPlus5Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MaxPlus5Button.setObjectName("y1MaxPlus5Button")
        self.mainChartLeftToolTopLayout.addWidget(self.y1MaxPlus5Button)
        self.y1MaxMinus5Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MaxMinus5Button.setObjectName("y1MaxMinus5Button")
        self.mainChartLeftToolTopLayout.addWidget(self.y1MaxMinus5Button)
        self.y1MaxMinus10Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MaxMinus10Button.setObjectName("y1MaxMinus10Button")
        self.mainChartLeftToolTopLayout.addWidget(self.y1MaxMinus10Button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartLeftToolTopLayout.addItem(spacerItem)
        self.mainChartLeftToolLayout.addLayout(self.mainChartLeftToolTopLayout)
        self.mainChartLeftToolMidLayout = QtWidgets.QVBoxLayout()
        self.mainChartLeftToolMidLayout.setObjectName("mainChartLeftToolMidLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartLeftToolMidLayout.addItem(spacerItem1)
        self.y1AutoOnButton = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1AutoOnButton.setCheckable(True)
        self.y1AutoOnButton.setObjectName("y1AutoOnButton")
        self.mainChartLeftToolMidLayout.addWidget(self.y1AutoOnButton)
        self.y1AutoOffButton = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1AutoOffButton.setCheckable(True)
        self.y1AutoOffButton.setObjectName("y1AutoOffButton")
        self.mainChartLeftToolMidLayout.addWidget(self.y1AutoOffButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartLeftToolMidLayout.addItem(spacerItem2)
        self.mainChartLeftToolLayout.addLayout(self.mainChartLeftToolMidLayout)
        self.mainChartLeftToolBottomLayout = QtWidgets.QVBoxLayout()
        self.mainChartLeftToolBottomLayout.setObjectName("mainChartLeftToolBottomLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartLeftToolBottomLayout.addItem(spacerItem3)
        self.y1MinPlus10Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MinPlus10Button.setObjectName("y1MinPlus10Button")
        self.mainChartLeftToolBottomLayout.addWidget(self.y1MinPlus10Button)
        self.y1MinPlus5Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MinPlus5Button.setObjectName("y1MinPlus5Button")
        self.mainChartLeftToolBottomLayout.addWidget(self.y1MinPlus5Button)
        self.y1MinMinus5Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MinMinus5Button.setObjectName("y1MinMinus5Button")
        self.mainChartLeftToolBottomLayout.addWidget(self.y1MinMinus5Button)
        self.y1MinMinus10Button = QtWidgets.QToolButton(self.mainChartLeftTools)
        self.y1MinMinus10Button.setObjectName("y1MinMinus10Button")
        self.mainChartLeftToolBottomLayout.addWidget(self.y1MinMinus10Button)
        self.mainChartLeftToolLayout.addLayout(self.mainChartLeftToolBottomLayout)
        self.mainChartLayout.addWidget(self.mainChartLeftTools)
        self.mainChart = MplWidget(self.mainChartContainer)
        self.mainChart.setObjectName("mainChart")
        self.mainChartLayout.addWidget(self.mainChart)
        self.mainChartRightTools = QtWidgets.QFrame(self.mainChartContainer)
        self.mainChartRightTools.setLineWidth(0)
        self.mainChartRightTools.setObjectName("mainChartRightTools")
        self.mainChartRightToolLayout = QtWidgets.QVBoxLayout(self.mainChartRightTools)
        self.mainChartRightToolLayout.setSpacing(0)
        self.mainChartRightToolLayout.setContentsMargins(0, 0, 0, 0)
        self.mainChartRightToolLayout.setObjectName("mainChartRightToolLayout")
        self.mainChartRightToolTopLayout = QtWidgets.QVBoxLayout()
        self.mainChartRightToolTopLayout.setObjectName("mainChartRightToolTopLayout")
        self.y2MaxPlus10Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MaxPlus10Button.setObjectName("y2MaxPlus10Button")
        self.mainChartRightToolTopLayout.addWidget(self.y2MaxPlus10Button)
        self.y2MaxPlus5Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MaxPlus5Button.setObjectName("y2MaxPlus5Button")
        self.mainChartRightToolTopLayout.addWidget(self.y2MaxPlus5Button)
        self.y2MaxMinus5Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MaxMinus5Button.setObjectName("y2MaxMinus5Button")
        self.mainChartRightToolTopLayout.addWidget(self.y2MaxMinus5Button)
        self.y2MaxMinus10Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MaxMinus10Button.setObjectName("y2MaxMinus10Button")
        self.mainChartRightToolTopLayout.addWidget(self.y2MaxMinus10Button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartRightToolTopLayout.addItem(spacerItem4)
        self.mainChartRightToolLayout.addLayout(self.mainChartRightToolTopLayout)
        self.mainChartRightToolMidLayout = QtWidgets.QVBoxLayout()
        self.mainChartRightToolMidLayout.setObjectName("mainChartRightToolMidLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartRightToolMidLayout.addItem(spacerItem5)
        self.y2AutoOnButton = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2AutoOnButton.setCheckable(True)
        self.y2AutoOnButton.setObjectName("y2AutoOnButton")
        self.mainChartRightToolMidLayout.addWidget(self.y2AutoOnButton)
        self.y2AutoOffButton = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2AutoOffButton.setCheckable(True)
        self.y2AutoOffButton.setObjectName("y2AutoOffButton")
        self.mainChartRightToolMidLayout.addWidget(self.y2AutoOffButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartRightToolMidLayout.addItem(spacerItem6)
        self.mainChartRightToolLayout.addLayout(self.mainChartRightToolMidLayout)
        self.mainChartRightToolBottomLayout = QtWidgets.QVBoxLayout()
        self.mainChartRightToolBottomLayout.setObjectName("mainChartRightToolBottomLayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainChartRightToolBottomLayout.addItem(spacerItem7)
        self.y2MinPlus10Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MinPlus10Button.setObjectName("y2MinPlus10Button")
        self.mainChartRightToolBottomLayout.addWidget(self.y2MinPlus10Button)
        self.y2MinPlus5Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MinPlus5Button.setObjectName("y2MinPlus5Button")
        self.mainChartRightToolBottomLayout.addWidget(self.y2MinPlus5Button)
        self.y2MinMinus5Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MinMinus5Button.setObjectName("y2MinMinus5Button")
        self.mainChartRightToolBottomLayout.addWidget(self.y2MinMinus5Button)
        self.y2MinMinus10Button = QtWidgets.QToolButton(self.mainChartRightTools)
        self.y2MinMinus10Button.setObjectName("y2MinMinus10Button")
        self.mainChartRightToolBottomLayout.addWidget(self.y2MinMinus10Button)
        self.mainChartRightToolLayout.addLayout(self.mainChartRightToolBottomLayout)
        self.mainChartLayout.addWidget(self.mainChartRightTools)
        self.mainChartLayout.setStretch(1, 1)
        self.waveformContainer = QtWidgets.QFrame(self.chartSplitter)
        self.waveformContainer.setObjectName("waveformContainer")
        self.waveformLayout = QtWidgets.QHBoxLayout(self.waveformContainer)
        self.waveformLayout.setObjectName("waveformLayout")
        self.waveformControls = QtWidgets.QGridLayout()
        self.waveformControls.setObjectName("waveformControls")
        self.signalSelectorLabel = QtWidgets.QLabel(self.waveformContainer)
        self.signalSelectorLabel.setObjectName("signalSelectorLabel")
        self.waveformControls.addWidget(self.signalSelectorLabel, 0, 0, 1, 1)
        self.signalSelector = QtWidgets.QComboBox(self.waveformContainer)
        self.signalSelector.setObjectName("signalSelector")
        self.waveformControls.addWidget(self.signalSelector, 0, 1, 1, 1)
        self.sourceFileLabel = QtWidgets.QLabel(self.waveformContainer)
        self.sourceFileLabel.setObjectName("sourceFileLabel")
        self.waveformControls.addWidget(self.sourceFileLabel, 1, 0, 1, 1)
        self.sourceFileLayout = QtWidgets.QHBoxLayout()
        self.sourceFileLayout.setObjectName("sourceFileLayout")
        self.sourceFile = QtWidgets.QLineEdit(self.waveformContainer)
        self.sourceFile.setReadOnly(True)
        self.sourceFile.setObjectName("sourceFile")
        self.sourceFileLayout.addWidget(self.sourceFile)
        self.loadSignalButton = QtWidgets.QToolButton(self.waveformContainer)
        self.loadSignalButton.setObjectName("loadSignalButton")
        self.sourceFileLayout.addWidget(self.loadSignalButton)
        self.waveformControls.addLayout(self.sourceFileLayout, 1, 1, 1, 1)
        self.checkboxContainer = QtWidgets.QHBoxLayout()
        self.checkboxContainer.setObjectName("checkboxContainer")
        self.waveformIsFiltered = QtWidgets.QCheckBox(self.waveformContainer)
        self.waveformIsFiltered.setObjectName("waveformIsFiltered")
        self.checkboxContainer.addWidget(self.waveformIsFiltered)
        self.hardClipWaveform = QtWidgets.QCheckBox(self.waveformContainer)
        self.hardClipWaveform.setObjectName("hardClipWaveform")
        self.checkboxContainer.addWidget(self.hardClipWaveform)
        self.waveformControls.addLayout(self.checkboxContainer, 2, 0, 1, 2)
        self.headroomLabel = QtWidgets.QLabel(self.waveformContainer)
        self.headroomLabel.setObjectName("headroomLabel")
        self.waveformControls.addWidget(self.headroomLabel, 3, 0, 1, 1)
        self.headroom = QtWidgets.QDoubleSpinBox(self.waveformContainer)
        self.headroom.setEnabled(False)
        self.headroom.setMinimum(-120.0)
        self.headroom.setMaximum(120.0)
        self.headroom.setSingleStep(0.01)
        self.headroom.setObjectName("headroom")
        self.waveformControls.addWidget(self.headroom, 3, 1, 1, 1)
        self.startTimeLabel = QtWidgets.QLabel(self.waveformContainer)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.waveformControls.addWidget(self.startTimeLabel, 4, 0, 1, 1)
        self.startTime = QtWidgets.QTimeEdit(self.waveformContainer)
        self.startTime.setObjectName("startTime")
        self.waveformControls.addWidget(self.startTime, 4, 1, 1, 1)
        self.endTime = QtWidgets.QTimeEdit(self.waveformContainer)
        self.endTime.setObjectName("endTime")
        self.waveformControls.addWidget(self.endTime, 5, 1, 1, 1)
        self.endTimeLabel = QtWidgets.QLabel(self.waveformContainer)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.waveformControls.addWidget(self.endTimeLabel, 5, 0, 1, 1)
        self.yRangeLabel = QtWidgets.QLabel(self.waveformContainer)
        self.yRangeLabel.setObjectName("yRangeLabel")
        self.waveformControls.addWidget(self.yRangeLabel, 6, 0, 1, 1)
        self.yRangeLayout = QtWidgets.QHBoxLayout()
        self.yRangeLayout.setObjectName("yRangeLayout")
        self.yMin = QtWidgets.QDoubleSpinBox(self.waveformContainer)
        self.yMin.setMinimum(-1.0)
        self.yMin.setMaximum(1.0)
        self.yMin.setSingleStep(0.01)
        self.yMin.setProperty("value", -1.0)
        self.yMin.setObjectName("yMin")
        self.yRangeLayout.addWidget(self.yMin)
        self.yMax = QtWidgets.QDoubleSpinBox(self.waveformContainer)
        self.yMax.setMinimum(-1.0)
        self.yMax.setMaximum(1.0)
        self.yMax.setSingleStep(0.01)
        self.yMax.setProperty("value", 1.0)
        self.yMax.setObjectName("yMax")
        self.yRangeLayout.addWidget(self.yMax)
        self.waveformControls.addLayout(self.yRangeLayout, 6, 1, 1, 1)
        self.bmHeaderLabel = QtWidgets.QLabel(self.waveformContainer)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.bmHeaderLabel.setFont(font)
        self.bmHeaderLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.bmHeaderLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bmHeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bmHeaderLabel.setObjectName("bmHeaderLabel")
        self.waveformControls.addWidget(self.bmHeaderLabel, 7, 0, 1, 2)
        self.bmlpfPositionLabel = QtWidgets.QLabel(self.waveformContainer)
        self.bmlpfPositionLabel.setObjectName("bmlpfPositionLabel")
        self.waveformControls.addWidget(self.bmlpfPositionLabel, 8, 0, 1, 1)
        self.bmlpfPosition = QtWidgets.QComboBox(self.waveformContainer)
        self.bmlpfPosition.setObjectName("bmlpfPosition")
        self.waveformControls.addWidget(self.bmlpfPosition, 8, 1, 1, 1)
        self.bmClippingLabel = QtWidgets.QLabel(self.waveformContainer)
        self.bmClippingLabel.setObjectName("bmClippingLabel")
        self.waveformControls.addWidget(self.bmClippingLabel, 9, 0, 1, 1)
        self.bmClippingOptions = QtWidgets.QHBoxLayout()
        self.bmClippingOptions.setObjectName("bmClippingOptions")
        self.bmClipBefore = QtWidgets.QCheckBox(self.waveformContainer)
        self.bmClipBefore.setObjectName("bmClipBefore")
        self.bmClippingOptions.addWidget(self.bmClipBefore)
        self.bmClipAfter = QtWidgets.QCheckBox(self.waveformContainer)
        self.bmClipAfter.setObjectName("bmClipAfter")
        self.bmClippingOptions.addWidget(self.bmClipAfter)
        self.waveformControls.addLayout(self.bmClippingOptions, 9, 1, 1, 1)
        self.bmHeadroomLabel = QtWidgets.QLabel(self.waveformContainer)
        self.bmHeadroomLabel.setObjectName("bmHeadroomLabel")
        self.waveformControls.addWidget(self.bmHeadroomLabel, 10, 0, 1, 1)
        self.bmHeadroom = QtWidgets.QComboBox(self.waveformContainer)
        self.bmHeadroom.setObjectName("bmHeadroom")
        self.bmHeadroom.addItem("")
        self.bmHeadroom.addItem("")
        self.bmHeadroom.addItem("")
        self.bmHeadroom.addItem("")
        self.bmHeadroom.addItem("")
        self.waveformControls.addWidget(self.bmHeadroom, 10, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.compareSpectrumButton = QtWidgets.QToolButton(self.waveformContainer)
        self.compareSpectrumButton.setObjectName("compareSpectrumButton")
        self.horizontalLayout.addWidget(self.compareSpectrumButton)
        self.showSpectrumButton = QtWidgets.QToolButton(self.waveformContainer)
        self.showSpectrumButton.setObjectName("showSpectrumButton")
        self.horizontalLayout.addWidget(self.showSpectrumButton)
        self.hideSpectrumButton = QtWidgets.QToolButton(self.waveformContainer)
        self.hideSpectrumButton.setObjectName("hideSpectrumButton")
        self.horizontalLayout.addWidget(self.hideSpectrumButton)
        self.filteredSpectrumLimitsButton = QtWidgets.QToolButton(self.waveformContainer)
        self.filteredSpectrumLimitsButton.setObjectName("filteredSpectrumLimitsButton")
        self.horizontalLayout.addWidget(self.filteredSpectrumLimitsButton)
        self.zoomInButton = QtWidgets.QToolButton(self.waveformContainer)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout.addWidget(self.zoomInButton)
        self.zoomOutButton = QtWidgets.QToolButton(self.waveformContainer)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout.addWidget(self.zoomOutButton)
        self.waveformControls.addLayout(self.horizontalLayout, 11, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.waveformControls.addItem(spacerItem8, 12, 0, 1, 2)
        self.waveformLayout.addLayout(self.waveformControls)
        self.waveformChart = PlotWidgetWithDateAxis(self.waveformContainer)
        self.waveformChart.setObjectName("waveformChart")
        self.waveformLayout.addWidget(self.waveformChart)
        self.filteredSpectrumChart = MplWidget(self.waveformContainer)
        self.filteredSpectrumChart.setObjectName("filteredSpectrumChart")
        self.waveformLayout.addWidget(self.filteredSpectrumChart)
        self.waveformLayout.setStretch(1, 1)
        self.waveformLayout.setStretch(2, 1)
        self.leftPane.addWidget(self.chartSplitter, 1, 0, 1, 9)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.leftPane.addWidget(self.label, 0, 3, 1, 1)
        self.octaveSmoothing = QtWidgets.QComboBox(self.centralwidget)
        self.octaveSmoothing.setObjectName("octaveSmoothing")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.octaveSmoothing.addItem("")
        self.leftPane.addWidget(self.octaveSmoothing, 0, 4, 1, 1)
        self.smoothAllSignals = QtWidgets.QCheckBox(self.centralwidget)
        self.smoothAllSignals.setObjectName("smoothAllSignals")
        self.leftPane.addWidget(self.smoothAllSignals, 0, 5, 1, 1)
        self.leftPane.setColumnStretch(1, 1)
        self.leftPane.setColumnStretch(2, 1)
        self.panes.addLayout(self.leftPane)
        self.rightPane = QtWidgets.QVBoxLayout()
        self.rightPane.setObjectName("rightPane")
        self.signalsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.signalsLabel.setFont(font)
        self.signalsLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.signalsLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.signalsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.signalsLabel.setObjectName("signalsLabel")
        self.rightPane.addWidget(self.signalsLabel)
        self.signalButtonsLayout = QtWidgets.QHBoxLayout()
        self.signalButtonsLayout.setObjectName("signalButtonsLayout")
        self.addSignalButton = QtWidgets.QToolButton(self.centralwidget)
        self.addSignalButton.setProperty("flat", False)
        self.addSignalButton.setObjectName("addSignalButton")
        self.signalButtonsLayout.addWidget(self.addSignalButton)
        self.linkSignalButton = QtWidgets.QToolButton(self.centralwidget)
        self.linkSignalButton.setEnabled(False)
        self.linkSignalButton.setObjectName("linkSignalButton")
        self.signalButtonsLayout.addWidget(self.linkSignalButton)
        self.deleteSignalButton = QtWidgets.QToolButton(self.centralwidget)
        self.deleteSignalButton.setEnabled(False)
        self.deleteSignalButton.setObjectName("deleteSignalButton")
        self.signalButtonsLayout.addWidget(self.deleteSignalButton)
        self.clearSignalsButton = QtWidgets.QToolButton(self.centralwidget)
        self.clearSignalsButton.setEnabled(False)
        self.clearSignalsButton.setObjectName("clearSignalsButton")
        self.signalButtonsLayout.addWidget(self.clearSignalsButton)
        self.rightPane.addLayout(self.signalButtonsLayout)
        self.signalView = QtWidgets.QTableView(self.centralwidget)
        self.signalView.setObjectName("signalView")
        self.rightPane.addWidget(self.signalView)
        self.filtersLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.filtersLabel.setFont(font)
        self.filtersLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.filtersLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.filtersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filtersLabel.setObjectName("filtersLabel")
        self.rightPane.addWidget(self.filtersLabel)
        self.filterToolbarLayout = QtWidgets.QHBoxLayout()
        self.filterToolbarLayout.setObjectName("filterToolbarLayout")
        self.preset1Button = QtWidgets.QToolButton(self.centralwidget)
        self.preset1Button.setEnabled(False)
        self.preset1Button.setToolTip("")
        self.preset1Button.setObjectName("preset1Button")
        self.filterToolbarLayout.addWidget(self.preset1Button)
        self.preset2Button = QtWidgets.QToolButton(self.centralwidget)
        self.preset2Button.setEnabled(False)
        self.preset2Button.setToolTip("")
        self.preset2Button.setObjectName("preset2Button")
        self.filterToolbarLayout.addWidget(self.preset2Button)
        self.preset3Button = QtWidgets.QToolButton(self.centralwidget)
        self.preset3Button.setEnabled(False)
        self.preset3Button.setToolTip("")
        self.preset3Button.setStatusTip("")
        self.preset3Button.setObjectName("preset3Button")
        self.filterToolbarLayout.addWidget(self.preset3Button)
        self.addFilterButton = QtWidgets.QToolButton(self.centralwidget)
        self.addFilterButton.setEnabled(True)
        self.addFilterButton.setObjectName("addFilterButton")
        self.filterToolbarLayout.addWidget(self.addFilterButton)
        self.editFilterButton = QtWidgets.QToolButton(self.centralwidget)
        self.editFilterButton.setEnabled(False)
        self.editFilterButton.setProperty("flat", False)
        self.editFilterButton.setObjectName("editFilterButton")
        self.filterToolbarLayout.addWidget(self.editFilterButton)
        self.deleteFilterButton = QtWidgets.QToolButton(self.centralwidget)
        self.deleteFilterButton.setEnabled(False)
        self.deleteFilterButton.setObjectName("deleteFilterButton")
        self.filterToolbarLayout.addWidget(self.deleteFilterButton)
        self.clearFiltersButton = QtWidgets.QToolButton(self.centralwidget)
        self.clearFiltersButton.setEnabled(False)
        self.clearFiltersButton.setObjectName("clearFiltersButton")
        self.filterToolbarLayout.addWidget(self.clearFiltersButton)
        self.rightPane.addLayout(self.filterToolbarLayout)
        self.filterView = QtWidgets.QTableView(self.centralwidget)
        self.filterView.setObjectName("filterView")
        self.rightPane.addWidget(self.filterView)
        self.selectorsLayout = QtWidgets.QGridLayout()
        self.selectorsLayout.setObjectName("selectorsLayout")
        self.showSignalsLabel = QtWidgets.QLabel(self.centralwidget)
        self.showSignalsLabel.setObjectName("showSignalsLabel")
        self.selectorsLayout.addWidget(self.showSignalsLabel, 0, 0, 1, 1)
        self.showFiltersLabel = QtWidgets.QLabel(self.centralwidget)
        self.showFiltersLabel.setObjectName("showFiltersLabel")
        self.selectorsLayout.addWidget(self.showFiltersLabel, 0, 1, 1, 1)
        self.showFiltersLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.showFiltersLabel1.setObjectName("showFiltersLabel1")
        self.selectorsLayout.addWidget(self.showFiltersLabel1, 0, 2, 1, 1)
        self.showSignals = QtWidgets.QComboBox(self.centralwidget)
        self.showSignals.setObjectName("showSignals")
        self.selectorsLayout.addWidget(self.showSignals, 1, 0, 1, 1)
        self.showFilteredSignals = QtWidgets.QComboBox(self.centralwidget)
        self.showFilteredSignals.setObjectName("showFilteredSignals")
        self.selectorsLayout.addWidget(self.showFilteredSignals, 1, 1, 1, 1)
        self.showFilters = QtWidgets.QComboBox(self.centralwidget)
        self.showFilters.setObjectName("showFilters")
        self.selectorsLayout.addWidget(self.showFilters, 1, 2, 1, 1)
        self.equalEnergyTilt = QtWidgets.QCheckBox(self.centralwidget)
        self.equalEnergyTilt.setObjectName("equalEnergyTilt")
        self.selectorsLayout.addWidget(self.equalEnergyTilt, 2, 2, 1, 1)
        self.showLegend = QtWidgets.QCheckBox(self.centralwidget)
        self.showLegend.setChecked(True)
        self.showLegend.setObjectName("showLegend")
        self.selectorsLayout.addWidget(self.showLegend, 2, 0, 1, 1)
        self.rightPane.addLayout(self.selectorsLayout)
        self.panes.addLayout(self.rightPane)
        self.panes.setStretch(0, 3)
        self.panes.setStretch(1, 1)
        self.widgetGridLayout.addLayout(self.panes, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1569, 18))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPresets = QtWidgets.QMenu(self.menuFile)
        self.menuPresets.setObjectName("menuPresets")
        self.menuLoad = QtWidgets.QMenu(self.menuPresets)
        self.menuLoad.setObjectName("menuLoad")
        self.menu_Clear = QtWidgets.QMenu(self.menuPresets)
        self.menu_Clear.setObjectName("menu_Clear")
        self.menu_Store = QtWidgets.QMenu(self.menuPresets)
        self.menu_Store.setObjectName("menu_Store")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionShow_Logs = QtWidgets.QAction(MainWindow)
        self.actionShow_Logs.setObjectName("actionShow_Logs")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExtract_Audio = QtWidgets.QAction(MainWindow)
        self.actionExtract_Audio.setObjectName("actionExtract_Audio")
        self.actionPresets = QtWidgets.QAction(MainWindow)
        self.actionPresets.setObjectName("actionPresets")
        self.actionClear_Preset_3 = QtWidgets.QAction(MainWindow)
        self.actionClear_Preset_3.setObjectName("actionClear_Preset_3")
        self.actionSave_Chart = QtWidgets.QAction(MainWindow)
        self.actionSave_Chart.setObjectName("actionSave_Chart")
        self.actionExport_Biquad = QtWidgets.QAction(MainWindow)
        self.actionExport_Biquad.setObjectName("actionExport_Biquad")
        self.actionSave_Filter = QtWidgets.QAction(MainWindow)
        self.actionSave_Filter.setEnabled(False)
        self.actionSave_Filter.setObjectName("actionSave_Filter")
        self.actionLoad_Filter = QtWidgets.QAction(MainWindow)
        self.actionLoad_Filter.setCheckable(False)
        self.actionLoad_Filter.setEnabled(True)
        self.actionLoad_Filter.setObjectName("actionLoad_Filter")
        self.action_load_preset_1 = QtWidgets.QAction(MainWindow)
        self.action_load_preset_1.setObjectName("action_load_preset_1")
        self.action_load_preset_2 = QtWidgets.QAction(MainWindow)
        self.action_load_preset_2.setObjectName("action_load_preset_2")
        self.action_load_preset_3 = QtWidgets.QAction(MainWindow)
        self.action_load_preset_3.setObjectName("action_load_preset_3")
        self.action_clear_preset_1 = QtWidgets.QAction(MainWindow)
        self.action_clear_preset_1.setObjectName("action_clear_preset_1")
        self.action_clear_preset_2 = QtWidgets.QAction(MainWindow)
        self.action_clear_preset_2.setObjectName("action_clear_preset_2")
        self.action_clear_preset_3 = QtWidgets.QAction(MainWindow)
        self.action_clear_preset_3.setObjectName("action_clear_preset_3")
        self.action_store_preset_1 = QtWidgets.QAction(MainWindow)
        self.action_store_preset_1.setObjectName("action_store_preset_1")
        self.action_store_preset_2 = QtWidgets.QAction(MainWindow)
        self.action_store_preset_2.setObjectName("action_store_preset_2")
        self.action_store_preset_3 = QtWidgets.QAction(MainWindow)
        self.action_store_preset_3.setObjectName("action_store_preset_3")
        self.actionExport_FRD = QtWidgets.QAction(MainWindow)
        self.actionExport_FRD.setObjectName("actionExport_FRD")
        self.action_Save_Project = QtWidgets.QAction(MainWindow)
        self.action_Save_Project.setObjectName("action_Save_Project")
        self.action_Load_Project = QtWidgets.QAction(MainWindow)
        self.action_Load_Project.setObjectName("action_Load_Project")
        self.actionSave_Signal = QtWidgets.QAction(MainWindow)
        self.actionSave_Signal.setObjectName("actionSave_Signal")
        self.actionLoad_Signal = QtWidgets.QAction(MainWindow)
        self.actionLoad_Signal.setObjectName("actionLoad_Signal")
        self.actionClear_Project = QtWidgets.QAction(MainWindow)
        self.actionClear_Project.setObjectName("actionClear_Project")
        self.actionAnalyse_Audio = QtWidgets.QAction(MainWindow)
        self.actionAnalyse_Audio.setObjectName("actionAnalyse_Audio")
        self.action_Batch_Extract = QtWidgets.QAction(MainWindow)
        self.action_Batch_Extract.setObjectName("action_Batch_Extract")
        self.actionSave_Report = QtWidgets.QAction(MainWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_Remux_Audio = QtWidgets.QAction(MainWindow)
        self.action_Remux_Audio.setObjectName("action_Remux_Audio")
        self.actionAdd_BEQ_Filter = QtWidgets.QAction(MainWindow)
        self.actionAdd_BEQ_Filter.setObjectName("actionAdd_BEQ_Filter")
        self.actionClear_Signals = QtWidgets.QAction(MainWindow)
        self.actionClear_Signals.setObjectName("actionClear_Signals")
        self.action1_1_Smoothing = QtWidgets.QAction(MainWindow)
        self.action1_1_Smoothing.setObjectName("action1_1_Smoothing")
        self.action1_3_Smoothing = QtWidgets.QAction(MainWindow)
        self.action1_3_Smoothing.setObjectName("action1_3_Smoothing")
        self.action1_6_Smoothing = QtWidgets.QAction(MainWindow)
        self.action1_6_Smoothing.setObjectName("action1_6_Smoothing")
        self.action1_1_2_Smoothing = QtWidgets.QAction(MainWindow)
        self.action1_1_2_Smoothing.setObjectName("action1_1_2_Smoothing")
        self.action1_2_4_Smoothing = QtWidgets.QAction(MainWindow)
        self.action1_2_4_Smoothing.setObjectName("action1_2_4_Smoothing")
        self.action1_4_8_Smoothing = QtWidgets.QAction(MainWindow)
        self.action1_4_8_Smoothing.setObjectName("action1_4_8_Smoothing")
        self.action_Remove_Smoothing = QtWidgets.QAction(MainWindow)
        self.action_Remove_Smoothing.setObjectName("action_Remove_Smoothing")
        self.actionClear_Filters = QtWidgets.QAction(MainWindow)
        self.actionClear_Filters.setObjectName("actionClear_Filters")
        self.actionMerge_Minidsp_XML = QtWidgets.QAction(MainWindow)
        self.actionMerge_Minidsp_XML.setObjectName("actionMerge_Minidsp_XML")
        self.actionUser_Guide = QtWidgets.QAction(MainWindow)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.actionRelease_Notes = QtWidgets.QAction(MainWindow)
        self.actionRelease_Notes.setObjectName("actionRelease_Notes")
        self.actionExport_BEQ_Filter = QtWidgets.QAction(MainWindow)
        self.actionExport_BEQ_Filter.setObjectName("actionExport_BEQ_Filter")
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addAction(self.actionShow_Logs)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionRelease_Notes)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addSeparator()
        self.menuLoad.addAction(self.action_load_preset_1)
        self.menuLoad.addAction(self.action_load_preset_2)
        self.menuLoad.addAction(self.action_load_preset_3)
        self.menu_Clear.addAction(self.action_clear_preset_1)
        self.menu_Clear.addAction(self.action_clear_preset_2)
        self.menu_Clear.addAction(self.action_clear_preset_3)
        self.menu_Store.addAction(self.action_store_preset_1)
        self.menu_Store.addAction(self.action_store_preset_2)
        self.menu_Store.addAction(self.action_store_preset_3)
        self.menuPresets.addAction(self.menuLoad.menuAction())
        self.menuPresets.addAction(self.menu_Store.menuAction())
        self.menuPresets.addAction(self.menu_Clear.menuAction())
        self.menuFile.addAction(self.action_Load_Project)
        self.menuFile.addAction(self.action_Save_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Signal)
        self.menuFile.addAction(self.actionSave_Signal)
        self.menuFile.addAction(self.actionClear_Signals)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Filter)
        self.menuFile.addAction(self.actionSave_Filter)
        self.menuFile.addAction(self.actionClear_Filters)
        self.menuFile.addAction(self.menuPresets.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAdd_BEQ_Filter)
        self.menuFile.addAction(self.actionExport_BEQ_Filter)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_FRD)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Chart)
        self.menuFile.addAction(self.actionSave_Report)
        self.menu_Tools.addAction(self.actionExtract_Audio)
        self.menu_Tools.addAction(self.action_Batch_Extract)
        self.menu_Tools.addAction(self.action_Remux_Audio)
        self.menu_Tools.addSeparator()
        self.menu_Tools.addAction(self.actionAnalyse_Audio)
        self.menu_Tools.addSeparator()
        self.menu_Tools.addAction(self.actionExport_Biquad)
        self.menu_Tools.addAction(self.actionMerge_Minidsp_XML)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.addFilterButton, QtCore.SIGNAL("clicked()"), MainWindow.addFilter)
        QtCore.QObject.connect(self.deleteFilterButton, QtCore.SIGNAL("clicked()"), MainWindow.deleteFilter)
        QtCore.QObject.connect(self.editFilterButton, QtCore.SIGNAL("clicked()"), MainWindow.editFilter)
        QtCore.QObject.connect(self.addSignalButton, QtCore.SIGNAL("clicked()"), MainWindow.addSignal)
        QtCore.QObject.connect(self.deleteSignalButton, QtCore.SIGNAL("clicked()"), MainWindow.deleteSignal)
        QtCore.QObject.connect(self.signalReference, QtCore.SIGNAL("currentIndexChanged(int)"), MainWindow.normaliseSignalMagnitude)
        QtCore.QObject.connect(self.limitsButton, QtCore.SIGNAL("clicked()"), MainWindow.showLimits)
        QtCore.QObject.connect(self.filterReference, QtCore.SIGNAL("currentIndexChanged(int)"), MainWindow.normaliseFilterMagnitude)
        QtCore.QObject.connect(self.showValuesButton, QtCore.SIGNAL("clicked()"), MainWindow.showValues)
        QtCore.QObject.connect(self.showLegend, QtCore.SIGNAL("clicked()"), MainWindow.changeLegendVisibility)
        QtCore.QObject.connect(self.showFilters, QtCore.SIGNAL("currentTextChanged(QString)"), MainWindow.changeFilterVisibility)
        QtCore.QObject.connect(self.preset1Button, QtCore.SIGNAL("clicked()"), MainWindow.applyPreset1)
        QtCore.QObject.connect(self.preset2Button, QtCore.SIGNAL("clicked()"), MainWindow.applyPreset2)
        QtCore.QObject.connect(self.preset3Button, QtCore.SIGNAL("clicked()"), MainWindow.applyPreset3)
        QtCore.QObject.connect(self.showSignals, QtCore.SIGNAL("currentTextChanged(QString)"), MainWindow.changeSignalVisibility)
        QtCore.QObject.connect(self.showFilteredSignals, QtCore.SIGNAL("currentTextChanged(QString)"), MainWindow.changeSignalFilterVisibility)
        QtCore.QObject.connect(self.linkSignalButton, QtCore.SIGNAL("clicked()"), MainWindow.linkSignals)
        QtCore.QObject.connect(self.equalEnergyTilt, QtCore.SIGNAL("clicked()"), MainWindow.toggleTilt)
        QtCore.QObject.connect(self.octaveSmoothing, QtCore.SIGNAL("currentTextChanged(QString)"), MainWindow.smoothSignals)
        QtCore.QObject.connect(self.smoothAllSignals, QtCore.SIGNAL("clicked()"), MainWindow.smoothSignals)
        QtCore.QObject.connect(self.clearSignalsButton, QtCore.SIGNAL("clicked()"), MainWindow.clearSignals)
        QtCore.QObject.connect(self.clearFiltersButton, QtCore.SIGNAL("clicked()"), MainWindow.clearFilters)
        QtCore.QObject.connect(self.y2MaxPlus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_max_plus_10)
        QtCore.QObject.connect(self.y2MaxMinus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_max_minus_10)
        QtCore.QObject.connect(self.y1MaxPlus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_max_plus_10)
        QtCore.QObject.connect(self.y1MaxPlus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_max_plus_5)
        QtCore.QObject.connect(self.y1AutoOnButton, QtCore.SIGNAL("clicked()"), MainWindow.y1_auto_on)
        QtCore.QObject.connect(self.y1AutoOffButton, QtCore.SIGNAL("clicked()"), MainWindow.y1_auto_off)
        QtCore.QObject.connect(self.y1MaxMinus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_max_minus_5)
        QtCore.QObject.connect(self.y1MaxMinus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_max_minus_10)
        QtCore.QObject.connect(self.y2MaxPlus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_max_plus_5)
        QtCore.QObject.connect(self.y2AutoOnButton, QtCore.SIGNAL("clicked()"), MainWindow.y2_auto_on)
        QtCore.QObject.connect(self.y2AutoOffButton, QtCore.SIGNAL("clicked()"), MainWindow.y2_auto_off)
        QtCore.QObject.connect(self.y2MaxMinus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_max_minus_5)
        QtCore.QObject.connect(self.y1MinPlus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_min_plus_10)
        QtCore.QObject.connect(self.y1MinPlus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_min_plus_5)
        QtCore.QObject.connect(self.y1MinMinus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_min_minus_5)
        QtCore.QObject.connect(self.y1MinMinus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y1_min_minus_10)
        QtCore.QObject.connect(self.y2MinPlus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_min_plus_10)
        QtCore.QObject.connect(self.y2MinPlus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_min_plus_5)
        QtCore.QObject.connect(self.y2MinMinus5Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_min_minus_5)
        QtCore.QObject.connect(self.y2MinMinus10Button, QtCore.SIGNAL("clicked()"), MainWindow.y2_min_minus_10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "BEQ Designer", None, -1))
        self.showValuesButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.filterReference.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.limitsButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.signalReference.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.referenceLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Reference:", None, -1))
        self.signalSelectorLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Signal", None, -1))
        self.sourceFileLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Source File", None, -1))
        self.loadSignalButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.waveformIsFiltered.setText(QtWidgets.QApplication.translate("MainWindow", "Filtered?", None, -1))
        self.hardClipWaveform.setText(QtWidgets.QApplication.translate("MainWindow", "Clip?", None, -1))
        self.headroomLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Headroom", None, -1))
        self.startTimeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.startTime.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "HH:mm:ss.zzz", None, -1))
        self.endTime.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "HH:mm:ss.zzz", None, -1))
        self.endTimeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "End", None, -1))
        self.yRangeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Y Range", None, -1))
        self.bmHeaderLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Bass Management", None, -1))
        self.bmlpfPositionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "LPF", None, -1))
        self.bmClippingLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Clip", None, -1))
        self.bmClipBefore.setText(QtWidgets.QApplication.translate("MainWindow", "Before", None, -1))
        self.bmClipAfter.setText(QtWidgets.QApplication.translate("MainWindow", "After", None, -1))
        self.bmHeadroomLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Headroom", None, -1))
        self.bmHeadroom.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "WCS", None, -1))
        self.bmHeadroom.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "-8", None, -1))
        self.bmHeadroom.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "-7", None, -1))
        self.bmHeadroom.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "-6", None, -1))
        self.bmHeadroom.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "-5", None, -1))
        self.compareSpectrumButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.showSpectrumButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.hideSpectrumButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.filteredSpectrumLimitsButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.zoomInButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.zoomOutButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Smoothing:", None, -1))
        self.octaveSmoothing.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.octaveSmoothing.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "1/1", None, -1))
        self.octaveSmoothing.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "1/2", None, -1))
        self.octaveSmoothing.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "1/3", None, -1))
        self.octaveSmoothing.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "1/6", None, -1))
        self.octaveSmoothing.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "1/12", None, -1))
        self.octaveSmoothing.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "1/24", None, -1))
        self.octaveSmoothing.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "Savitzky–Golay", None, -1))
        self.smoothAllSignals.setText(QtWidgets.QApplication.translate("MainWindow", "All Signals?", None, -1))
        self.signalsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Signals", None, -1))
        self.addSignalButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.addSignalButton.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+=", None, -1))
        self.linkSignalButton.setText(QtWidgets.QApplication.translate("MainWindow", "Link", None, -1))
        self.linkSignalButton.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+L", None, -1))
        self.deleteSignalButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.clearSignalsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.filtersLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Filters", None, -1))
        self.preset1Button.setText(QtWidgets.QApplication.translate("MainWindow", "P1", None, -1))
        self.preset1Button.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+1", None, -1))
        self.preset2Button.setText(QtWidgets.QApplication.translate("MainWindow", "P2", None, -1))
        self.preset2Button.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+2", None, -1))
        self.preset3Button.setText(QtWidgets.QApplication.translate("MainWindow", "P3", None, -1))
        self.preset3Button.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+3", None, -1))
        self.addFilterButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.addFilterButton.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+=", None, -1))
        self.editFilterButton.setText(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.deleteFilterButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.deleteFilterButton.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+-", None, -1))
        self.clearFiltersButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.clearFiltersButton.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+-", None, -1))
        self.showSignalsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Peak/Avg", None, -1))
        self.showFiltersLabel.setText(QtWidgets.QApplication.translate("MainWindow", "With Filters?", None, -1))
        self.showFiltersLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Filter Response?", None, -1))
        self.equalEnergyTilt.setText(QtWidgets.QApplication.translate("MainWindow", "+3dB/octave?", None, -1))
        self.showLegend.setText(QtWidgets.QApplication.translate("MainWindow", "Show Legend", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Settings", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menuPresets.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Presets", None, -1))
        self.menuLoad.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Load", None, -1))
        self.menu_Clear.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Clear", None, -1))
        self.menu_Store.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Store", None, -1))
        self.menu_Tools.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Tools", None, -1))
        self.actionShow_Logs.setText(QtWidgets.QApplication.translate("MainWindow", "Show &Logs", None, -1))
        self.actionShow_Logs.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("MainWindow", "&Preferences", None, -1))
        self.actionPreferences.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+P", None, -1))
        self.actionExtract_Audio.setText(QtWidgets.QApplication.translate("MainWindow", "&Extract Audio", None, -1))
        self.actionExtract_Audio.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.actionPresets.setText(QtWidgets.QApplication.translate("MainWindow", "Presets", None, -1))
        self.actionClear_Preset_3.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Preset 3", None, -1))
        self.actionSave_Chart.setText(QtWidgets.QApplication.translate("MainWindow", "Save &Chart", None, -1))
        self.actionSave_Chart.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, -1))
        self.actionExport_Biquad.setText(QtWidgets.QApplication.translate("MainWindow", "Export &Biquad", None, -1))
        self.actionExport_Biquad.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+B", None, -1))
        self.actionSave_Filter.setText(QtWidgets.QApplication.translate("MainWindow", "Save &Filter", None, -1))
        self.actionSave_Filter.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+S", None, -1))
        self.actionLoad_Filter.setText(QtWidgets.QApplication.translate("MainWindow", "Load Filte&r", None, -1))
        self.actionLoad_Filter.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+L", None, -1))
        self.action_load_preset_1.setText(QtWidgets.QApplication.translate("MainWindow", "&1", None, -1))
        self.action_load_preset_2.setText(QtWidgets.QApplication.translate("MainWindow", "&2", None, -1))
        self.action_load_preset_3.setText(QtWidgets.QApplication.translate("MainWindow", "&3", None, -1))
        self.action_clear_preset_1.setText(QtWidgets.QApplication.translate("MainWindow", "&1", None, -1))
        self.action_clear_preset_2.setText(QtWidgets.QApplication.translate("MainWindow", "&2", None, -1))
        self.action_clear_preset_3.setText(QtWidgets.QApplication.translate("MainWindow", "&3", None, -1))
        self.action_store_preset_1.setText(QtWidgets.QApplication.translate("MainWindow", "&1", None, -1))
        self.action_store_preset_1.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+1", None, -1))
        self.action_store_preset_2.setText(QtWidgets.QApplication.translate("MainWindow", "&2", None, -1))
        self.action_store_preset_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+2", None, -1))
        self.action_store_preset_3.setText(QtWidgets.QApplication.translate("MainWindow", "&3", None, -1))
        self.action_store_preset_3.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+3", None, -1))
        self.actionExport_FRD.setText(QtWidgets.QApplication.translate("MainWindow", "&Export FRD", None, -1))
        self.action_Save_Project.setText(QtWidgets.QApplication.translate("MainWindow", "&Save Project", None, -1))
        self.action_Save_Project.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.action_Load_Project.setText(QtWidgets.QApplication.translate("MainWindow", "&Load Project", None, -1))
        self.action_Load_Project.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionSave_Signal.setText(QtWidgets.QApplication.translate("MainWindow", "Save Si&gnal", None, -1))
        self.actionSave_Signal.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))
        self.actionLoad_Signal.setText(QtWidgets.QApplication.translate("MainWindow", "Loa&d Signal", None, -1))
        self.actionLoad_Signal.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+O", None, -1))
        self.actionClear_Project.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Project", None, -1))
        self.actionAnalyse_Audio.setText(QtWidgets.QApplication.translate("MainWindow", "&Analyse Audio", None, -1))
        self.actionAnalyse_Audio.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+A", None, -1))
        self.action_Batch_Extract.setText(QtWidgets.QApplication.translate("MainWindow", "&Batch Extract", None, -1))
        self.action_Batch_Extract.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+E", None, -1))
        self.actionSave_Report.setText(QtWidgets.QApplication.translate("MainWindow", "Save Repor&t", None, -1))
        self.actionSave_Report.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "&About", None, -1))
        self.action_Remux_Audio.setText(QtWidgets.QApplication.translate("MainWindow", "&Remux Audio", None, -1))
        self.action_Remux_Audio.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+U", None, -1))
        self.actionAdd_BEQ_Filter.setText(QtWidgets.QApplication.translate("MainWindow", "Load BE&Q Filter", None, -1))
        self.actionAdd_BEQ_Filter.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+B", None, -1))
        self.actionClear_Signals.setText(QtWidgets.QApplication.translate("MainWindow", "Clear S&ignals", None, -1))
        self.action1_1_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "1/&1 Smoothing", None, -1))
        self.action1_1_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+1", None, -1))
        self.action1_3_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "1/&3 Smoothing", None, -1))
        self.action1_3_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+2", None, -1))
        self.action1_6_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "1/&6 Smoothing", None, -1))
        self.action1_6_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+3", None, -1))
        self.action1_1_2_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "1/1&2 Smoothing", None, -1))
        self.action1_1_2_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+4", None, -1))
        self.action1_2_4_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "1/2&4 Smoothing", None, -1))
        self.action1_2_4_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+5", None, -1))
        self.action1_4_8_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "1/4&8 Smoothing", None, -1))
        self.action1_4_8_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+6", None, -1))
        self.action_Remove_Smoothing.setText(QtWidgets.QApplication.translate("MainWindow", "&Remove Smoothing", None, -1))
        self.action_Remove_Smoothing.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Alt+Shift+0", None, -1))
        self.actionClear_Filters.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Filters", None, -1))
        self.actionMerge_Minidsp_XML.setText(QtWidgets.QApplication.translate("MainWindow", "Merge Minidsp XML", None, -1))
        self.actionMerge_Minidsp_XML.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+X", None, -1))
        self.actionUser_Guide.setText(QtWidgets.QApplication.translate("MainWindow", "User Guide", None, -1))
        self.actionUser_Guide.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F1", None, -1))
        self.actionRelease_Notes.setText(QtWidgets.QApplication.translate("MainWindow", "Release Notes", None, -1))
        self.actionExport_BEQ_Filter.setText(QtWidgets.QApplication.translate("MainWindow", "Export BEQ Filter", None, -1))
        self.actionExport_BEQ_Filter.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+E", None, -1))

from mpl import MplWidget
from app import PlotWidgetWithDateAxis
