# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browse_catalogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogueViewerDialog(object):
    def setupUi(self, catalogueViewerDialog):
        catalogueViewerDialog.setObjectName("catalogueViewerDialog")
        catalogueViewerDialog.resize(878, 568)
        self.verticalLayout = QtWidgets.QVBoxLayout(catalogueViewerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameFilter = QtWidgets.QLineEdit(catalogueViewerDialog)
        self.nameFilter.setObjectName("nameFilter")
        self.verticalLayout.addWidget(self.nameFilter)
        self.tableView = QtWidgets.QTableView(catalogueViewerDialog)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.buttonBox = QtWidgets.QDialogButtonBox(catalogueViewerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(catalogueViewerDialog)
        self.buttonBox.accepted.connect(catalogueViewerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(catalogueViewerDialog.reject) # type: ignore
        self.nameFilter.textChanged['QString'].connect(catalogueViewerDialog.apply_filter) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(catalogueViewerDialog)

    def retranslateUi(self, catalogueViewerDialog):
        _translate = QtCore.QCoreApplication.translate
        catalogueViewerDialog.setWindowTitle(_translate("catalogueViewerDialog", "Browse Catalogue"))
