# Form implementation generated from reading ui file 'channel_matrix.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_channelMatrixDialog(object):
    def setupUi(self, channelMatrixDialog):
        channelMatrixDialog.setObjectName("channelMatrixDialog")
        channelMatrixDialog.resize(838, 448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(channelMatrixDialog.sizePolicy().hasHeightForWidth())
        channelMatrixDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(channelMatrixDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.errorMessageIcon = QtWidgets.QLabel(parent=channelMatrixDialog)
        self.errorMessageIcon.setText("")
        self.errorMessageIcon.setObjectName("errorMessageIcon")
        self.gridLayout.addWidget(self.errorMessageIcon, 1, 0, 1, 1)
        self.errorMessage = QtWidgets.QLabel(parent=channelMatrixDialog)
        self.errorMessage.setText("")
        self.errorMessage.setObjectName("errorMessage")
        self.gridLayout.addWidget(self.errorMessage, 1, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=channelMatrixDialog)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Reset|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 4, 1, 1)
        self.matrix = QtWidgets.QTableView(parent=channelMatrixDialog)
        self.matrix.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.matrix.setObjectName("matrix")
        self.gridLayout.addWidget(self.matrix, 0, 0, 1, 6)

        self.retranslateUi(channelMatrixDialog)
        self.buttonBox.accepted.connect(channelMatrixDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(channelMatrixDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(channelMatrixDialog)

    def retranslateUi(self, channelMatrixDialog):
        _translate = QtCore.QCoreApplication.translate
        channelMatrixDialog.setWindowTitle(_translate("channelMatrixDialog", "Channel Matrix"))
