# Form implementation generated from reading ui file 'designers.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_designersDialog(object):
    def setupUi(self, designersDialog):
        designersDialog.setObjectName("designersDialog")
        designersDialog.resize(640, 360)
        self.mainLayout = QtWidgets.QVBoxLayout(designersDialog)
        self.mainLayout.setObjectName("mainLayout")
        self.helpLabel = QtWidgets.QLabel(parent=designersDialog)
        self.helpLabel.setWordWrap(True)
        self.helpLabel.setObjectName("helpLabel")
        self.mainLayout.addWidget(self.helpLabel)
        self.designersTable = QtWidgets.QTableWidget(parent=designersDialog)
        self.designersTable.setColumnCount(3)
        self.designersTable.setObjectName("designersTable")
        self.designersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.designersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.designersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.designersTable.setHorizontalHeaderItem(2, item)
        self.mainLayout.addWidget(self.designersTable)
        self.rowButtonsLayout = QtWidgets.QHBoxLayout()
        self.rowButtonsLayout.setObjectName("rowButtonsLayout")
        self.addButton = QtWidgets.QPushButton(parent=designersDialog)
        self.addButton.setObjectName("addButton")
        self.rowButtonsLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(parent=designersDialog)
        self.removeButton.setObjectName("removeButton")
        self.rowButtonsLayout.addWidget(self.removeButton)
        self.mainLayout.addLayout(self.rowButtonsLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=designersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.mainLayout.addWidget(self.buttonBox)

        self.retranslateUi(designersDialog)
        self.buttonBox.rejected.connect(designersDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(designersDialog)

    def retranslateUi(self, designersDialog):
        _translate = QtCore.QCoreApplication.translate
        designersDialog.setWindowTitle(_translate("designersDialog", "Designers"))
        self.helpLabel.setText(_translate("designersDialog", "HTTP designer endpoints, available to Batch Design by name. Headers (optional) is a JSON object, e.g. {\"Authorization\": \"Bearer ...\"}."))
        item = self.designersTable.horizontalHeaderItem(0)
        item.setText(_translate("designersDialog", "Name"))
        item = self.designersTable.horizontalHeaderItem(1)
        item.setText(_translate("designersDialog", "URL"))
        item = self.designersTable.horizontalHeaderItem(2)
        item.setText(_translate("designersDialog", "Headers (JSON)"))
        self.addButton.setText(_translate("designersDialog", "Add"))
        self.removeButton.setText(_translate("designersDialog", "Remove"))
