# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_exportSignalDialog(object):
    def setupUi(self, exportSignalDialog):
        exportSignalDialog.setObjectName("exportSignalDialog")
        exportSignalDialog.resize(408, 96)
        self.gridLayout = QtWidgets.QGridLayout(exportSignalDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=exportSignalDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.signal = QtWidgets.QComboBox(parent=exportSignalDialog)
        self.signal.setObjectName("signal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.signal)
        self.signalLabel = QtWidgets.QLabel(parent=exportSignalDialog)
        self.signalLabel.setObjectName("signalLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.signalLabel)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(exportSignalDialog)
        self.buttonBox.accepted.connect(exportSignalDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(exportSignalDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(exportSignalDialog)

    def retranslateUi(self, exportSignalDialog):
        _translate = QtCore.QCoreApplication.translate
        exportSignalDialog.setWindowTitle(_translate("exportSignalDialog", "Export Signal"))
        self.signalLabel.setText(_translate("exportSignalDialog", "Signal"))
