# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extract.ui',
# licensing of 'extract.ui' applies.
#
# Created: Sun Jun 30 22:06:40 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_extractAudioDialog(object):
    def setupUi(self, extractAudioDialog):
        extractAudioDialog.setObjectName("extractAudioDialog")
        extractAudioDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        extractAudioDialog.resize(880, 1027)
        extractAudioDialog.setSizeGripEnabled(True)
        extractAudioDialog.setModal(False)
        self.boxLayout = QtWidgets.QVBoxLayout(extractAudioDialog)
        self.boxLayout.setObjectName("boxLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ffmpegOutput = QtWidgets.QPlainTextEdit(extractAudioDialog)
        self.ffmpegOutput.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.ffmpegOutput.setFont(font)
        self.ffmpegOutput.setReadOnly(True)
        self.ffmpegOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.ffmpegOutput.setObjectName("ffmpegOutput")
        self.gridLayout.addWidget(self.ffmpegOutput, 13, 1, 1, 1)
        self.streamsLabel = QtWidgets.QLabel(extractAudioDialog)
        self.streamsLabel.setObjectName("streamsLabel")
        self.gridLayout.addWidget(self.streamsLabel, 1, 0, 1, 1)
        self.targetDirPicker = QtWidgets.QToolButton(extractAudioDialog)
        self.targetDirPicker.setObjectName("targetDirPicker")
        self.gridLayout.addWidget(self.targetDirPicker, 9, 2, 1, 1)
        self.targetDir = QtWidgets.QLineEdit(extractAudioDialog)
        self.targetDir.setEnabled(False)
        self.targetDir.setObjectName("targetDir")
        self.gridLayout.addWidget(self.targetDir, 9, 1, 1, 1)
        self.showProbeButton = QtWidgets.QToolButton(extractAudioDialog)
        self.showProbeButton.setObjectName("showProbeButton")
        self.gridLayout.addWidget(self.showProbeButton, 1, 2, 2, 1)
        self.signalName = QtWidgets.QLineEdit(extractAudioDialog)
        self.signalName.setEnabled(True)
        self.signalName.setObjectName("signalName")
        self.gridLayout.addWidget(self.signalName, 14, 1, 1, 1)
        self.inputFilePicker = QtWidgets.QToolButton(extractAudioDialog)
        self.inputFilePicker.setObjectName("inputFilePicker")
        self.gridLayout.addWidget(self.inputFilePicker, 0, 2, 1, 1)
        self.showRemuxCommand = QtWidgets.QToolButton(extractAudioDialog)
        self.showRemuxCommand.setObjectName("showRemuxCommand")
        self.gridLayout.addWidget(self.showRemuxCommand, 11, 2, 1, 1)
        self.targetDirectoryLabel = QtWidgets.QLabel(extractAudioDialog)
        self.targetDirectoryLabel.setObjectName("targetDirectoryLabel")
        self.gridLayout.addWidget(self.targetDirectoryLabel, 9, 0, 1, 1)
        self.filterMapping = QtWidgets.QListWidget(extractAudioDialog)
        self.filterMapping.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filterMapping.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.filterMapping.setObjectName("filterMapping")
        self.gridLayout.addWidget(self.filterMapping, 8, 1, 1, 1)
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.inputFile = QtWidgets.QLineEdit(extractAudioDialog)
        self.inputFile.setEnabled(False)
        self.inputFile.setObjectName("inputFile")
        self.inputLayout.addWidget(self.inputFile)
        self.inputDrop = DropArea(extractAudioDialog)
        self.inputDrop.setMinimumSize(QtCore.QSize(100, 0))
        self.inputDrop.setAutoFillBackground(False)
        self.inputDrop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputDrop.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.inputDrop.setText("")
        self.inputDrop.setScaledContents(False)
        self.inputDrop.setAlignment(QtCore.Qt.AlignCenter)
        self.inputDrop.setObjectName("inputDrop")
        self.inputLayout.addWidget(self.inputDrop)
        self.inputLayout.setStretch(0, 1)
        self.gridLayout.addLayout(self.inputLayout, 0, 1, 1, 1)
        self.ffmpegCommandLine = QtWidgets.QPlainTextEdit(extractAudioDialog)
        self.ffmpegCommandLine.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.ffmpegCommandLine.setFont(font)
        self.ffmpegCommandLine.setReadOnly(True)
        self.ffmpegCommandLine.setObjectName("ffmpegCommandLine")
        self.gridLayout.addWidget(self.ffmpegCommandLine, 11, 1, 1, 1)
        self.ffmpegCommandLabel = QtWidgets.QLabel(extractAudioDialog)
        self.ffmpegCommandLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ffmpegCommandLabel.setObjectName("ffmpegCommandLabel")
        self.gridLayout.addWidget(self.ffmpegCommandLabel, 11, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monoMix = QtWidgets.QCheckBox(extractAudioDialog)
        self.monoMix.setEnabled(True)
        self.monoMix.setChecked(True)
        self.monoMix.setObjectName("monoMix")
        self.horizontalLayout.addWidget(self.monoMix)
        self.decimateAudio = QtWidgets.QCheckBox(extractAudioDialog)
        self.decimateAudio.setChecked(True)
        self.decimateAudio.setObjectName("decimateAudio")
        self.horizontalLayout.addWidget(self.decimateAudio)
        self.includeSubtitles = QtWidgets.QCheckBox(extractAudioDialog)
        self.includeSubtitles.setToolTip("")
        self.includeSubtitles.setObjectName("includeSubtitles")
        self.horizontalLayout.addWidget(self.includeSubtitles)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.audioStreams = QtWidgets.QComboBox(extractAudioDialog)
        self.audioStreams.setObjectName("audioStreams")
        self.horizontalLayout_3.addWidget(self.audioStreams)
        self.videoStreams = QtWidgets.QComboBox(extractAudioDialog)
        self.videoStreams.setObjectName("videoStreams")
        self.horizontalLayout_3.addWidget(self.videoStreams)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.channelsLabel = QtWidgets.QLabel(extractAudioDialog)
        self.channelsLabel.setObjectName("channelsLabel")
        self.gridLayout.addWidget(self.channelsLabel, 3, 0, 1, 1)
        self.signalNameLabel = QtWidgets.QLabel(extractAudioDialog)
        self.signalNameLabel.setObjectName("signalNameLabel")
        self.gridLayout.addWidget(self.signalNameLabel, 14, 0, 1, 1)
        self.rangeLayout = QtWidgets.QHBoxLayout()
        self.rangeLayout.setObjectName("rangeLayout")
        self.limitRange = QtWidgets.QToolButton(extractAudioDialog)
        self.limitRange.setCheckable(True)
        self.limitRange.setObjectName("limitRange")
        self.rangeLayout.addWidget(self.limitRange)
        self.rangeFrom = QtWidgets.QTimeEdit(extractAudioDialog)
        self.rangeFrom.setObjectName("rangeFrom")
        self.rangeLayout.addWidget(self.rangeFrom)
        self.rangeSeparatorLabel = QtWidgets.QLabel(extractAudioDialog)
        self.rangeSeparatorLabel.setObjectName("rangeSeparatorLabel")
        self.rangeLayout.addWidget(self.rangeSeparatorLabel)
        self.rangeTo = QtWidgets.QTimeEdit(extractAudioDialog)
        self.rangeTo.setObjectName("rangeTo")
        self.rangeLayout.addWidget(self.rangeTo)
        self.rangeLayout.setStretch(1, 1)
        self.rangeLayout.setStretch(3, 1)
        self.gridLayout.addLayout(self.rangeLayout, 5, 1, 1, 1)
        self.ffmpegProgress = QtWidgets.QProgressBar(extractAudioDialog)
        self.ffmpegProgress.setProperty("value", 0)
        self.ffmpegProgress.setObjectName("ffmpegProgress")
        self.gridLayout.addWidget(self.ffmpegProgress, 12, 1, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(extractAudioDialog)
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout.addWidget(self.outputFilename, 10, 1, 1, 1)
        self.outputFilenameLabel = QtWidgets.QLabel(extractAudioDialog)
        self.outputFilenameLabel.setObjectName("outputFilenameLabel")
        self.gridLayout.addWidget(self.outputFilenameLabel, 10, 0, 1, 1)
        self.ffmpegProgressLabel = QtWidgets.QLabel(extractAudioDialog)
        self.ffmpegProgressLabel.setObjectName("ffmpegProgressLabel")
        self.gridLayout.addWidget(self.ffmpegProgressLabel, 12, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lfeChannelIndex = QtWidgets.QSpinBox(extractAudioDialog)
        self.lfeChannelIndex.setMinimum(0)
        self.lfeChannelIndex.setObjectName("lfeChannelIndex")
        self.horizontalLayout_2.addWidget(self.lfeChannelIndex)
        self.channelCount = QtWidgets.QSpinBox(extractAudioDialog)
        self.channelCount.setMinimum(1)
        self.channelCount.setObjectName("channelCount")
        self.horizontalLayout_2.addWidget(self.channelCount)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.audioFormatLabel = QtWidgets.QLabel(extractAudioDialog)
        self.audioFormatLabel.setObjectName("audioFormatLabel")
        self.horizontalLayout_2.addWidget(self.audioFormatLabel)
        self.audioFormat = QtWidgets.QComboBox(extractAudioDialog)
        self.audioFormat.setObjectName("audioFormat")
        self.horizontalLayout_2.addWidget(self.audioFormat)
        self.eacBitRate = QtWidgets.QSpinBox(extractAudioDialog)
        self.eacBitRate.setMinimum(32)
        self.eacBitRate.setMaximum(6000)
        self.eacBitRate.setProperty("value", 1500)
        self.eacBitRate.setObjectName("eacBitRate")
        self.horizontalLayout_2.addWidget(self.eacBitRate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.inputFileLabel = QtWidgets.QLabel(extractAudioDialog)
        self.inputFileLabel.setObjectName("inputFileLabel")
        self.gridLayout.addWidget(self.inputFileLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(extractAudioDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.ffmpegOutputLabel = QtWidgets.QLabel(extractAudioDialog)
        self.ffmpegOutputLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ffmpegOutputLabel.setObjectName("ffmpegOutputLabel")
        self.gridLayout.addWidget(self.ffmpegOutputLabel, 13, 0, 1, 1)
        self.filterMappingLabel = QtWidgets.QLabel(extractAudioDialog)
        self.filterMappingLabel.setObjectName("filterMappingLabel")
        self.gridLayout.addWidget(self.filterMappingLabel, 8, 0, 1, 1)
        self.remuxOptionsLayout = QtWidgets.QHBoxLayout()
        self.remuxOptionsLayout.setObjectName("remuxOptionsLayout")
        self.includeOriginalAudio = QtWidgets.QCheckBox(extractAudioDialog)
        self.includeOriginalAudio.setObjectName("includeOriginalAudio")
        self.remuxOptionsLayout.addWidget(self.includeOriginalAudio)
        self.gainOffsetLabel = QtWidgets.QLabel(extractAudioDialog)
        self.gainOffsetLabel.setObjectName("gainOffsetLabel")
        self.remuxOptionsLayout.addWidget(self.gainOffsetLabel)
        self.gainOffset = QtWidgets.QDoubleSpinBox(extractAudioDialog)
        self.gainOffset.setMinimum(-100.0)
        self.gainOffset.setMaximum(100.0)
        self.gainOffset.setSingleStep(0.01)
        self.gainOffset.setObjectName("gainOffset")
        self.remuxOptionsLayout.addWidget(self.gainOffset)
        self.adjustRemuxedAudio = QtWidgets.QCheckBox(extractAudioDialog)
        self.adjustRemuxedAudio.setChecked(True)
        self.adjustRemuxedAudio.setObjectName("adjustRemuxedAudio")
        self.remuxOptionsLayout.addWidget(self.adjustRemuxedAudio)
        self.remuxedAudioOffset = QtWidgets.QDoubleSpinBox(extractAudioDialog)
        self.remuxedAudioOffset.setMinimum(-120.0)
        self.remuxedAudioOffset.setMaximum(12.0)
        self.remuxedAudioOffset.setSingleStep(0.01)
        self.remuxedAudioOffset.setObjectName("remuxedAudioOffset")
        self.remuxOptionsLayout.addWidget(self.remuxedAudioOffset)
        self.remuxOptionsLayout.setStretch(0, 1)
        self.remuxOptionsLayout.setStretch(3, 1)
        self.gridLayout.addLayout(self.remuxOptionsLayout, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(extractAudioDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 2, 1)
        self.calculateGainAdjustment = QtWidgets.QToolButton(extractAudioDialog)
        self.calculateGainAdjustment.setObjectName("calculateGainAdjustment")
        self.gridLayout.addWidget(self.calculateGainAdjustment, 7, 2, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.boxLayout.addLayout(self.gridLayout)
        self.buttonLayout = QtWidgets.QGridLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(extractAudioDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonLayout.addWidget(self.buttonBox, 0, 0, 1, 1)
        self.boxLayout.addLayout(self.buttonLayout)

        self.retranslateUi(extractAudioDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), extractAudioDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), extractAudioDialog.reject)
        QtCore.QObject.connect(self.inputFilePicker, QtCore.SIGNAL("clicked()"), extractAudioDialog.selectFile)
        QtCore.QObject.connect(self.showProbeButton, QtCore.SIGNAL("clicked()"), extractAudioDialog.showProbeInDetail)
        QtCore.QObject.connect(self.targetDirPicker, QtCore.SIGNAL("clicked()"), extractAudioDialog.setTargetDirectory)
        QtCore.QObject.connect(self.outputFilename, QtCore.SIGNAL("editingFinished()"), extractAudioDialog.updateOutputFilename)
        QtCore.QObject.connect(self.audioStreams, QtCore.SIGNAL("currentIndexChanged(int)"), extractAudioDialog.updateFfmpegSpec)
        QtCore.QObject.connect(self.outputFilename, QtCore.SIGNAL("editingFinished()"), extractAudioDialog.updateOutputFilename)
        QtCore.QObject.connect(self.monoMix, QtCore.SIGNAL("clicked()"), extractAudioDialog.toggleMonoMix)
        QtCore.QObject.connect(self.lfeChannelIndex, QtCore.SIGNAL("valueChanged(int)"), extractAudioDialog.overrideFfmpegSpec)
        QtCore.QObject.connect(self.channelCount, QtCore.SIGNAL("valueChanged(int)"), extractAudioDialog.overrideFfmpegSpec)
        QtCore.QObject.connect(self.decimateAudio, QtCore.SIGNAL("clicked()"), extractAudioDialog.toggle_decimate_audio)
        QtCore.QObject.connect(self.includeOriginalAudio, QtCore.SIGNAL("clicked()"), extractAudioDialog.update_original_audio)
        QtCore.QObject.connect(self.rangeTo, QtCore.SIGNAL("timeChanged(QTime)"), extractAudioDialog.update_end_time)
        QtCore.QObject.connect(self.rangeFrom, QtCore.SIGNAL("timeChanged(QTime)"), extractAudioDialog.update_start_time)
        QtCore.QObject.connect(self.limitRange, QtCore.SIGNAL("clicked()"), extractAudioDialog.toggle_range)
        QtCore.QObject.connect(self.showRemuxCommand, QtCore.SIGNAL("clicked()"), extractAudioDialog.show_remux_cmd)
        QtCore.QObject.connect(self.includeSubtitles, QtCore.SIGNAL("clicked()"), extractAudioDialog.toggle_include_subtitles)
        QtCore.QObject.connect(self.gainOffset, QtCore.SIGNAL("valueChanged(double)"), extractAudioDialog.update_original_audio)
        QtCore.QObject.connect(self.videoStreams, QtCore.SIGNAL("currentIndexChanged(int)"), extractAudioDialog.onVideoStreamChange)
        QtCore.QObject.connect(self.audioFormat, QtCore.SIGNAL("currentTextChanged(QString)"), extractAudioDialog.change_audio_format)
        QtCore.QObject.connect(self.eacBitRate, QtCore.SIGNAL("valueChanged(int)"), extractAudioDialog.change_audio_bitrate)
        QtCore.QObject.connect(self.calculateGainAdjustment, QtCore.SIGNAL("clicked()"), extractAudioDialog.calculate_gain_adjustment)
        QtCore.QObject.connect(self.remuxedAudioOffset, QtCore.SIGNAL("valueChanged(double)"), extractAudioDialog.override_filtered_gain_adjustment)
        QtCore.QMetaObject.connectSlotsByName(extractAudioDialog)

    def retranslateUi(self, extractAudioDialog):
        extractAudioDialog.setWindowTitle(QtWidgets.QApplication.translate("extractAudioDialog", "Extract Audio", None, -1))
        self.streamsLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "A/V Streams", None, -1))
        self.targetDirPicker.setText(QtWidgets.QApplication.translate("extractAudioDialog", "...", None, -1))
        self.showProbeButton.setText(QtWidgets.QApplication.translate("extractAudioDialog", "...", None, -1))
        self.inputFilePicker.setText(QtWidgets.QApplication.translate("extractAudioDialog", "...", None, -1))
        self.showRemuxCommand.setText(QtWidgets.QApplication.translate("extractAudioDialog", "...", None, -1))
        self.targetDirectoryLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Target Directory", None, -1))
        self.ffmpegCommandLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "ffmpeg command ", None, -1))
        self.monoMix.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Mix to Mono?", None, -1))
        self.decimateAudio.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Decimate Audio?", None, -1))
        self.includeSubtitles.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Add Subtitles?", None, -1))
        self.channelsLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "LFE Channel/Total", None, -1))
        self.signalNameLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Signal Name", None, -1))
        self.limitRange.setText(QtWidgets.QApplication.translate("extractAudioDialog", "...", None, -1))
        self.rangeFrom.setDisplayFormat(QtWidgets.QApplication.translate("extractAudioDialog", "HH:mm:ss.zzz", None, -1))
        self.rangeSeparatorLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "to", None, -1))
        self.rangeTo.setDisplayFormat(QtWidgets.QApplication.translate("extractAudioDialog", "HH:mm:ss.zzz", None, -1))
        self.outputFilenameLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Output Filename", None, -1))
        self.ffmpegProgressLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Progress", None, -1))
        self.lfeChannelIndex.setToolTip(QtWidgets.QApplication.translate("extractAudioDialog", "0 = No LFE", None, -1))
        self.audioFormatLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Format", None, -1))
        self.eacBitRate.setSuffix(QtWidgets.QApplication.translate("extractAudioDialog", " kbps", None, -1))
        self.inputFileLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "File", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Range", None, -1))
        self.ffmpegOutputLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "ffmpeg output", None, -1))
        self.filterMappingLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Signal Mapping", None, -1))
        self.includeOriginalAudio.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Add Original Audio?", None, -1))
        self.gainOffsetLabel.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Offset:", None, -1))
        self.gainOffset.setSuffix(QtWidgets.QApplication.translate("extractAudioDialog", " dB", None, -1))
        self.adjustRemuxedAudio.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Adjust Remuxed Audio?", None, -1))
        self.remuxedAudioOffset.setSuffix(QtWidgets.QApplication.translate("extractAudioDialog", " dB", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("extractAudioDialog", "Options", None, -1))
        self.calculateGainAdjustment.setText(QtWidgets.QApplication.translate("extractAudioDialog", "...", None, -1))

from ui.drop import DropArea
