# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extract.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_extractAudioDialog(object):
    def setupUi(self, extractAudioDialog):
        extractAudioDialog.setObjectName("extractAudioDialog")
        extractAudioDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        extractAudioDialog.resize(880, 1027)
        extractAudioDialog.setSizeGripEnabled(True)
        extractAudioDialog.setModal(False)
        self.boxLayout = QtWidgets.QVBoxLayout(extractAudioDialog)
        self.boxLayout.setObjectName("boxLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inputFile = QtWidgets.QLineEdit(extractAudioDialog)
        self.inputFile.setEnabled(False)
        self.inputFile.setObjectName("inputFile")
        self.gridLayout.addWidget(self.inputFile, 0, 1, 1, 1)
        self.lfeChannelIndex = QtWidgets.QSpinBox(extractAudioDialog)
        self.lfeChannelIndex.setMinimum(0)
        self.lfeChannelIndex.setObjectName("lfeChannelIndex")
        self.gridLayout.addWidget(self.lfeChannelIndex, 4, 1, 1, 1)
        self.channelCountLabel = QtWidgets.QLabel(extractAudioDialog)
        self.channelCountLabel.setObjectName("channelCountLabel")
        self.gridLayout.addWidget(self.channelCountLabel, 3, 0, 1, 1)
        self.streamsLabel = QtWidgets.QLabel(extractAudioDialog)
        self.streamsLabel.setObjectName("streamsLabel")
        self.gridLayout.addWidget(self.streamsLabel, 2, 0, 1, 1)
        self.signalName = QtWidgets.QLineEdit(extractAudioDialog)
        self.signalName.setEnabled(True)
        self.signalName.setObjectName("signalName")
        self.gridLayout.addWidget(self.signalName, 13, 1, 1, 1)
        self.ffmpegOutput = QtWidgets.QPlainTextEdit(extractAudioDialog)
        self.ffmpegOutput.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.ffmpegOutput.setFont(font)
        self.ffmpegOutput.setReadOnly(True)
        self.ffmpegOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.ffmpegOutput.setObjectName("ffmpegOutput")
        self.gridLayout.addWidget(self.ffmpegOutput, 12, 1, 1, 1)
        self.targetDirectoryLabel = QtWidgets.QLabel(extractAudioDialog)
        self.targetDirectoryLabel.setObjectName("targetDirectoryLabel")
        self.gridLayout.addWidget(self.targetDirectoryLabel, 8, 0, 1, 1)
        self.targetDirPicker = QtWidgets.QToolButton(extractAudioDialog)
        self.targetDirPicker.setObjectName("targetDirPicker")
        self.gridLayout.addWidget(self.targetDirPicker, 8, 2, 1, 1)
        self.audioStreams = QtWidgets.QComboBox(extractAudioDialog)
        self.audioStreams.setObjectName("audioStreams")
        self.gridLayout.addWidget(self.audioStreams, 2, 1, 1, 1)
        self.targetDir = QtWidgets.QLineEdit(extractAudioDialog)
        self.targetDir.setEnabled(False)
        self.targetDir.setObjectName("targetDir")
        self.gridLayout.addWidget(self.targetDir, 8, 1, 1, 1)
        self.outputFilenameLabel = QtWidgets.QLabel(extractAudioDialog)
        self.outputFilenameLabel.setObjectName("outputFilenameLabel")
        self.gridLayout.addWidget(self.outputFilenameLabel, 9, 0, 1, 1)
        self.ffmpegCommandLine = QtWidgets.QPlainTextEdit(extractAudioDialog)
        self.ffmpegCommandLine.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.ffmpegCommandLine.setFont(font)
        self.ffmpegCommandLine.setReadOnly(True)
        self.ffmpegCommandLine.setObjectName("ffmpegCommandLine")
        self.gridLayout.addWidget(self.ffmpegCommandLine, 10, 1, 1, 1)
        self.signalNameLabel = QtWidgets.QLabel(extractAudioDialog)
        self.signalNameLabel.setObjectName("signalNameLabel")
        self.gridLayout.addWidget(self.signalNameLabel, 13, 0, 1, 1)
        self.ffmpegCommandLabel = QtWidgets.QLabel(extractAudioDialog)
        self.ffmpegCommandLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ffmpegCommandLabel.setObjectName("ffmpegCommandLabel")
        self.gridLayout.addWidget(self.ffmpegCommandLabel, 10, 0, 1, 1)
        self.ffmpegProgressLabel = QtWidgets.QLabel(extractAudioDialog)
        self.ffmpegProgressLabel.setObjectName("ffmpegProgressLabel")
        self.gridLayout.addWidget(self.ffmpegProgressLabel, 11, 0, 1, 1)
        self.ffmpegProgress = QtWidgets.QProgressBar(extractAudioDialog)
        self.ffmpegProgress.setProperty("value", 0)
        self.ffmpegProgress.setObjectName("ffmpegProgress")
        self.gridLayout.addWidget(self.ffmpegProgress, 11, 1, 1, 1)
        self.filterMappingLabel = QtWidgets.QLabel(extractAudioDialog)
        self.filterMappingLabel.setObjectName("filterMappingLabel")
        self.gridLayout.addWidget(self.filterMappingLabel, 7, 0, 1, 1)
        self.ffmpegOutputLabel = QtWidgets.QLabel(extractAudioDialog)
        self.ffmpegOutputLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ffmpegOutputLabel.setObjectName("ffmpegOutputLabel")
        self.gridLayout.addWidget(self.ffmpegOutputLabel, 12, 0, 1, 1)
        self.filterMapping = QtWidgets.QListWidget(extractAudioDialog)
        self.filterMapping.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filterMapping.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.filterMapping.setObjectName("filterMapping")
        self.gridLayout.addWidget(self.filterMapping, 7, 1, 1, 1)
        self.showProbeButton = QtWidgets.QToolButton(extractAudioDialog)
        self.showProbeButton.setObjectName("showProbeButton")
        self.gridLayout.addWidget(self.showProbeButton, 1, 2, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monoMix = QtWidgets.QCheckBox(extractAudioDialog)
        self.monoMix.setEnabled(True)
        self.monoMix.setChecked(True)
        self.monoMix.setObjectName("monoMix")
        self.horizontalLayout.addWidget(self.monoMix)
        self.decimateAudio = QtWidgets.QCheckBox(extractAudioDialog)
        self.decimateAudio.setChecked(True)
        self.decimateAudio.setObjectName("decimateAudio")
        self.horizontalLayout.addWidget(self.decimateAudio)
        self.includeOriginalAudio = QtWidgets.QCheckBox(extractAudioDialog)
        self.includeOriginalAudio.setObjectName("includeOriginalAudio")
        self.horizontalLayout.addWidget(self.includeOriginalAudio)
        self.compressAudio = QtWidgets.QCheckBox(extractAudioDialog)
        self.compressAudio.setObjectName("compressAudio")
        self.horizontalLayout.addWidget(self.compressAudio)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.videoStreamsLabel = QtWidgets.QLabel(extractAudioDialog)
        self.videoStreamsLabel.setObjectName("videoStreamsLabel")
        self.gridLayout.addWidget(self.videoStreamsLabel, 1, 0, 1, 1)
        self.videoStreams = QtWidgets.QComboBox(extractAudioDialog)
        self.videoStreams.setObjectName("videoStreams")
        self.gridLayout.addWidget(self.videoStreams, 1, 1, 1, 1)
        self.inputFilePicker = QtWidgets.QToolButton(extractAudioDialog)
        self.inputFilePicker.setObjectName("inputFilePicker")
        self.gridLayout.addWidget(self.inputFilePicker, 0, 2, 1, 1)
        self.inputFileLabel = QtWidgets.QLabel(extractAudioDialog)
        self.inputFileLabel.setObjectName("inputFileLabel")
        self.gridLayout.addWidget(self.inputFileLabel, 0, 0, 1, 1)
        self.channelCount = QtWidgets.QSpinBox(extractAudioDialog)
        self.channelCount.setMinimum(1)
        self.channelCount.setObjectName("channelCount")
        self.gridLayout.addWidget(self.channelCount, 3, 1, 1, 1)
        self.lfeChannelIndexLabel = QtWidgets.QLabel(extractAudioDialog)
        self.lfeChannelIndexLabel.setObjectName("lfeChannelIndexLabel")
        self.gridLayout.addWidget(self.lfeChannelIndexLabel, 4, 0, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(extractAudioDialog)
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout.addWidget(self.outputFilename, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(extractAudioDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.rangeLayout = QtWidgets.QHBoxLayout()
        self.rangeLayout.setObjectName("rangeLayout")
        self.limitRange = QtWidgets.QToolButton(extractAudioDialog)
        self.limitRange.setCheckable(True)
        self.limitRange.setObjectName("limitRange")
        self.rangeLayout.addWidget(self.limitRange)
        self.rangeFrom = QtWidgets.QTimeEdit(extractAudioDialog)
        self.rangeFrom.setObjectName("rangeFrom")
        self.rangeLayout.addWidget(self.rangeFrom)
        self.rangeSeparatorLabel = QtWidgets.QLabel(extractAudioDialog)
        self.rangeSeparatorLabel.setObjectName("rangeSeparatorLabel")
        self.rangeLayout.addWidget(self.rangeSeparatorLabel)
        self.rangeTo = QtWidgets.QTimeEdit(extractAudioDialog)
        self.rangeTo.setObjectName("rangeTo")
        self.rangeLayout.addWidget(self.rangeTo)
        self.rangeLayout.setStretch(1, 1)
        self.rangeLayout.setStretch(3, 1)
        self.gridLayout.addLayout(self.rangeLayout, 5, 1, 1, 1)
        self.showRemuxCommand = QtWidgets.QToolButton(extractAudioDialog)
        self.showRemuxCommand.setObjectName("showRemuxCommand")
        self.gridLayout.addWidget(self.showRemuxCommand, 10, 2, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout.setRowStretch(0, 1)
        self.boxLayout.addLayout(self.gridLayout)
        self.buttonLayout = QtWidgets.QGridLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(extractAudioDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonLayout.addWidget(self.buttonBox, 0, 0, 1, 1)
        self.boxLayout.addLayout(self.buttonLayout)

        self.retranslateUi(extractAudioDialog)
        self.buttonBox.accepted.connect(extractAudioDialog.accept)
        self.buttonBox.rejected.connect(extractAudioDialog.reject)
        self.inputFilePicker.clicked.connect(extractAudioDialog.selectFile)
        self.showProbeButton.clicked.connect(extractAudioDialog.showProbeInDetail)
        self.targetDirPicker.clicked.connect(extractAudioDialog.setTargetDirectory)
        self.outputFilename.editingFinished.connect(extractAudioDialog.updateOutputFilename)
        self.audioStreams.currentIndexChanged['int'].connect(extractAudioDialog.updateFfmpegSpec)
        self.outputFilename.editingFinished.connect(extractAudioDialog.updateOutputFilename)
        self.monoMix.clicked.connect(extractAudioDialog.toggleMonoMix)
        self.lfeChannelIndex.valueChanged['int'].connect(extractAudioDialog.overrideFfmpegSpec)
        self.channelCount.valueChanged['int'].connect(extractAudioDialog.overrideFfmpegSpec)
        self.videoStreams.currentIndexChanged['int'].connect(extractAudioDialog.updateFfmpegSpec)
        self.decimateAudio.clicked.connect(extractAudioDialog.toggle_decimate_audio)
        self.includeOriginalAudio.clicked.connect(extractAudioDialog.toggle_include_original_audio)
        self.compressAudio.clicked.connect(extractAudioDialog.toggle_compress_audio)
        self.rangeTo.timeChanged['QTime'].connect(extractAudioDialog.update_end_time)
        self.rangeFrom.timeChanged['QTime'].connect(extractAudioDialog.update_start_time)
        self.limitRange.clicked.connect(extractAudioDialog.toggle_range)
        self.showRemuxCommand.clicked.connect(extractAudioDialog.show_remux_cmd)
        QtCore.QMetaObject.connectSlotsByName(extractAudioDialog)

    def retranslateUi(self, extractAudioDialog):
        _translate = QtCore.QCoreApplication.translate
        extractAudioDialog.setWindowTitle(_translate("extractAudioDialog", "Extract Audio"))
        self.lfeChannelIndex.setToolTip(_translate("extractAudioDialog", "0 = No LFE"))
        self.channelCountLabel.setText(_translate("extractAudioDialog", "Channel Count"))
        self.streamsLabel.setText(_translate("extractAudioDialog", "Audio Stream"))
        self.targetDirectoryLabel.setText(_translate("extractAudioDialog", "Target Directory"))
        self.targetDirPicker.setText(_translate("extractAudioDialog", "..."))
        self.outputFilenameLabel.setText(_translate("extractAudioDialog", "Output Filename"))
        self.signalNameLabel.setText(_translate("extractAudioDialog", "Signal Name"))
        self.ffmpegCommandLabel.setText(_translate("extractAudioDialog", "ffmpeg command "))
        self.ffmpegProgressLabel.setText(_translate("extractAudioDialog", "Progress"))
        self.filterMappingLabel.setText(_translate("extractAudioDialog", "Signal Mapping"))
        self.ffmpegOutputLabel.setText(_translate("extractAudioDialog", "ffmpeg output"))
        self.showProbeButton.setText(_translate("extractAudioDialog", "..."))
        self.monoMix.setText(_translate("extractAudioDialog", "Mix to Mono?"))
        self.decimateAudio.setText(_translate("extractAudioDialog", "Decimate Audio?"))
        self.includeOriginalAudio.setText(_translate("extractAudioDialog", "Include Original Audio?"))
        self.compressAudio.setText(_translate("extractAudioDialog", "Compress Audio?"))
        self.videoStreamsLabel.setText(_translate("extractAudioDialog", "Video Stream"))
        self.inputFilePicker.setText(_translate("extractAudioDialog", "..."))
        self.inputFileLabel.setText(_translate("extractAudioDialog", "File"))
        self.lfeChannelIndexLabel.setText(_translate("extractAudioDialog", "LFE Channel"))
        self.label.setText(_translate("extractAudioDialog", "Range"))
        self.limitRange.setText(_translate("extractAudioDialog", "..."))
        self.rangeFrom.setDisplayFormat(_translate("extractAudioDialog", "HH:mm:ss.zzz"))
        self.rangeSeparatorLabel.setText(_translate("extractAudioDialog", "to"))
        self.rangeTo.setDisplayFormat(_translate("extractAudioDialog", "HH:mm:ss.zzz"))
        self.showRemuxCommand.setText(_translate("extractAudioDialog", "..."))

