# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editFilterDialog(object):
    def setupUi(self, editFilterDialog):
        editFilterDialog.setObjectName("editFilterDialog")
        editFilterDialog.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(editFilterDialog)
        self.formLayout.setObjectName("formLayout")
        self.filterType = QtWidgets.QComboBox(editFilterDialog)
        self.filterType.setObjectName("filterType")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.filterType)
        self.passFilterType = QtWidgets.QComboBox(editFilterDialog)
        self.passFilterType.setEnabled(False)
        self.passFilterType.setObjectName("passFilterType")
        self.passFilterType.addItem("")
        self.passFilterType.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passFilterType)
        self.filterOrder = QtWidgets.QSpinBox(editFilterDialog)
        self.filterOrder.setEnabled(False)
        self.filterOrder.setMinimum(1)
        self.filterOrder.setMaximum(24)
        self.filterOrder.setProperty("value", 2)
        self.filterOrder.setObjectName("filterOrder")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.filterOrder)
        self.buttonBox = QtWidgets.QDialogButtonBox(editFilterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.freq = QtWidgets.QDoubleSpinBox(editFilterDialog)
        self.freq.setDecimals(1)
        self.freq.setMinimum(1.0)
        self.freq.setMaximum(500.0)
        self.freq.setSingleStep(0.1)
        self.freq.setProperty("value", 40.0)
        self.freq.setObjectName("freq")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.freq)
        self.filterQ = QtWidgets.QDoubleSpinBox(editFilterDialog)
        self.filterQ.setDecimals(3)
        self.filterQ.setMinimum(0.001)
        self.filterQ.setMaximum(20.0)
        self.filterQ.setSingleStep(0.001)
        self.filterQ.setProperty("value", 0.707)
        self.filterQ.setObjectName("filterQ")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.filterQ)
        self.filterGain = QtWidgets.QDoubleSpinBox(editFilterDialog)
        self.filterGain.setDecimals(1)
        self.filterGain.setMinimum(-30.0)
        self.filterGain.setMaximum(30.0)
        self.filterGain.setSingleStep(0.1)
        self.filterGain.setObjectName("filterGain")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.filterGain)
        self.label = QtWidgets.QLabel(editFilterDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_5 = QtWidgets.QLabel(editFilterDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_2 = QtWidgets.QLabel(editFilterDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(editFilterDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(editFilterDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)

        self.retranslateUi(editFilterDialog)
        self.buttonBox.accepted.connect(editFilterDialog.accept)
        self.buttonBox.rejected.connect(editFilterDialog.reject)
        self.filterType.currentTextChanged['QString'].connect(editFilterDialog.enableFilterParams)
        self.passFilterType.currentTextChanged['QString'].connect(editFilterDialog.changeOrderStep)
        self.filterGain.valueChanged['double'].connect(editFilterDialog.enableOkIfGainIsValid)
        QtCore.QMetaObject.connectSlotsByName(editFilterDialog)

    def retranslateUi(self, editFilterDialog):
        _translate = QtCore.QCoreApplication.translate
        editFilterDialog.setWindowTitle(_translate("editFilterDialog", "Create Filter"))
        self.filterType.setItemText(0, _translate("editFilterDialog", "Low Shelf"))
        self.filterType.setItemText(1, _translate("editFilterDialog", "High Shelf"))
        self.filterType.setItemText(2, _translate("editFilterDialog", "Peak"))
        self.filterType.setItemText(3, _translate("editFilterDialog", "Variable Q LPF"))
        self.filterType.setItemText(4, _translate("editFilterDialog", "Variable Q HPF"))
        self.filterType.setItemText(5, _translate("editFilterDialog", "Low Pass"))
        self.filterType.setItemText(6, _translate("editFilterDialog", "High Pass"))
        self.passFilterType.setItemText(0, _translate("editFilterDialog", "Butterworth"))
        self.passFilterType.setItemText(1, _translate("editFilterDialog", "Linkwitz-Riley"))
        self.label.setText(_translate("editFilterDialog", "Type"))
        self.label_5.setText(_translate("editFilterDialog", "Order"))
        self.label_2.setText(_translate("editFilterDialog", "Freq"))
        self.label_3.setText(_translate("editFilterDialog", "Q"))
        self.label_4.setText(_translate("editFilterDialog", "Gain (dB)"))

