# Form implementation generated from reading ui file 'group_channels.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_groupChannelsDialog(object):
    def setupUi(self, groupChannelsDialog):
        groupChannelsDialog.setObjectName("groupChannelsDialog")
        groupChannelsDialog.resize(622, 316)
        self.gridLayout = QtWidgets.QGridLayout(groupChannelsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.channels = QtWidgets.QListWidget(parent=groupChannelsDialog)
        self.channels.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.channels.setObjectName("channels")
        self.gridLayout.addWidget(self.channels, 1, 1, 1, 4)
        self.channelGroups = QtWidgets.QListWidget(parent=groupChannelsDialog)
        self.channelGroups.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.channelGroups.setObjectName("channelGroups")
        self.gridLayout.addWidget(self.channelGroups, 1, 5, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=groupChannelsDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 6)
        self.groupName = QtWidgets.QLineEdit(parent=groupChannelsDialog)
        self.groupName.setInputMask("")
        self.groupName.setObjectName("groupName")
        self.gridLayout.addWidget(self.groupName, 2, 3, 1, 1)
        self.channelsLabel = QtWidgets.QLabel(parent=groupChannelsDialog)
        self.channelsLabel.setObjectName("channelsLabel")
        self.gridLayout.addWidget(self.channelsLabel, 0, 1, 1, 1)
        self.deleteGroupButton = QtWidgets.QToolButton(parent=groupChannelsDialog)
        self.deleteGroupButton.setObjectName("deleteGroupButton")
        self.gridLayout.addWidget(self.deleteGroupButton, 2, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.linkedLabel = QtWidgets.QLabel(parent=groupChannelsDialog)
        self.linkedLabel.setObjectName("linkedLabel")
        self.gridLayout.addWidget(self.linkedLabel, 0, 5, 1, 1)
        self.addGroupButton = QtWidgets.QToolButton(parent=groupChannelsDialog)
        self.addGroupButton.setObjectName("addGroupButton")
        self.gridLayout.addWidget(self.addGroupButton, 2, 2, 1, 1)
        self.linkAllButton = QtWidgets.QToolButton(parent=groupChannelsDialog)
        self.linkAllButton.setObjectName("linkAllButton")
        self.gridLayout.addWidget(self.linkAllButton, 2, 1, 1, 1)

        self.retranslateUi(groupChannelsDialog)
        self.buttonBox.accepted.connect(groupChannelsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(groupChannelsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(groupChannelsDialog)

    def retranslateUi(self, groupChannelsDialog):
        _translate = QtCore.QCoreApplication.translate
        groupChannelsDialog.setWindowTitle(_translate("groupChannelsDialog", "Group Channels"))
        self.groupName.setPlaceholderText(_translate("groupChannelsDialog", "Enter a channel group name"))
        self.channelsLabel.setText(_translate("groupChannelsDialog", "Channels"))
        self.deleteGroupButton.setText(_translate("groupChannelsDialog", "..."))
        self.linkedLabel.setText(_translate("groupChannelsDialog", "Grouped Channels"))
        self.addGroupButton.setText(_translate("groupChannelsDialog", "..."))
        self.linkAllButton.setText(_translate("groupChannelsDialog", "..."))
