# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_channels.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_groupChannelsDialog(object):
    def setupUi(self, groupChannelsDialog):
        groupChannelsDialog.setObjectName("groupChannelsDialog")
        groupChannelsDialog.resize(622, 316)
        self.gridLayout = QtWidgets.QGridLayout(groupChannelsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(groupChannelsDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.groupName = QtWidgets.QLineEdit(groupChannelsDialog)
        self.groupName.setInputMask("")
        self.groupName.setObjectName("groupName")
        self.gridLayout.addWidget(self.groupName, 2, 1, 1, 1)
        self.channelGroups = QtWidgets.QListWidget(groupChannelsDialog)
        self.channelGroups.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.channelGroups.setObjectName("channelGroups")
        self.gridLayout.addWidget(self.channelGroups, 1, 3, 1, 2)
        self.addGroupButton = QtWidgets.QToolButton(groupChannelsDialog)
        self.addGroupButton.setObjectName("addGroupButton")
        self.gridLayout.addWidget(self.addGroupButton, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.channels = QtWidgets.QListWidget(groupChannelsDialog)
        self.channels.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.channels.setObjectName("channels")
        self.gridLayout.addWidget(self.channels, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(groupChannelsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.deleteGroupButton = QtWidgets.QToolButton(groupChannelsDialog)
        self.deleteGroupButton.setObjectName("deleteGroupButton")
        self.gridLayout.addWidget(self.deleteGroupButton, 2, 4, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(groupChannelsDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 5)

        self.retranslateUi(groupChannelsDialog)
        self.buttonBox.accepted.connect(groupChannelsDialog.accept)
        self.buttonBox.rejected.connect(groupChannelsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(groupChannelsDialog)

    def retranslateUi(self, groupChannelsDialog):
        _translate = QtCore.QCoreApplication.translate
        groupChannelsDialog.setWindowTitle(_translate("groupChannelsDialog", "Link Channels"))
        self.label_2.setText(_translate("groupChannelsDialog", "Linked Channels"))
        self.groupName.setPlaceholderText(_translate("groupChannelsDialog", "Enter a channel group name"))
        self.addGroupButton.setText(_translate("groupChannelsDialog", "..."))
        self.label.setText(_translate("groupChannelsDialog", "Channels"))
        self.deleteGroupButton.setText(_translate("groupChannelsDialog", "..."))
