# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impulse.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_impulseDialog(object):
    def setupUi(self, impulseDialog):
        impulseDialog.setObjectName("impulseDialog")
        impulseDialog.resize(1070, 638)
        self.verticalLayout = QtWidgets.QVBoxLayout(impulseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previewChart = QtWidgets.QGraphicsView(impulseDialog)
        self.previewChart.setObjectName("previewChart")
        self.horizontalLayout.addWidget(self.previewChart)
        self.toolbarLayout = QtWidgets.QVBoxLayout()
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.limitsButton = QtWidgets.QToolButton(impulseDialog)
        self.limitsButton.setObjectName("limitsButton")
        self.toolbarLayout.addWidget(self.limitsButton)
        self.selectChannelsButton = QtWidgets.QToolButton(impulseDialog)
        self.selectChannelsButton.setObjectName("selectChannelsButton")
        self.toolbarLayout.addWidget(self.selectChannelsButton)
        self.chartToggle = QtWidgets.QToolButton(impulseDialog)
        self.chartToggle.setCheckable(True)
        self.chartToggle.setObjectName("chartToggle")
        self.toolbarLayout.addWidget(self.chartToggle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.toolbarLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.toolbarLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(impulseDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(impulseDialog)
        self.buttonBox.accepted.connect(impulseDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(impulseDialog.reject) # type: ignore
        self.limitsButton.clicked.connect(impulseDialog.show_limits) # type: ignore
        self.selectChannelsButton.toggled['bool'].connect(impulseDialog.update_chart) # type: ignore
        self.chartToggle.clicked.connect(impulseDialog.select_channels) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(impulseDialog)

    def retranslateUi(self, impulseDialog):
        _translate = QtCore.QCoreApplication.translate
        impulseDialog.setWindowTitle(_translate("impulseDialog", "Impulse/Step Response"))
        self.selectChannelsButton.setText(_translate("impulseDialog", "..."))
        self.chartToggle.setText(_translate("impulseDialog", "..."))
