# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jriver_filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jriverFilterDialog(object):
    def setupUi(self, jriverFilterDialog):
        jriverFilterDialog.setObjectName("jriverFilterDialog")
        jriverFilterDialog.resize(456, 334)
        self.verticalLayout = QtWidgets.QVBoxLayout(jriverFilterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(jriverFilterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(jriverFilterDialog)
        self.buttonBox.accepted.connect(jriverFilterDialog.accept)
        self.buttonBox.rejected.connect(jriverFilterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(jriverFilterDialog)

    def retranslateUi(self, jriverFilterDialog):
        _translate = QtCore.QCoreApplication.translate
        jriverFilterDialog.setWindowTitle(_translate("jriverFilterDialog", "Add/Edit Filter"))
