# Form implementation generated from reading ui file 'load_zone.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_loadDspFromZoneDialog(object):
    def setupUi(self, loadDspFromZoneDialog):
        loadDspFromZoneDialog.setObjectName("loadDspFromZoneDialog")
        loadDspFromZoneDialog.resize(428, 551)
        self.gridLayout = QtWidgets.QGridLayout(loadDspFromZoneDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.manageConnectionsLabel = QtWidgets.QLabel(parent=loadDspFromZoneDialog)
        self.manageConnectionsLabel.setWordWrap(True)
        self.manageConnectionsLabel.setObjectName("manageConnectionsLabel")
        self.gridLayout.addWidget(self.manageConnectionsLabel, 3, 0, 1, 3)
        self.zonesLabel = QtWidgets.QLabel(parent=loadDspFromZoneDialog)
        self.zonesLabel.setObjectName("zonesLabel")
        self.gridLayout.addWidget(self.zonesLabel, 1, 0, 1, 1)
        self.savedConnectionsLabel = QtWidgets.QLabel(parent=loadDspFromZoneDialog)
        self.savedConnectionsLabel.setObjectName("savedConnectionsLabel")
        self.gridLayout.addWidget(self.savedConnectionsLabel, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=loadDspFromZoneDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 3)
        self.savedConnections = QtWidgets.QListWidget(parent=loadDspFromZoneDialog)
        self.savedConnections.setObjectName("savedConnections")
        self.gridLayout.addWidget(self.savedConnections, 0, 1, 1, 1)
        self.zones = QtWidgets.QListWidget(parent=loadDspFromZoneDialog)
        self.zones.setObjectName("zones")
        self.gridLayout.addWidget(self.zones, 1, 1, 1, 1)
        self.upload = QtWidgets.QToolButton(parent=loadDspFromZoneDialog)
        self.upload.setObjectName("upload")
        self.gridLayout.addWidget(self.upload, 1, 2, 1, 1)
        self.resultLabel = QtWidgets.QLabel(parent=loadDspFromZoneDialog)
        self.resultLabel.setObjectName("resultLabel")
        self.gridLayout.addWidget(self.resultLabel, 2, 0, 1, 1)
        self.resultText = QtWidgets.QPlainTextEdit(parent=loadDspFromZoneDialog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.resultText.setFont(font)
        self.resultText.setReadOnly(True)
        self.resultText.setObjectName("resultText")
        self.gridLayout.addWidget(self.resultText, 2, 1, 1, 1)

        self.retranslateUi(loadDspFromZoneDialog)
        self.buttonBox.accepted.connect(loadDspFromZoneDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(loadDspFromZoneDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loadDspFromZoneDialog)
        loadDspFromZoneDialog.setTabOrder(self.savedConnections, self.zones)

    def retranslateUi(self, loadDspFromZoneDialog):
        _translate = QtCore.QCoreApplication.translate
        loadDspFromZoneDialog.setWindowTitle(_translate("loadDspFromZoneDialog", "Load DSP"))
        self.manageConnectionsLabel.setText(_translate("loadDspFromZoneDialog", "Add or remove Media Center servers in Preferences > JRiver."))
        self.zonesLabel.setText(_translate("loadDspFromZoneDialog", "Zone"))
        self.savedConnectionsLabel.setText(_translate("loadDspFromZoneDialog", "Connect To"))
        self.upload.setText(_translate("loadDspFromZoneDialog", "..."))
        self.resultLabel.setText(_translate("loadDspFromZoneDialog", "Result"))
