# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mds.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mdsDialog(object):
    def setupUi(self, mdsDialog):
        mdsDialog.setObjectName("mdsDialog")
        mdsDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(mdsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.orderLabel = QtWidgets.QLabel(mdsDialog)
        self.orderLabel.setObjectName("orderLabel")
        self.gridLayout.addWidget(self.orderLabel, 0, 0, 1, 1)
        self.dcGroupDelayMillis = QtWidgets.QDoubleSpinBox(mdsDialog)
        self.dcGroupDelayMillis.setReadOnly(True)
        self.dcGroupDelayMillis.setDecimals(3)
        self.dcGroupDelayMillis.setSingleStep(0.001)
        self.dcGroupDelayMillis.setObjectName("dcGroupDelayMillis")
        self.gridLayout.addWidget(self.dcGroupDelayMillis, 6, 1, 1, 1)
        self.frequency = QtWidgets.QSpinBox(mdsDialog)
        self.frequency.setMinimum(1)
        self.frequency.setMaximum(24000)
        self.frequency.setProperty("value", 100)
        self.frequency.setObjectName("frequency")
        self.gridLayout.addWidget(self.frequency, 1, 1, 1, 1)
        self.dcGroupDelayLabel = QtWidgets.QLabel(mdsDialog)
        self.dcGroupDelayLabel.setObjectName("dcGroupDelayLabel")
        self.gridLayout.addWidget(self.dcGroupDelayLabel, 6, 0, 1, 1)
        self.delayMillis = QtWidgets.QDoubleSpinBox(mdsDialog)
        self.delayMillis.setReadOnly(True)
        self.delayMillis.setDecimals(3)
        self.delayMillis.setSingleStep(0.001)
        self.delayMillis.setObjectName("delayMillis")
        self.gridLayout.addWidget(self.delayMillis, 5, 1, 1, 1)
        self.actualFrequency = QtWidgets.QDoubleSpinBox(mdsDialog)
        self.actualFrequency.setObjectName("actualFrequency")
        self.gridLayout.addWidget(self.actualFrequency, 2, 1, 1, 1)
        self.delaySamples = QtWidgets.QSpinBox(mdsDialog)
        self.delaySamples.setReadOnly(False)
        self.delaySamples.setObjectName("delaySamples")
        self.gridLayout.addWidget(self.delaySamples, 4, 1, 1, 1)
        self.frequencyLabel = QtWidgets.QLabel(mdsDialog)
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.gridLayout.addWidget(self.frequencyLabel, 1, 0, 1, 1)
        self.delayMillisLabel = QtWidgets.QLabel(mdsDialog)
        self.delayMillisLabel.setObjectName("delayMillisLabel")
        self.gridLayout.addWidget(self.delayMillisLabel, 5, 0, 1, 1)
        self.order = QtWidgets.QSpinBox(mdsDialog)
        self.order.setMinimum(1)
        self.order.setMaximum(8)
        self.order.setProperty("value", 4)
        self.order.setObjectName("order")
        self.gridLayout.addWidget(self.order, 0, 1, 1, 1)
        self.delaySamplesLabel = QtWidgets.QLabel(mdsDialog)
        self.delaySamplesLabel.setObjectName("delaySamplesLabel")
        self.gridLayout.addWidget(self.delaySamplesLabel, 4, 0, 1, 1)
        self.actualFrequencyLabel = QtWidgets.QLabel(mdsDialog)
        self.actualFrequencyLabel.setObjectName("actualFrequencyLabel")
        self.gridLayout.addWidget(self.actualFrequencyLabel, 2, 0, 1, 1)
        self.freqScalingFactor = QtWidgets.QDoubleSpinBox(mdsDialog)
        self.freqScalingFactor.setDecimals(4)
        self.freqScalingFactor.setSingleStep(0.0001)
        self.freqScalingFactor.setObjectName("freqScalingFactor")
        self.gridLayout.addWidget(self.freqScalingFactor, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(mdsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(mdsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mdsDialog)
        self.buttonBox.accepted.connect(mdsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(mdsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mdsDialog)

    def retranslateUi(self, mdsDialog):
        _translate = QtCore.QCoreApplication.translate
        mdsDialog.setWindowTitle(_translate("mdsDialog", "Matched Delay Subtractive Designer"))
        self.orderLabel.setText(_translate("mdsDialog", "Order"))
        self.dcGroupDelayLabel.setText(_translate("mdsDialog", "DC Group Delay (ms)"))
        self.frequencyLabel.setText(_translate("mdsDialog", "Target Frequency (Hz)"))
        self.delayMillisLabel.setText(_translate("mdsDialog", "Delay (ms)"))
        self.delaySamplesLabel.setText(_translate("mdsDialog", "Delay (samples)"))
        self.actualFrequencyLabel.setText(_translate("mdsDialog", "Actual Frequency (Hz)"))
        self.label.setText(_translate("mdsDialog", "Freq Scaling Factor"))
