# Form implementation generated from reading ui file 'newversion.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newVersionDialog(object):
    def setupUi(self, newVersionDialog):
        newVersionDialog.setObjectName("newVersionDialog")
        newVersionDialog.resize(586, 544)
        self.verticalLayout = QtWidgets.QVBoxLayout(newVersionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.message = QtWidgets.QLabel(parent=newVersionDialog)
        self.message.setObjectName("message")
        self.headerLayout.addWidget(self.message)
        self.headerLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.headerLayout)
        self.versionTable = QtWidgets.QTableView(parent=newVersionDialog)
        self.versionTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.versionTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.versionTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.versionTable.setObjectName("versionTable")
        self.verticalLayout.addWidget(self.versionTable)
        self.releaseNotes = QtWidgets.QTextBrowser(parent=newVersionDialog)
        self.releaseNotes.setOpenExternalLinks(True)
        self.releaseNotes.setObjectName("releaseNotes")
        self.verticalLayout.addWidget(self.releaseNotes)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=newVersionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(newVersionDialog)
        self.buttonBox.accepted.connect(newVersionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(newVersionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(newVersionDialog)

    def retranslateUi(self, newVersionDialog):
        _translate = QtCore.QCoreApplication.translate
        newVersionDialog.setWindowTitle(_translate("newVersionDialog", "New Version Available!"))
        self.message.setText(_translate("newVersionDialog", "Message"))
