# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jriverGraphDialog(object):
    def setupUi(self, jriverGraphDialog):
        jriverGraphDialog.setObjectName("jriverGraphDialog")
        jriverGraphDialog.resize(1036, 742)
        jriverGraphDialog.setSizeGripEnabled(True)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(jriverGraphDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outerLayout = QtWidgets.QVBoxLayout()
        self.outerLayout.setObjectName("outerLayout")
        self.direction = QtWidgets.QCheckBox(jriverGraphDialog)
        self.direction.setObjectName("direction")
        self.outerLayout.addWidget(self.direction)
        self.splitter = QtWidgets.QSplitter(jriverGraphDialog)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.source = QtWidgets.QPlainTextEdit(self.splitter)
        self.source.setObjectName("source")
        self.svgView = SvgView(self.splitter)
        self.svgView.setObjectName("svgView")
        self.outerLayout.addWidget(self.splitter)
        self.horizontalLayout_2.addLayout(self.outerLayout)

        self.retranslateUi(jriverGraphDialog)
        QtCore.QMetaObject.connectSlotsByName(jriverGraphDialog)

    def retranslateUi(self, jriverGraphDialog):
        _translate = QtCore.QCoreApplication.translate
        jriverGraphDialog.setWindowTitle(_translate("jriverGraphDialog", "JRiver DSP Filter Pipeline"))
        self.direction.setText(_translate("jriverGraphDialog", "Top to Bottom?"))
from svg import SvgView
