# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jriverGraphDialog(object):
    def setupUi(self, jriverGraphDialog):
        jriverGraphDialog.setObjectName("jriverGraphDialog")
        jriverGraphDialog.resize(626, 742)
        jriverGraphDialog.setSizeGripEnabled(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(jriverGraphDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.source = QtWidgets.QPlainTextEdit(jriverGraphDialog)
        self.source.setObjectName("source")
        self.horizontalLayout.addWidget(self.source)

        self.retranslateUi(jriverGraphDialog)
        QtCore.QMetaObject.connectSlotsByName(jriverGraphDialog)

    def retranslateUi(self, jriverGraphDialog):
        _translate = QtCore.QCoreApplication.translate
        jriverGraphDialog.setWindowTitle(_translate("jriverGraphDialog", "JRiver DSP Filter Pipeline"))
