# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preferencesDialog(object):
    def setupUi(self, preferencesDialog):
        preferencesDialog.setObjectName("preferencesDialog")
        preferencesDialog.resize(809, 334)
        self.verticalLayout = QtWidgets.QVBoxLayout(preferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panes = QtWidgets.QVBoxLayout()
        self.panes.setObjectName("panes")
        self.binariesPane = QtWidgets.QGridLayout()
        self.binariesPane.setObjectName("binariesPane")
        self.ffprobeLabel = QtWidgets.QLabel(preferencesDialog)
        self.ffprobeLabel.setObjectName("ffprobeLabel")
        self.binariesPane.addWidget(self.ffprobeLabel, 2, 0, 1, 1)
        self.binaryLabel = QtWidgets.QLabel(preferencesDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.binaryLabel.setFont(font)
        self.binaryLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.binaryLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.binaryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.binaryLabel.setObjectName("binaryLabel")
        self.binariesPane.addWidget(self.binaryLabel, 0, 0, 1, 4)
        self.ffprobeDirectoryPicker = QtWidgets.QToolButton(preferencesDialog)
        self.ffprobeDirectoryPicker.setObjectName("ffprobeDirectoryPicker")
        self.binariesPane.addWidget(self.ffprobeDirectoryPicker, 2, 3, 1, 1)
        self.ffmpegLabel = QtWidgets.QLabel(preferencesDialog)
        self.ffmpegLabel.setObjectName("ffmpegLabel")
        self.binariesPane.addWidget(self.ffmpegLabel, 1, 0, 1, 1)
        self.ffmpegDirectory = QtWidgets.QLineEdit(preferencesDialog)
        self.ffmpegDirectory.setEnabled(False)
        self.ffmpegDirectory.setObjectName("ffmpegDirectory")
        self.binariesPane.addWidget(self.ffmpegDirectory, 1, 1, 1, 2)
        self.ffmpegDirectoryPicker = QtWidgets.QToolButton(preferencesDialog)
        self.ffmpegDirectoryPicker.setObjectName("ffmpegDirectoryPicker")
        self.binariesPane.addWidget(self.ffmpegDirectoryPicker, 1, 3, 1, 1)
        self.ffprobeDirectory = QtWidgets.QLineEdit(preferencesDialog)
        self.ffprobeDirectory.setEnabled(False)
        self.ffprobeDirectory.setObjectName("ffprobeDirectory")
        self.binariesPane.addWidget(self.ffprobeDirectory, 2, 1, 1, 2)
        self.panes.addLayout(self.binariesPane)
        self.analysisPane = QtWidgets.QGridLayout()
        self.analysisPane.setObjectName("analysisPane")
        self.targetFs = QtWidgets.QComboBox(preferencesDialog)
        self.targetFs.setObjectName("targetFs")
        self.targetFs.addItem("")
        self.targetFs.addItem("")
        self.targetFs.addItem("")
        self.targetFs.addItem("")
        self.analysisPane.addWidget(self.targetFs, 1, 1, 1, 1)
        self.resolutionLabel = QtWidgets.QLabel(preferencesDialog)
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.analysisPane.addWidget(self.resolutionLabel, 1, 2, 1, 1)
        self.targetFsLabel = QtWidgets.QLabel(preferencesDialog)
        self.targetFsLabel.setObjectName("targetFsLabel")
        self.analysisPane.addWidget(self.targetFsLabel, 1, 0, 1, 1)
        self.analysisLabel = QtWidgets.QLabel(preferencesDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.analysisLabel.setFont(font)
        self.analysisLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.analysisLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.analysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisLabel.setObjectName("analysisLabel")
        self.analysisPane.addWidget(self.analysisLabel, 0, 0, 1, 4)
        self.resolutionSelect = QtWidgets.QComboBox(preferencesDialog)
        self.resolutionSelect.setObjectName("resolutionSelect")
        self.resolutionSelect.addItem("")
        self.resolutionSelect.addItem("")
        self.resolutionSelect.addItem("")
        self.analysisPane.addWidget(self.resolutionSelect, 1, 3, 1, 1)
        self.avgAnalysisWindowLabel = QtWidgets.QLabel(preferencesDialog)
        self.avgAnalysisWindowLabel.setObjectName("avgAnalysisWindowLabel")
        self.analysisPane.addWidget(self.avgAnalysisWindowLabel, 2, 0, 1, 1)
        self.avgAnalysisWindow = QtWidgets.QComboBox(preferencesDialog)
        self.avgAnalysisWindow.setObjectName("avgAnalysisWindow")
        self.analysisPane.addWidget(self.avgAnalysisWindow, 2, 1, 1, 1)
        self.peakAnalysisWindowLabel = QtWidgets.QLabel(preferencesDialog)
        self.peakAnalysisWindowLabel.setObjectName("peakAnalysisWindowLabel")
        self.analysisPane.addWidget(self.peakAnalysisWindowLabel, 2, 2, 1, 1)
        self.peakAnalysisWindow = QtWidgets.QComboBox(preferencesDialog)
        self.peakAnalysisWindow.setObjectName("peakAnalysisWindow")
        self.analysisPane.addWidget(self.peakAnalysisWindow, 2, 3, 1, 1)
        self.panes.addLayout(self.analysisPane)
        self.extractPane = QtWidgets.QGridLayout()
        self.extractPane.setObjectName("extractPane")
        self.defaultOutputDirectoryPicker = QtWidgets.QToolButton(preferencesDialog)
        self.defaultOutputDirectoryPicker.setObjectName("defaultOutputDirectoryPicker")
        self.extractPane.addWidget(self.defaultOutputDirectoryPicker, 1, 2, 1, 1)
        self.defaultOutputDirectoryLabel = QtWidgets.QLabel(preferencesDialog)
        self.defaultOutputDirectoryLabel.setObjectName("defaultOutputDirectoryLabel")
        self.extractPane.addWidget(self.defaultOutputDirectoryLabel, 1, 0, 1, 1)
        self.defaultOutputDirectory = QtWidgets.QLineEdit(preferencesDialog)
        self.defaultOutputDirectory.setEnabled(False)
        self.defaultOutputDirectory.setObjectName("defaultOutputDirectory")
        self.extractPane.addWidget(self.defaultOutputDirectory, 1, 1, 1, 1)
        self.extractionLabel = QtWidgets.QLabel(preferencesDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.extractionLabel.setFont(font)
        self.extractionLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.extractionLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.extractionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.extractionLabel.setObjectName("extractionLabel")
        self.extractPane.addWidget(self.extractionLabel, 0, 0, 1, 3)
        self.panes.addLayout(self.extractPane)
        self.verticalLayout.addLayout(self.panes)
        self.buttonBox = QtWidgets.QDialogButtonBox(preferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(preferencesDialog)
        self.buttonBox.accepted.connect(preferencesDialog.accept)
        self.buttonBox.rejected.connect(preferencesDialog.reject)
        self.ffmpegDirectoryPicker.clicked.connect(preferencesDialog.showFfmpegDirectoryPicker)
        self.ffprobeDirectoryPicker.clicked.connect(preferencesDialog.showFfprobeDirectoryPicker)
        self.defaultOutputDirectoryPicker.clicked.connect(preferencesDialog.showDefaultOutputDirectoryPicker)
        QtCore.QMetaObject.connectSlotsByName(preferencesDialog)

    def retranslateUi(self, preferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        preferencesDialog.setWindowTitle(_translate("preferencesDialog", "Preferences"))
        self.ffprobeLabel.setText(_translate("preferencesDialog", "ffprobe"))
        self.binaryLabel.setText(_translate("preferencesDialog", "Binaries"))
        self.ffprobeDirectoryPicker.setText(_translate("preferencesDialog", "..."))
        self.ffmpegLabel.setText(_translate("preferencesDialog", "ffmpeg"))
        self.ffmpegDirectoryPicker.setText(_translate("preferencesDialog", "..."))
        self.targetFs.setItemText(0, _translate("preferencesDialog", "500 Hz"))
        self.targetFs.setItemText(1, _translate("preferencesDialog", "1000 Hz"))
        self.targetFs.setItemText(2, _translate("preferencesDialog", "2000 Hz"))
        self.targetFs.setItemText(3, _translate("preferencesDialog", "Full Range"))
        self.resolutionLabel.setText(_translate("preferencesDialog", "Resolution"))
        self.targetFsLabel.setText(_translate("preferencesDialog", "Target Fs"))
        self.analysisLabel.setText(_translate("preferencesDialog", "Analysis"))
        self.resolutionSelect.setItemText(0, _translate("preferencesDialog", "1 Hz"))
        self.resolutionSelect.setItemText(1, _translate("preferencesDialog", "0.5 Hz"))
        self.resolutionSelect.setItemText(2, _translate("preferencesDialog", "0.25 Hz"))
        self.avgAnalysisWindowLabel.setText(_translate("preferencesDialog", "Avg Window"))
        self.peakAnalysisWindowLabel.setText(_translate("preferencesDialog", "Peak Window"))
        self.defaultOutputDirectoryPicker.setText(_translate("preferencesDialog", "..."))
        self.defaultOutputDirectoryLabel.setText(_translate("preferencesDialog", "Default Output Directory"))
        self.extractionLabel.setText(_translate("preferencesDialog", "Extraction"))

