# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preferencesDialog(object):
    def setupUi(self, preferencesDialog):
        preferencesDialog.setObjectName("preferencesDialog")
        preferencesDialog.resize(917, 279)
        self.verticalLayout = QtWidgets.QVBoxLayout(preferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(preferencesDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(preferencesDialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(preferencesDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(preferencesDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.ffmpegDirectoryPicker = QtWidgets.QToolButton(preferencesDialog)
        self.ffmpegDirectoryPicker.setObjectName("ffmpegDirectoryPicker")
        self.gridLayout_2.addWidget(self.ffmpegDirectoryPicker, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(preferencesDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(preferencesDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 5)
        self.soxDirectoryPicker = QtWidgets.QToolButton(preferencesDialog)
        self.soxDirectoryPicker.setObjectName("soxDirectoryPicker")
        self.gridLayout_2.addWidget(self.soxDirectoryPicker, 3, 4, 1, 1)
        self.ffprobeDirectoryPicker = QtWidgets.QToolButton(preferencesDialog)
        self.ffprobeDirectoryPicker.setObjectName("ffprobeDirectoryPicker")
        self.gridLayout_2.addWidget(self.ffprobeDirectoryPicker, 2, 4, 1, 1)
        self.targetFs = QtWidgets.QSpinBox(preferencesDialog)
        self.targetFs.setMinimum(500)
        self.targetFs.setMaximum(96000)
        self.targetFs.setSingleStep(100)
        self.targetFs.setProperty("value", 1000)
        self.targetFs.setObjectName("targetFs")
        self.gridLayout_2.addWidget(self.targetFs, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 2, 1, 3)
        self.ffmpegDirectory = QtWidgets.QLineEdit(preferencesDialog)
        self.ffmpegDirectory.setEnabled(False)
        self.ffmpegDirectory.setObjectName("ffmpegDirectory")
        self.gridLayout_2.addWidget(self.ffmpegDirectory, 1, 1, 1, 3)
        self.ffprobeDirectory = QtWidgets.QLineEdit(preferencesDialog)
        self.ffprobeDirectory.setEnabled(False)
        self.ffprobeDirectory.setObjectName("ffprobeDirectory")
        self.gridLayout_2.addWidget(self.ffprobeDirectory, 2, 1, 1, 3)
        self.soxDirectory = QtWidgets.QLineEdit(preferencesDialog)
        self.soxDirectory.setEnabled(False)
        self.soxDirectory.setObjectName("soxDirectory")
        self.gridLayout_2.addWidget(self.soxDirectory, 3, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(preferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(preferencesDialog)
        self.buttonBox.accepted.connect(preferencesDialog.accept)
        self.buttonBox.rejected.connect(preferencesDialog.reject)
        self.ffmpegDirectoryPicker.clicked.connect(preferencesDialog.showFfmpegDirectoryPicker)
        self.soxDirectoryPicker.clicked.connect(preferencesDialog.showSoxDirectoryPicker)
        self.ffprobeDirectoryPicker.clicked.connect(preferencesDialog.showFfprobeDirectoryPicker)
        QtCore.QMetaObject.connectSlotsByName(preferencesDialog)

    def retranslateUi(self, preferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        preferencesDialog.setWindowTitle(_translate("preferencesDialog", "Preferences"))
        self.label_4.setText(_translate("preferencesDialog", "ffprobe"))
        self.label.setText(_translate("preferencesDialog", "ffmpeg"))
        self.label_5.setText(_translate("preferencesDialog", "Analysis"))
        self.label_6.setText(_translate("preferencesDialog", "Target Fs"))
        self.ffmpegDirectoryPicker.setText(_translate("preferencesDialog", "..."))
        self.label_2.setText(_translate("preferencesDialog", "sox"))
        self.label_3.setText(_translate("preferencesDialog", "Binaries"))
        self.soxDirectoryPicker.setText(_translate("preferencesDialog", "..."))
        self.ffprobeDirectoryPicker.setText(_translate("preferencesDialog", "..."))

