# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_saveReportDialog(object):
    def setupUi(self, saveReportDialog):
        saveReportDialog.setObjectName("saveReportDialog")
        saveReportDialog.resize(1532, 1037)
        self.gridLayout_2 = QtWidgets.QGridLayout(saveReportDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableAlpha = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.tableAlpha.setMinimum(0.01)
        self.tableAlpha.setMaximum(1.0)
        self.tableAlpha.setSingleStep(0.01)
        self.tableAlpha.setProperty("value", 1.0)
        self.tableAlpha.setObjectName("tableAlpha")
        self.gridLayout.addWidget(self.tableAlpha, 15, 1, 1, 1)
        self.tableFontSizeLabel = QtWidgets.QLabel(saveReportDialog)
        self.tableFontSizeLabel.setObjectName("tableFontSizeLabel")
        self.gridLayout.addWidget(self.tableFontSizeLabel, 16, 0, 1, 1)
        self.tableFontSize = QtWidgets.QSpinBox(saveReportDialog)
        self.tableFontSize.setMaximum(24)
        self.tableFontSize.setProperty("value", 10)
        self.tableFontSize.setObjectName("tableFontSize")
        self.gridLayout.addWidget(self.tableFontSize, 16, 1, 1, 1)
        self.tableAlphaLabel = QtWidgets.QLabel(saveReportDialog)
        self.tableAlphaLabel.setObjectName("tableAlphaLabel")
        self.gridLayout.addWidget(self.tableAlphaLabel, 15, 0, 1, 1)
        self.heightLabel = QtWidgets.QLabel(saveReportDialog)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 7, 0, 1, 1)
        self.imageLabel = QtWidgets.QLabel(saveReportDialog)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 1, 0, 1, 1)
        self.gridOpacity = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.gridOpacity.setMaximum(1.0)
        self.gridOpacity.setSingleStep(0.01)
        self.gridOpacity.setProperty("value", 0.4)
        self.gridOpacity.setObjectName("gridOpacity")
        self.gridLayout.addWidget(self.gridOpacity, 24, 1, 1, 1)
        self.heightPixels = QtWidgets.QSpinBox(saveReportDialog)
        self.heightPixels.setMinimum(512)
        self.heightPixels.setMaximum(8192)
        self.heightPixels.setObjectName("heightPixels")
        self.gridLayout.addWidget(self.heightPixels, 7, 1, 1, 1)
        self.imageOpacity = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.imageOpacity.setDecimals(2)
        self.imageOpacity.setMinimum(0.01)
        self.imageOpacity.setMaximum(1.0)
        self.imageOpacity.setSingleStep(0.01)
        self.imageOpacity.setProperty("value", 1.0)
        self.imageOpacity.setObjectName("imageOpacity")
        self.gridLayout.addWidget(self.imageOpacity, 3, 1, 1, 1)
        self.image = QtWidgets.QLineEdit(saveReportDialog)
        self.image.setEnabled(True)
        self.image.setReadOnly(True)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 1, 1, 1, 1)
        self.imagePicker = QtWidgets.QToolButton(saveReportDialog)
        self.imagePicker.setObjectName("imagePicker")
        self.gridLayout.addWidget(self.imagePicker, 1, 2, 1, 1)
        self.chartLabel = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chartLabel.setFont(font)
        self.chartLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.chartLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.chartLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.chartLabel.setObjectName("chartLabel")
        self.gridLayout.addWidget(self.chartLabel, 23, 0, 1, 3)
        self.tableRowHeightLabel = QtWidgets.QLabel(saveReportDialog)
        self.tableRowHeightLabel.setObjectName("tableRowHeightLabel")
        self.gridLayout.addWidget(self.tableRowHeightLabel, 9, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.y0 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.y0.setDecimals(3)
        self.y0.setMaximum(0.999)
        self.y0.setSingleStep(0.001)
        self.y0.setProperty("value", 0.75)
        self.y0.setObjectName("y0")
        self.horizontalLayout_4.addWidget(self.y0)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 12, 1, 1, 1)
        self.titleLabel = QtWidgets.QLabel(saveReportDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 4, 0, 1, 1)
        self.layoutLabel = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.layoutLabel.setFont(font)
        self.layoutLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.layoutLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.layoutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.layoutLabel.setObjectName("layoutLabel")
        self.gridLayout.addWidget(self.layoutLabel, 18, 0, 1, 3)
        self.filtersLabel = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filtersLabel.setFont(font)
        self.filtersLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.filtersLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.filtersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filtersLabel.setObjectName("filtersLabel")
        self.gridLayout.addWidget(self.filtersLabel, 8, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(saveReportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 28, 0, 1, 3)
        self.curvesLabel = QtWidgets.QLabel(saveReportDialog)
        self.curvesLabel.setObjectName("curvesLabel")
        self.gridLayout.addWidget(self.curvesLabel, 25, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveLayout = QtWidgets.QPushButton(saveReportDialog)
        self.saveLayout.setObjectName("saveLayout")
        self.horizontalLayout_5.addWidget(self.saveLayout)
        self.gridLayout.addLayout(self.horizontalLayout_5, 27, 1, 1, 1)
        self.titleFontSizeLabel = QtWidgets.QLabel(saveReportDialog)
        self.titleFontSizeLabel.setObjectName("titleFontSizeLabel")
        self.gridLayout.addWidget(self.titleFontSizeLabel, 5, 0, 1, 1)
        self.showLegend = QtWidgets.QCheckBox(saveReportDialog)
        self.showLegend.setObjectName("showLegend")
        self.gridLayout.addWidget(self.showLegend, 26, 1, 1, 2)
        self.tablePositionLabel = QtWidgets.QLabel(saveReportDialog)
        self.tablePositionLabel.setObjectName("tablePositionLabel")
        self.gridLayout.addWidget(self.tablePositionLabel, 10, 0, 5, 1)
        self.chartLayout = QtWidgets.QComboBox(saveReportDialog)
        self.chartLayout.setObjectName("chartLayout")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.gridLayout.addWidget(self.chartLayout, 22, 1, 1, 1)
        self.limitsButton = QtWidgets.QToolButton(saveReportDialog)
        self.limitsButton.setObjectName("limitsButton")
        self.gridLayout.addWidget(self.limitsButton, 24, 2, 1, 1)
        self.filterRowHeightMultiplier = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.filterRowHeightMultiplier.setMaximum(3.0)
        self.filterRowHeightMultiplier.setSingleStep(0.01)
        self.filterRowHeightMultiplier.setProperty("value", 1.2)
        self.filterRowHeightMultiplier.setObjectName("filterRowHeightMultiplier")
        self.gridLayout.addWidget(self.filterRowHeightMultiplier, 9, 1, 1, 1)
        self.majorSplitRatioLabel = QtWidgets.QLabel(saveReportDialog)
        self.majorSplitRatioLabel.setObjectName("majorSplitRatioLabel")
        self.gridLayout.addWidget(self.majorSplitRatioLabel, 19, 0, 1, 1)
        self.curves = QtWidgets.QListWidget(saveReportDialog)
        self.curves.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.curves.setObjectName("curves")
        self.gridLayout.addWidget(self.curves, 25, 1, 1, 1)
        self.minorSplitRatio = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.minorSplitRatio.setMinimum(0.02)
        self.minorSplitRatio.setMaximum(10.0)
        self.minorSplitRatio.setSingleStep(0.02)
        self.minorSplitRatio.setProperty("value", 3.0)
        self.minorSplitRatio.setObjectName("minorSplitRatio")
        self.gridLayout.addWidget(self.minorSplitRatio, 20, 1, 1, 1)
        self.imageURLLabel = QtWidgets.QLabel(saveReportDialog)
        self.imageURLLabel.setObjectName("imageURLLabel")
        self.gridLayout.addWidget(self.imageURLLabel, 2, 0, 1, 1)
        self.loadURL = QtWidgets.QToolButton(saveReportDialog)
        self.loadURL.setObjectName("loadURL")
        self.gridLayout.addWidget(self.loadURL, 2, 2, 1, 1)
        self.majorSplitRatio = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.majorSplitRatio.setDecimals(2)
        self.majorSplitRatio.setMinimum(0.1)
        self.majorSplitRatio.setMaximum(10.0)
        self.majorSplitRatio.setSingleStep(0.02)
        self.majorSplitRatio.setProperty("value", 1.0)
        self.majorSplitRatio.setObjectName("majorSplitRatio")
        self.gridLayout.addWidget(self.majorSplitRatio, 19, 1, 1, 1)
        self.imageURL = QtWidgets.QLineEdit(saveReportDialog)
        self.imageURL.setObjectName("imageURL")
        self.gridLayout.addWidget(self.imageURL, 2, 1, 1, 1)
        self.minorSplitRatioLabel = QtWidgets.QLabel(saveReportDialog)
        self.minorSplitRatioLabel.setObjectName("minorSplitRatioLabel")
        self.gridLayout.addWidget(self.minorSplitRatioLabel, 20, 0, 1, 1)
        self.chartLayoutLabel = QtWidgets.QLabel(saveReportDialog)
        self.chartLayoutLabel.setObjectName("chartLayoutLabel")
        self.gridLayout.addWidget(self.chartLayoutLabel, 22, 0, 1, 1)
        self.imageAlphaLabel = QtWidgets.QLabel(saveReportDialog)
        self.imageAlphaLabel.setObjectName("imageAlphaLabel")
        self.gridLayout.addWidget(self.imageAlphaLabel, 3, 0, 1, 1)
        self.chartSplitLabel = QtWidgets.QLabel(saveReportDialog)
        self.chartSplitLabel.setObjectName("chartSplitLabel")
        self.gridLayout.addWidget(self.chartSplitLabel, 21, 0, 1, 1)
        self.gridAlphaLabel = QtWidgets.QLabel(saveReportDialog)
        self.gridAlphaLabel.setObjectName("gridAlphaLabel")
        self.gridLayout.addWidget(self.gridAlphaLabel, 24, 0, 1, 1)
        self.chartSplit = QtWidgets.QComboBox(saveReportDialog)
        self.chartSplit.setObjectName("chartSplit")
        self.chartSplit.addItem("")
        self.chartSplit.addItem("")
        self.gridLayout.addWidget(self.chartSplit, 21, 1, 1, 1)
        self.imageLabel_2 = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.imageLabel_2.setFont(font)
        self.imageLabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imageLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel_2.setObjectName("imageLabel_2")
        self.gridLayout.addWidget(self.imageLabel_2, 0, 0, 1, 3)
        self.titleFontSize = QtWidgets.QSpinBox(saveReportDialog)
        self.titleFontSize.setObjectName("titleFontSize")
        self.gridLayout.addWidget(self.titleFontSize, 5, 1, 1, 1)
        self.widthPixels = QtWidgets.QSpinBox(saveReportDialog)
        self.widthPixels.setMinimum(512)
        self.widthPixels.setMaximum(8192)
        self.widthPixels.setObjectName("widthPixels")
        self.gridLayout.addWidget(self.widthPixels, 6, 1, 1, 1)
        self.title = QtWidgets.QLineEdit(saveReportDialog)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.y1 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.y1.setDecimals(3)
        self.y1.setMaximum(1.0)
        self.y1.setSingleStep(0.001)
        self.y1.setProperty("value", 1.0)
        self.y1.setObjectName("y1")
        self.horizontalLayout_2.addWidget(self.y1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 10, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.x0 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.x0.setDecimals(3)
        self.x0.setMaximum(0.999)
        self.x0.setSingleStep(0.001)
        self.x0.setProperty("value", 0.748)
        self.x0.setObjectName("x0")
        self.horizontalLayout_3.addWidget(self.x0)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.x1 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.x1.setDecimals(3)
        self.x1.setMaximum(1.0)
        self.x1.setSingleStep(0.001)
        self.x1.setProperty("value", 1.0)
        self.x1.setObjectName("x1")
        self.horizontalLayout_3.addWidget(self.x1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 11, 1, 1, 1)
        self.widthLabel = QtWidgets.QLabel(saveReportDialog)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout.addWidget(self.widthLabel, 6, 0, 1, 1)
        self.showTableHeader = QtWidgets.QCheckBox(saveReportDialog)
        self.showTableHeader.setObjectName("showTableHeader")
        self.gridLayout.addWidget(self.showTableHeader, 17, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.preview = MplWidget(saveReportDialog)
        self.preview.setObjectName("preview")
        self.horizontalLayout.addWidget(self.preview)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)

        self.retranslateUi(saveReportDialog)
        self.chartLayout.setCurrentIndex(15)
        self.chartSplit.setCurrentIndex(1)
        self.buttonBox.accepted.connect(saveReportDialog.accept)
        self.buttonBox.rejected.connect(saveReportDialog.reject)
        self.curves.itemSelectionChanged.connect(saveReportDialog.set_selected)
        self.widthPixels.valueChanged['int'].connect(saveReportDialog.update_height)
        self.showLegend.clicked.connect(saveReportDialog.redraw)
        self.imagePicker.clicked.connect(saveReportDialog.choose_image)
        self.title.textChanged['QString'].connect(saveReportDialog.set_title)
        self.titleFontSize.valueChanged['int'].connect(saveReportDialog.set_title)
        self.majorSplitRatio.valueChanged['double'].connect(saveReportDialog.redraw_all_axes)
        self.chartSplit.currentIndexChanged['int'].connect(saveReportDialog.redraw_all_axes)
        self.limitsButton.clicked.connect(saveReportDialog.show_limits)
        self.chartSplit.currentIndexChanged['int'].connect(saveReportDialog.redraw_all_axes)
        self.chartLayout.currentIndexChanged['int'].connect(saveReportDialog.redraw_all_axes)
        self.minorSplitRatio.valueChanged['double'].connect(saveReportDialog.redraw_all_axes)
        self.gridOpacity.valueChanged['double'].connect(saveReportDialog.set_grid_opacity)
        self.imageOpacity.valueChanged['double'].connect(saveReportDialog.set_image_opacity)
        self.filterRowHeightMultiplier.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.y0.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.x0.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.y1.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.x1.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.saveLayout.clicked.connect(saveReportDialog.save_layout)
        self.imageURL.textChanged['QString'].connect(saveReportDialog.update_image_url)
        self.loadURL.clicked.connect(saveReportDialog.load_image_from_url)
        self.tableAlpha.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.tableFontSize.valueChanged['int'].connect(saveReportDialog.replace_table)
        self.showTableHeader.clicked.connect(saveReportDialog.replace_table)
        QtCore.QMetaObject.connectSlotsByName(saveReportDialog)
        saveReportDialog.setTabOrder(self.imagePicker, self.imageURL)
        saveReportDialog.setTabOrder(self.imageURL, self.loadURL)
        saveReportDialog.setTabOrder(self.loadURL, self.imageOpacity)
        saveReportDialog.setTabOrder(self.imageOpacity, self.title)
        saveReportDialog.setTabOrder(self.title, self.titleFontSize)
        saveReportDialog.setTabOrder(self.titleFontSize, self.widthPixels)
        saveReportDialog.setTabOrder(self.widthPixels, self.heightPixels)
        saveReportDialog.setTabOrder(self.heightPixels, self.filterRowHeightMultiplier)
        saveReportDialog.setTabOrder(self.filterRowHeightMultiplier, self.x0)
        saveReportDialog.setTabOrder(self.x0, self.y0)
        saveReportDialog.setTabOrder(self.y0, self.x1)
        saveReportDialog.setTabOrder(self.x1, self.y1)
        saveReportDialog.setTabOrder(self.y1, self.tableAlpha)
        saveReportDialog.setTabOrder(self.tableAlpha, self.tableFontSize)
        saveReportDialog.setTabOrder(self.tableFontSize, self.majorSplitRatio)
        saveReportDialog.setTabOrder(self.majorSplitRatio, self.minorSplitRatio)
        saveReportDialog.setTabOrder(self.minorSplitRatio, self.chartSplit)
        saveReportDialog.setTabOrder(self.chartSplit, self.chartLayout)
        saveReportDialog.setTabOrder(self.chartLayout, self.gridOpacity)
        saveReportDialog.setTabOrder(self.gridOpacity, self.curves)
        saveReportDialog.setTabOrder(self.curves, self.showLegend)
        saveReportDialog.setTabOrder(self.showLegend, self.limitsButton)
        saveReportDialog.setTabOrder(self.limitsButton, self.saveLayout)
        saveReportDialog.setTabOrder(self.saveLayout, self.preview)
        saveReportDialog.setTabOrder(self.preview, self.image)

    def retranslateUi(self, saveReportDialog):
        _translate = QtCore.QCoreApplication.translate
        saveReportDialog.setWindowTitle(_translate("saveReportDialog", "Save Report"))
        self.tableFontSizeLabel.setText(_translate("saveReportDialog", "Font Size"))
        self.tableAlphaLabel.setText(_translate("saveReportDialog", "Alpha"))
        self.heightLabel.setText(_translate("saveReportDialog", "Height"))
        self.imageLabel.setText(_translate("saveReportDialog", "File"))
        self.imagePicker.setText(_translate("saveReportDialog", "..."))
        self.chartLabel.setText(_translate("saveReportDialog", "Chart"))
        self.tableRowHeightLabel.setText(_translate("saveReportDialog", "Row Height"))
        self.titleLabel.setText(_translate("saveReportDialog", "Title"))
        self.layoutLabel.setText(_translate("saveReportDialog", "Layout"))
        self.filtersLabel.setText(_translate("saveReportDialog", "Filters"))
        self.curvesLabel.setText(_translate("saveReportDialog", "Curves"))
        self.saveLayout.setText(_translate("saveReportDialog", "Save Layout"))
        self.titleFontSizeLabel.setText(_translate("saveReportDialog", "Font Size"))
        self.showLegend.setText(_translate("saveReportDialog", "Show Legend?"))
        self.tablePositionLabel.setText(_translate("saveReportDialog", "Position"))
        self.chartLayout.setItemText(0, _translate("saveReportDialog", "Image | Chart, Filters"))
        self.chartLayout.setItemText(1, _translate("saveReportDialog", "Image | Filters, Chart"))
        self.chartLayout.setItemText(2, _translate("saveReportDialog", "Chart | Image, Filter"))
        self.chartLayout.setItemText(3, _translate("saveReportDialog", "Chart | Filters, Image"))
        self.chartLayout.setItemText(4, _translate("saveReportDialog", "Filters | Image, Chart"))
        self.chartLayout.setItemText(5, _translate("saveReportDialog", "Filters | Chart, Image"))
        self.chartLayout.setItemText(6, _translate("saveReportDialog", "Image, Filters | Chart"))
        self.chartLayout.setItemText(7, _translate("saveReportDialog", "Filters, Image | Chart"))
        self.chartLayout.setItemText(8, _translate("saveReportDialog", "Chart, Image | Filters"))
        self.chartLayout.setItemText(9, _translate("saveReportDialog", "Image, Chart | Filters"))
        self.chartLayout.setItemText(10, _translate("saveReportDialog", "Filters, Chart | Image"))
        self.chartLayout.setItemText(11, _translate("saveReportDialog", "Chart, Filters | Image"))
        self.chartLayout.setItemText(12, _translate("saveReportDialog", "Chart | Filters"))
        self.chartLayout.setItemText(13, _translate("saveReportDialog", "Filters | Chart"))
        self.chartLayout.setItemText(14, _translate("saveReportDialog", "Chart | Image"))
        self.chartLayout.setItemText(15, _translate("saveReportDialog", "Image | Chart"))
        self.limitsButton.setText(_translate("saveReportDialog", "..."))
        self.majorSplitRatioLabel.setText(_translate("saveReportDialog", "Major Split Ratio"))
        self.imageURLLabel.setText(_translate("saveReportDialog", "URL"))
        self.loadURL.setText(_translate("saveReportDialog", "..."))
        self.minorSplitRatioLabel.setText(_translate("saveReportDialog", "Minor Split Ratio"))
        self.chartLayoutLabel.setText(_translate("saveReportDialog", "Layout"))
        self.imageAlphaLabel.setText(_translate("saveReportDialog", "Alpha"))
        self.chartSplitLabel.setText(_translate("saveReportDialog", "Split"))
        self.gridAlphaLabel.setText(_translate("saveReportDialog", "Grid Alpha"))
        self.chartSplit.setItemText(0, _translate("saveReportDialog", "Horizontal"))
        self.chartSplit.setItemText(1, _translate("saveReportDialog", "Vertical"))
        self.imageLabel_2.setText(_translate("saveReportDialog", "Image"))
        self.widthLabel.setText(_translate("saveReportDialog", "Width"))
        self.showTableHeader.setText(_translate("saveReportDialog", "Show Header?"))

from mpl import MplWidget
