# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_saveReportDialog(object):
    def setupUi(self, saveReportDialog):
        saveReportDialog.setObjectName("saveReportDialog")
        saveReportDialog.resize(1532, 975)
        self.gridLayout_2 = QtWidgets.QGridLayout(saveReportDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.filterFontSizeLabel = QtWidgets.QLabel(saveReportDialog)
        self.filterFontSizeLabel.setObjectName("filterFontSizeLabel")
        self.gridLayout.addWidget(self.filterFontSizeLabel, 9, 0, 1, 1)
        self.majorSplitRatio = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.majorSplitRatio.setDecimals(2)
        self.majorSplitRatio.setMinimum(0.1)
        self.majorSplitRatio.setMaximum(10.0)
        self.majorSplitRatio.setSingleStep(0.02)
        self.majorSplitRatio.setProperty("value", 1.0)
        self.majorSplitRatio.setObjectName("majorSplitRatio")
        self.gridLayout.addWidget(self.majorSplitRatio, 16, 1, 1, 1)
        self.filterRowHeightMultiplier = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.filterRowHeightMultiplier.setMaximum(3.0)
        self.filterRowHeightMultiplier.setSingleStep(0.01)
        self.filterRowHeightMultiplier.setProperty("value", 1.2)
        self.filterRowHeightMultiplier.setObjectName("filterRowHeightMultiplier")
        self.gridLayout.addWidget(self.filterRowHeightMultiplier, 8, 1, 1, 1)
        self.filterFontSize = QtWidgets.QSpinBox(saveReportDialog)
        self.filterFontSize.setObjectName("filterFontSize")
        self.gridLayout.addWidget(self.filterFontSize, 9, 1, 1, 1)
        self.majorSplitRatioLabel = QtWidgets.QLabel(saveReportDialog)
        self.majorSplitRatioLabel.setObjectName("majorSplitRatioLabel")
        self.gridLayout.addWidget(self.majorSplitRatioLabel, 16, 0, 1, 1)
        self.minorSplitRatio = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.minorSplitRatio.setMinimum(0.02)
        self.minorSplitRatio.setMaximum(10.0)
        self.minorSplitRatio.setSingleStep(0.02)
        self.minorSplitRatio.setProperty("value", 3.0)
        self.minorSplitRatio.setObjectName("minorSplitRatio")
        self.gridLayout.addWidget(self.minorSplitRatio, 17, 1, 1, 1)
        self.minorSplitRatioLabel = QtWidgets.QLabel(saveReportDialog)
        self.minorSplitRatioLabel.setObjectName("minorSplitRatioLabel")
        self.gridLayout.addWidget(self.minorSplitRatioLabel, 17, 0, 1, 1)
        self.chartSplit = QtWidgets.QComboBox(saveReportDialog)
        self.chartSplit.setObjectName("chartSplit")
        self.chartSplit.addItem("")
        self.chartSplit.addItem("")
        self.gridLayout.addWidget(self.chartSplit, 18, 1, 1, 1)
        self.chartLayoutLabel = QtWidgets.QLabel(saveReportDialog)
        self.chartLayoutLabel.setObjectName("chartLayoutLabel")
        self.gridLayout.addWidget(self.chartLayoutLabel, 19, 0, 1, 1)
        self.chartSplitLabel = QtWidgets.QLabel(saveReportDialog)
        self.chartSplitLabel.setObjectName("chartSplitLabel")
        self.gridLayout.addWidget(self.chartSplitLabel, 18, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(saveReportDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.titleFontSize = QtWidgets.QSpinBox(saveReportDialog)
        self.titleFontSize.setObjectName("titleFontSize")
        self.gridLayout.addWidget(self.titleFontSize, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.y1 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.y1.setDecimals(3)
        self.y1.setMaximum(1.0)
        self.y1.setSingleStep(0.001)
        self.y1.setProperty("value", 1.0)
        self.y1.setObjectName("y1")
        self.horizontalLayout_2.addWidget(self.y1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(saveReportDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 21, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.x0 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.x0.setDecimals(3)
        self.x0.setMaximum(0.999)
        self.x0.setSingleStep(0.001)
        self.x0.setProperty("value", 0.75)
        self.x0.setObjectName("x0")
        self.horizontalLayout_3.addWidget(self.x0)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.x1 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.x1.setDecimals(3)
        self.x1.setMaximum(1.0)
        self.x1.setSingleStep(0.001)
        self.x1.setProperty("value", 1.0)
        self.x1.setObjectName("x1")
        self.horizontalLayout_3.addWidget(self.x1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 11, 1, 1, 1)
        self.title = QtWidgets.QLineEdit(saveReportDialog)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 3, 1, 1, 1)
        self.widthPixels = QtWidgets.QSpinBox(saveReportDialog)
        self.widthPixels.setMinimum(512)
        self.widthPixels.setMaximum(8192)
        self.widthPixels.setObjectName("widthPixels")
        self.gridLayout.addWidget(self.widthPixels, 5, 1, 1, 1)
        self.gridOpacity = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.gridOpacity.setMaximum(1.0)
        self.gridOpacity.setSingleStep(0.01)
        self.gridOpacity.setProperty("value", 0.5)
        self.gridOpacity.setObjectName("gridOpacity")
        self.gridLayout.addWidget(self.gridOpacity, 21, 1, 1, 1)
        self.widthLabel = QtWidgets.QLabel(saveReportDialog)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout.addWidget(self.widthLabel, 5, 0, 1, 1)
        self.heightPixels = QtWidgets.QSpinBox(saveReportDialog)
        self.heightPixels.setMinimum(512)
        self.heightPixels.setMaximum(8192)
        self.heightPixels.setObjectName("heightPixels")
        self.gridLayout.addWidget(self.heightPixels, 6, 1, 1, 1)
        self.heightLabel = QtWidgets.QLabel(saveReportDialog)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 6, 0, 1, 1)
        self.imagePicker = QtWidgets.QToolButton(saveReportDialog)
        self.imagePicker.setObjectName("imagePicker")
        self.gridLayout.addWidget(self.imagePicker, 1, 2, 1, 1)
        self.imageLabel = QtWidgets.QLabel(saveReportDialog)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(saveReportDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.image = QtWidgets.QLineEdit(saveReportDialog)
        self.image.setEnabled(False)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 1, 1, 1, 1)
        self.titleLabel = QtWidgets.QLabel(saveReportDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 15, 0, 1, 3)
        self.imageOpacity = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.imageOpacity.setDecimals(2)
        self.imageOpacity.setMinimum(0.01)
        self.imageOpacity.setMaximum(1.0)
        self.imageOpacity.setSingleStep(0.01)
        self.imageOpacity.setProperty("value", 1.0)
        self.imageOpacity.setObjectName("imageOpacity")
        self.gridLayout.addWidget(self.imageOpacity, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(saveReportDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 20, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.y0 = QtWidgets.QDoubleSpinBox(saveReportDialog)
        self.y0.setDecimals(3)
        self.y0.setMaximum(0.999)
        self.y0.setSingleStep(0.001)
        self.y0.setProperty("value", 0.75)
        self.y0.setObjectName("y0")
        self.horizontalLayout_4.addWidget(self.y0)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 12, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(saveReportDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 0, 5, 1)
        self.curvesLabel = QtWidgets.QLabel(saveReportDialog)
        self.curvesLabel.setObjectName("curvesLabel")
        self.gridLayout.addWidget(self.curvesLabel, 22, 0, 1, 1)
        self.chartLayout = QtWidgets.QComboBox(saveReportDialog)
        self.chartLayout.setObjectName("chartLayout")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.chartLayout.addItem("")
        self.gridLayout.addWidget(self.chartLayout, 19, 1, 1, 1)
        self.limitsButton = QtWidgets.QToolButton(saveReportDialog)
        self.limitsButton.setObjectName("limitsButton")
        self.gridLayout.addWidget(self.limitsButton, 19, 2, 1, 1)
        self.curves = QtWidgets.QListWidget(saveReportDialog)
        self.curves.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.curves.setObjectName("curves")
        self.gridLayout.addWidget(self.curves, 22, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(saveReportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 24, 0, 1, 3)
        self.showLegend = QtWidgets.QCheckBox(saveReportDialog)
        self.showLegend.setObjectName("showLegend")
        self.gridLayout.addWidget(self.showLegend, 23, 1, 1, 2)
        self.titleFontSizeLabel = QtWidgets.QLabel(saveReportDialog)
        self.titleFontSizeLabel.setObjectName("titleFontSizeLabel")
        self.gridLayout.addWidget(self.titleFontSizeLabel, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.preview = MplWidget(saveReportDialog)
        self.preview.setObjectName("preview")
        self.horizontalLayout.addWidget(self.preview)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)

        self.retranslateUi(saveReportDialog)
        self.chartSplit.setCurrentIndex(1)
        self.chartLayout.setCurrentIndex(15)
        self.buttonBox.accepted.connect(saveReportDialog.accept)
        self.buttonBox.rejected.connect(saveReportDialog.reject)
        self.curves.itemSelectionChanged.connect(saveReportDialog.set_selected)
        self.widthPixels.valueChanged['int'].connect(saveReportDialog.update_height)
        self.showLegend.clicked.connect(saveReportDialog.redraw)
        self.imagePicker.clicked.connect(saveReportDialog.choose_image)
        self.title.textChanged['QString'].connect(saveReportDialog.set_title)
        self.filterFontSize.valueChanged['int'].connect(saveReportDialog.set_table_font_size)
        self.titleFontSize.valueChanged['int'].connect(saveReportDialog.set_title)
        self.majorSplitRatio.valueChanged['double'].connect(saveReportDialog.redraw_all_axes)
        self.chartSplit.currentIndexChanged['int'].connect(saveReportDialog.redraw_all_axes)
        self.limitsButton.clicked.connect(saveReportDialog.show_limits)
        self.chartSplit.currentIndexChanged['int'].connect(saveReportDialog.redraw_all_axes)
        self.chartLayout.currentIndexChanged['int'].connect(saveReportDialog.redraw_all_axes)
        self.minorSplitRatio.valueChanged['double'].connect(saveReportDialog.redraw_all_axes)
        self.gridOpacity.valueChanged['double'].connect(saveReportDialog.set_grid_opacity)
        self.imageOpacity.valueChanged['double'].connect(saveReportDialog.set_image_opacity)
        self.filterRowHeightMultiplier.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.y0.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.x0.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.y1.valueChanged['double'].connect(saveReportDialog.replace_table)
        self.x1.valueChanged['double'].connect(saveReportDialog.replace_table)
        QtCore.QMetaObject.connectSlotsByName(saveReportDialog)

    def retranslateUi(self, saveReportDialog):
        _translate = QtCore.QCoreApplication.translate
        saveReportDialog.setWindowTitle(_translate("saveReportDialog", "Save Report"))
        self.filterFontSizeLabel.setText(_translate("saveReportDialog", "Font Size"))
        self.majorSplitRatioLabel.setText(_translate("saveReportDialog", "Major Split Ratio"))
        self.minorSplitRatioLabel.setText(_translate("saveReportDialog", "Minor Split Ratio"))
        self.chartSplit.setItemText(0, _translate("saveReportDialog", "Horizontal"))
        self.chartSplit.setItemText(1, _translate("saveReportDialog", "Vertical"))
        self.chartLayoutLabel.setText(_translate("saveReportDialog", "Layout"))
        self.chartSplitLabel.setText(_translate("saveReportDialog", "Split"))
        self.label_5.setText(_translate("saveReportDialog", "Image"))
        self.label.setText(_translate("saveReportDialog", "Alpha"))
        self.label_2.setText(_translate("saveReportDialog", "Grid Alpha"))
        self.widthLabel.setText(_translate("saveReportDialog", "Width"))
        self.heightLabel.setText(_translate("saveReportDialog", "Height"))
        self.imagePicker.setText(_translate("saveReportDialog", "..."))
        self.imageLabel.setText(_translate("saveReportDialog", "Image"))
        self.label_3.setText(_translate("saveReportDialog", "Row Height"))
        self.titleLabel.setText(_translate("saveReportDialog", "Title"))
        self.label_7.setText(_translate("saveReportDialog", "Layout"))
        self.label_4.setText(_translate("saveReportDialog", "Filters"))
        self.label_6.setText(_translate("saveReportDialog", "Chart"))
        self.label_8.setText(_translate("saveReportDialog", "Position"))
        self.curvesLabel.setText(_translate("saveReportDialog", "Curves"))
        self.chartLayout.setItemText(0, _translate("saveReportDialog", "Image | Chart, Filters"))
        self.chartLayout.setItemText(1, _translate("saveReportDialog", "Image | Filters, Chart"))
        self.chartLayout.setItemText(2, _translate("saveReportDialog", "Chart | Image, Filter"))
        self.chartLayout.setItemText(3, _translate("saveReportDialog", "Chart | Filters, Image"))
        self.chartLayout.setItemText(4, _translate("saveReportDialog", "Filters | Image, Chart"))
        self.chartLayout.setItemText(5, _translate("saveReportDialog", "Filters | Chart, Image"))
        self.chartLayout.setItemText(6, _translate("saveReportDialog", "Image, Filters | Chart"))
        self.chartLayout.setItemText(7, _translate("saveReportDialog", "Filters, Image | Chart"))
        self.chartLayout.setItemText(8, _translate("saveReportDialog", "Chart, Image | Filters"))
        self.chartLayout.setItemText(9, _translate("saveReportDialog", "Image, Chart | Filters"))
        self.chartLayout.setItemText(10, _translate("saveReportDialog", "Filters, Chart | Image"))
        self.chartLayout.setItemText(11, _translate("saveReportDialog", "Chart, Filters | Image"))
        self.chartLayout.setItemText(12, _translate("saveReportDialog", "Chart | Filters"))
        self.chartLayout.setItemText(13, _translate("saveReportDialog", "Filters | Chart"))
        self.chartLayout.setItemText(14, _translate("saveReportDialog", "Chart | Image"))
        self.chartLayout.setItemText(15, _translate("saveReportDialog", "Image | Chart"))
        self.limitsButton.setText(_translate("saveReportDialog", "..."))
        self.showLegend.setText(_translate("saveReportDialog", "Show Legend?"))
        self.titleFontSizeLabel.setText(_translate("saveReportDialog", "Font Size"))

from mpl import MplWidget
