# Form implementation generated from reading ui file 'savechart.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_saveChartDialog(object):
    def setupUi(self, saveChartDialog):
        saveChartDialog.setObjectName("saveChartDialog")
        saveChartDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        saveChartDialog.resize(259, 155)
        saveChartDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(saveChartDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.widthPixels = QtWidgets.QSpinBox(parent=saveChartDialog)
        self.widthPixels.setMinimum(1)
        self.widthPixels.setMaximum(8192)
        self.widthPixels.setObjectName("widthPixels")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.widthPixels)
        self.heightPixels = QtWidgets.QSpinBox(parent=saveChartDialog)
        self.heightPixels.setEnabled(False)
        self.heightPixels.setMinimum(1)
        self.heightPixels.setMaximum(8192)
        self.heightPixels.setObjectName("heightPixels")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.heightPixels)
        self.label = QtWidgets.QLabel(parent=saveChartDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=saveChartDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=saveChartDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(saveChartDialog)
        self.buttonBox.accepted.connect(saveChartDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(saveChartDialog.reject) # type: ignore
        self.widthPixels.valueChanged['int'].connect(saveChartDialog.set_height) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(saveChartDialog)

    def retranslateUi(self, saveChartDialog):
        _translate = QtCore.QCoreApplication.translate
        saveChartDialog.setWindowTitle(_translate("saveChartDialog", "Save Chart"))
        self.label.setText(_translate("saveChartDialog", "Width"))
        self.label_2.setText(_translate("saveChartDialog", "Height"))
