# Form implementation generated from reading ui file 'signal_viz.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_selectSignalsDialog(object):
    def setupUi(self, selectSignalsDialog):
        selectSignalsDialog.setObjectName("selectSignalsDialog")
        selectSignalsDialog.resize(424, 374)
        self.gridLayout = QtWidgets.QGridLayout(selectSignalsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=selectSignalsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.signals = QtWidgets.QListWidget(parent=selectSignalsDialog)
        self.signals.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.signals.setObjectName("signals")
        self.gridLayout.addWidget(self.signals, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=selectSignalsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(selectSignalsDialog)
        self.buttonBox.accepted.connect(selectSignalsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(selectSignalsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(selectSignalsDialog)

    def retranslateUi(self, selectSignalsDialog):
        _translate = QtCore.QCoreApplication.translate
        selectSignalsDialog.setWindowTitle(_translate("selectSignalsDialog", "Set Signal Visibility"))
        self.label.setText(_translate("selectSignalsDialog", "Select signals to include in the main chart view:"))
