# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addSignalDialog(object):
    def setupUi(self, addSignalDialog):
        addSignalDialog.setObjectName("addSignalDialog")
        addSignalDialog.resize(1392, 748)
        self.verticalLayout = QtWidgets.QVBoxLayout(addSignalDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panesLayout = QtWidgets.QGridLayout()
        self.panesLayout.setObjectName("panesLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.channelLabel = QtWidgets.QLabel(addSignalDialog)
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout.addWidget(self.channelLabel, 3, 0, 1, 1)
        self.file = QtWidgets.QLineEdit(addSignalDialog)
        self.file.setEnabled(False)
        self.file.setReadOnly(True)
        self.file.setObjectName("file")
        self.gridLayout.addWidget(self.file, 1, 1, 1, 1)
        self.filePicker = QtWidgets.QToolButton(addSignalDialog)
        self.filePicker.setObjectName("filePicker")
        self.gridLayout.addWidget(self.filePicker, 1, 2, 1, 1)
        self.channelSelector = QtWidgets.QComboBox(addSignalDialog)
        self.channelSelector.setEnabled(False)
        self.channelSelector.setObjectName("channelSelector")
        self.gridLayout.addWidget(self.channelSelector, 3, 1, 1, 1)
        self.signalName = QtWidgets.QLineEdit(addSignalDialog)
        self.signalName.setEnabled(False)
        self.signalName.setObjectName("signalName")
        self.gridLayout.addWidget(self.signalName, 6, 1, 1, 1)
        self.endTimeLabel = QtWidgets.QLabel(addSignalDialog)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.gridLayout.addWidget(self.endTimeLabel, 5, 0, 1, 1)
        self.startTime = QtWidgets.QTimeEdit(addSignalDialog)
        self.startTime.setEnabled(False)
        self.startTime.setTime(QtCore.QTime(1, 0, 0))
        self.startTime.setObjectName("startTime")
        self.gridLayout.addWidget(self.startTime, 4, 1, 1, 1)
        self.endTime = QtWidgets.QTimeEdit(addSignalDialog)
        self.endTime.setEnabled(False)
        self.endTime.setObjectName("endTime")
        self.gridLayout.addWidget(self.endTime, 5, 1, 1, 1)
        self.startTimeLabel = QtWidgets.QLabel(addSignalDialog)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.gridLayout.addWidget(self.startTimeLabel, 4, 0, 1, 1)
        self.signalNameLabel = QtWidgets.QLabel(addSignalDialog)
        self.signalNameLabel.setObjectName("signalNameLabel")
        self.gridLayout.addWidget(self.signalNameLabel, 6, 0, 1, 1)
        self.fsLabel = QtWidgets.QLabel(addSignalDialog)
        self.fsLabel.setObjectName("fsLabel")
        self.gridLayout.addWidget(self.fsLabel, 2, 0, 1, 1)
        self.fileTypePicker = QtWidgets.QComboBox(addSignalDialog)
        self.fileTypePicker.setObjectName("fileTypePicker")
        self.fileTypePicker.addItem("")
        self.fileTypePicker.addItem("")
        self.gridLayout.addWidget(self.fileTypePicker, 0, 1, 1, 1)
        self.fileLabel = QtWidgets.QLabel(addSignalDialog)
        self.fileLabel.setObjectName("fileLabel")
        self.gridLayout.addWidget(self.fileLabel, 1, 0, 1, 1)
        self.fileTypePickerLabel = QtWidgets.QLabel(addSignalDialog)
        self.fileTypePickerLabel.setObjectName("fileTypePickerLabel")
        self.gridLayout.addWidget(self.fileTypePickerLabel, 0, 0, 1, 1)
        self.fs = QtWidgets.QLineEdit(addSignalDialog)
        self.fs.setEnabled(False)
        self.fs.setObjectName("fs")
        self.gridLayout.addWidget(self.fs, 2, 1, 1, 1)
        self.previewButton = QtWidgets.QPushButton(addSignalDialog)
        self.previewButton.setEnabled(False)
        self.previewButton.setObjectName("previewButton")
        self.gridLayout.addWidget(self.previewButton, 7, 1, 1, 1)
        self.panesLayout.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.panesLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.previewChart = MplWidget(addSignalDialog)
        self.previewChart.setObjectName("previewChart")
        self.panesLayout.addWidget(self.previewChart, 0, 1, 2, 1)
        self.panesLayout.setColumnStretch(0, 1)
        self.panesLayout.setColumnStretch(1, 3)
        self.verticalLayout.addLayout(self.panesLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(addSignalDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addSignalDialog)
        self.buttonBox.rejected.connect(addSignalDialog.reject)
        self.buttonBox.accepted.connect(addSignalDialog.accept)
        self.filePicker.clicked.connect(addSignalDialog.selectFile)
        self.previewButton.clicked.connect(addSignalDialog.prepareSignal)
        self.signalName.textChanged['QString'].connect(addSignalDialog.enablePreview)
        QtCore.QMetaObject.connectSlotsByName(addSignalDialog)

    def retranslateUi(self, addSignalDialog):
        _translate = QtCore.QCoreApplication.translate
        addSignalDialog.setWindowTitle(_translate("addSignalDialog", "Load Signal"))
        self.channelLabel.setText(_translate("addSignalDialog", "Channel"))
        self.filePicker.setText(_translate("addSignalDialog", "..."))
        self.endTimeLabel.setText(_translate("addSignalDialog", "End"))
        self.startTime.setDisplayFormat(_translate("addSignalDialog", "HH:mm:ss.zzz"))
        self.endTime.setDisplayFormat(_translate("addSignalDialog", "HH:mm:ss.zzz"))
        self.startTimeLabel.setText(_translate("addSignalDialog", "Start"))
        self.signalNameLabel.setText(_translate("addSignalDialog", "Name"))
        self.fsLabel.setText(_translate("addSignalDialog", "Fs"))
        self.fileTypePicker.setItemText(0, _translate("addSignalDialog", "wav"))
        self.fileTypePicker.setItemText(1, _translate("addSignalDialog", "frd"))
        self.fileLabel.setText(_translate("addSignalDialog", "File"))
        self.fileTypePickerLabel.setText(_translate("addSignalDialog", "File Type"))
        self.previewButton.setText(_translate("addSignalDialog", "Preview"))

from mpl import MplWidget
