# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signalStatsDialog(object):
    def setupUi(self, signalStatsDialog):
        signalStatsDialog.setObjectName("signalStatsDialog")
        signalStatsDialog.resize(306, 561)
        self.gridLayout = QtWidgets.QGridLayout(signalStatsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.rms = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.rms.setReadOnly(True)
        self.rms.setMinimum(-150.0)
        self.rms.setMaximum(10.0)
        self.rms.setSingleStep(0.01)
        self.rms.setObjectName("rms")
        self.gridLayout.addWidget(self.rms, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(signalStatsDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(signalStatsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 3)
        self.slowPeak = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.slowPeak.setReadOnly(True)
        self.slowPeak.setMinimum(-150.0)
        self.slowPeak.setMaximum(10.0)
        self.slowPeak.setSingleStep(0.01)
        self.slowPeak.setObjectName("slowPeak")
        self.gridLayout.addWidget(self.slowPeak, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(signalStatsDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(signalStatsDialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 11, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(signalStatsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 14, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(signalStatsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 18, 0, 1, 3)
        self.label_18 = QtWidgets.QLabel(signalStatsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 17, 0, 1, 1)
        self.includeInstant = QtWidgets.QToolButton(signalStatsDialog)
        self.includeInstant.setText("")
        self.includeInstant.setCheckable(True)
        self.includeInstant.setChecked(True)
        self.includeInstant.setObjectName("includeInstant")
        self.gridLayout.addWidget(self.includeInstant, 3, 2, 1, 1)
        self.customPeak = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.customPeak.setReadOnly(True)
        self.customPeak.setMinimum(-150.0)
        self.customPeak.setMaximum(10.0)
        self.customPeak.setSingleStep(0.01)
        self.customPeak.setObjectName("customPeak")
        self.gridLayout.addWidget(self.customPeak, 7, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.peakExtensionX1 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.peakExtensionX1.setReadOnly(True)
        self.peakExtensionX1.setDecimals(1)
        self.peakExtensionX1.setMaximum(160.0)
        self.peakExtensionX1.setSingleStep(0.1)
        self.peakExtensionX1.setObjectName("peakExtensionX1")
        self.gridLayout_3.addWidget(self.peakExtensionX1, 0, 0, 1, 1)
        self.peakExtensionX2 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.peakExtensionX2.setReadOnly(True)
        self.peakExtensionX2.setDecimals(1)
        self.peakExtensionX2.setMaximum(160.0)
        self.peakExtensionX2.setSingleStep(0.1)
        self.peakExtensionX2.setObjectName("peakExtensionX2")
        self.gridLayout_3.addWidget(self.peakExtensionX2, 0, 1, 1, 1)
        self.peakExtensionY1 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.peakExtensionY1.setReadOnly(True)
        self.peakExtensionY1.setMinimum(-120.0)
        self.peakExtensionY1.setMaximum(0.0)
        self.peakExtensionY1.setSingleStep(0.01)
        self.peakExtensionY1.setObjectName("peakExtensionY1")
        self.gridLayout_3.addWidget(self.peakExtensionY1, 1, 0, 1, 1)
        self.peakExtensionY2 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.peakExtensionY2.setReadOnly(True)
        self.peakExtensionY2.setMinimum(-120.0)
        self.peakExtensionY2.setMaximum(0.0)
        self.peakExtensionY2.setSingleStep(0.01)
        self.peakExtensionY2.setObjectName("peakExtensionY2")
        self.gridLayout_3.addWidget(self.peakExtensionY2, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 13, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(signalStatsDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(signalStatsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 15, 0, 1, 3)
        self.includeFast = QtWidgets.QToolButton(signalStatsDialog)
        self.includeFast.setText("")
        self.includeFast.setCheckable(True)
        self.includeFast.setObjectName("includeFast")
        self.gridLayout.addWidget(self.includeFast, 4, 2, 1, 1)
        self.includeRMS = QtWidgets.QToolButton(signalStatsDialog)
        self.includeRMS.setText("")
        self.includeRMS.setCheckable(True)
        self.includeRMS.setChecked(True)
        self.includeRMS.setObjectName("includeRMS")
        self.gridLayout.addWidget(self.includeRMS, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(signalStatsDialog)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(signalStatsDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.levelRating = QtWidgets.QSpinBox(signalStatsDialog)
        self.levelRating.setReadOnly(True)
        self.levelRating.setMaximum(5)
        self.levelRating.setObjectName("levelRating")
        self.gridLayout.addWidget(self.levelRating, 9, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(signalStatsDialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 16, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.averageExtensionX1 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.averageExtensionX1.setReadOnly(True)
        self.averageExtensionX1.setDecimals(1)
        self.averageExtensionX1.setMaximum(160.0)
        self.averageExtensionX1.setSingleStep(0.1)
        self.averageExtensionX1.setObjectName("averageExtensionX1")
        self.gridLayout_2.addWidget(self.averageExtensionX1, 0, 0, 1, 1)
        self.averageExtensionX2 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.averageExtensionX2.setReadOnly(True)
        self.averageExtensionX2.setDecimals(1)
        self.averageExtensionX2.setMaximum(160.0)
        self.averageExtensionX2.setSingleStep(0.1)
        self.averageExtensionX2.setObjectName("averageExtensionX2")
        self.gridLayout_2.addWidget(self.averageExtensionX2, 0, 1, 1, 1)
        self.averageExtensionY1 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.averageExtensionY1.setReadOnly(True)
        self.averageExtensionY1.setMinimum(-120.0)
        self.averageExtensionY1.setMaximum(10.0)
        self.averageExtensionY1.setSingleStep(0.01)
        self.averageExtensionY1.setObjectName("averageExtensionY1")
        self.gridLayout_2.addWidget(self.averageExtensionY1, 1, 0, 1, 1)
        self.averageExtensionY2 = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.averageExtensionY2.setReadOnly(True)
        self.averageExtensionY2.setMinimum(-120.0)
        self.averageExtensionY2.setMaximum(10.0)
        self.averageExtensionY2.setSingleStep(0.01)
        self.averageExtensionY2.setObjectName("averageExtensionY2")
        self.gridLayout_2.addWidget(self.averageExtensionY2, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 12, 1, 1, 2)
        self.includeSlow = QtWidgets.QToolButton(signalStatsDialog)
        self.includeSlow.setText("")
        self.includeSlow.setCheckable(True)
        self.includeSlow.setChecked(True)
        self.includeSlow.setObjectName("includeSlow")
        self.gridLayout.addWidget(self.includeSlow, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(signalStatsDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(signalStatsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 3)
        self.compositeLevel = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.compositeLevel.setReadOnly(True)
        self.compositeLevel.setMinimum(-150.0)
        self.compositeLevel.setMaximum(10.0)
        self.compositeLevel.setSingleStep(0.01)
        self.compositeLevel.setObjectName("compositeLevel")
        self.gridLayout.addWidget(self.compositeLevel, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(signalStatsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(signalStatsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 9, 0, 1, 1)
        self.instantPeak = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.instantPeak.setReadOnly(True)
        self.instantPeak.setMinimum(-150.0)
        self.instantPeak.setMaximum(10.0)
        self.instantPeak.setSingleStep(0.01)
        self.instantPeak.setObjectName("instantPeak")
        self.gridLayout.addWidget(self.instantPeak, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(signalStatsDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.extensionLimit = QtWidgets.QSpinBox(signalStatsDialog)
        self.extensionLimit.setMinimum(-20)
        self.extensionLimit.setMaximum(-1)
        self.extensionLimit.setProperty("value", -10)
        self.extensionLimit.setObjectName("extensionLimit")
        self.gridLayout.addWidget(self.extensionLimit, 11, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(signalStatsDialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.customIntegrationTime = QtWidgets.QSpinBox(signalStatsDialog)
        self.customIntegrationTime.setMinimum(1)
        self.customIntegrationTime.setMaximum(60000)
        self.customIntegrationTime.setProperty("value", 5000)
        self.customIntegrationTime.setObjectName("customIntegrationTime")
        self.gridLayout.addWidget(self.customIntegrationTime, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(signalStatsDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.dynamics = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.dynamics.setReadOnly(True)
        self.dynamics.setSingleStep(0.01)
        self.dynamics.setObjectName("dynamics")
        self.gridLayout.addWidget(self.dynamics, 16, 1, 1, 2)
        self.includeCustom = QtWidgets.QToolButton(signalStatsDialog)
        self.includeCustom.setText("")
        self.includeCustom.setCheckable(True)
        self.includeCustom.setObjectName("includeCustom")
        self.gridLayout.addWidget(self.includeCustom, 7, 2, 1, 1)
        self.fastPeak = QtWidgets.QDoubleSpinBox(signalStatsDialog)
        self.fastPeak.setReadOnly(True)
        self.fastPeak.setMinimum(-150.0)
        self.fastPeak.setMaximum(10.0)
        self.fastPeak.setSingleStep(0.01)
        self.fastPeak.setObjectName("fastPeak")
        self.gridLayout.addWidget(self.fastPeak, 4, 1, 1, 1)
        self.dynamicsRating = QtWidgets.QSpinBox(signalStatsDialog)
        self.dynamicsRating.setReadOnly(True)
        self.dynamicsRating.setMaximum(5)
        self.dynamicsRating.setObjectName("dynamicsRating")
        self.gridLayout.addWidget(self.dynamicsRating, 17, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.extensionSource = QtWidgets.QComboBox(signalStatsDialog)
        self.extensionSource.setEnabled(False)
        self.extensionSource.setObjectName("extensionSource")
        self.extensionSource.addItem("")
        self.extensionSource.setItemText(0, "")
        self.extensionSource.addItem("")
        self.extensionSource.addItem("")
        self.horizontalLayout.addWidget(self.extensionSource)
        self.extensionRating = QtWidgets.QSpinBox(signalStatsDialog)
        self.extensionRating.setReadOnly(True)
        self.extensionRating.setMaximum(5)
        self.extensionRating.setObjectName("extensionRating")
        self.horizontalLayout.addWidget(self.extensionRating)
        self.gridLayout.addLayout(self.horizontalLayout, 14, 1, 1, 2)

        self.retranslateUi(signalStatsDialog)
        self.buttonBox.accepted.connect(signalStatsDialog.accept)
        self.buttonBox.rejected.connect(signalStatsDialog.reject)
        self.includeRMS.toggled['bool'].connect(signalStatsDialog.set_composite)
        self.includeInstant.toggled['bool'].connect(signalStatsDialog.set_composite)
        self.includeFast.toggled['bool'].connect(signalStatsDialog.set_composite)
        self.includeSlow.toggled['bool'].connect(signalStatsDialog.set_composite)
        self.includeCustom.toggled['bool'].connect(signalStatsDialog.set_composite)
        self.customIntegrationTime.editingFinished.connect(signalStatsDialog.set_custom_peak)
        self.extensionLimit.valueChanged['int'].connect(signalStatsDialog.set_extension)
        self.compositeLevel.valueChanged['double'].connect(signalStatsDialog.rate_level)
        QtCore.QMetaObject.connectSlotsByName(signalStatsDialog)

    def retranslateUi(self, signalStatsDialog):
        _translate = QtCore.QCoreApplication.translate
        signalStatsDialog.setWindowTitle(_translate("signalStatsDialog", "Stats"))
        self.rms.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label_7.setText(_translate("signalStatsDialog", "Composite Level"))
        self.label_10.setText(_translate("signalStatsDialog", "Extension"))
        self.slowPeak.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label_4.setText(_translate("signalStatsDialog", "Slow Peak"))
        self.label_14.setText(_translate("signalStatsDialog", "Limit"))
        self.label_17.setText(_translate("signalStatsDialog", "Rating"))
        self.label_18.setText(_translate("signalStatsDialog", "Rating"))
        self.customPeak.setSuffix(_translate("signalStatsDialog", " dB"))
        self.peakExtensionX1.setSuffix(_translate("signalStatsDialog", " Hz"))
        self.peakExtensionX2.setSuffix(_translate("signalStatsDialog", " Hz"))
        self.peakExtensionY1.setSuffix(_translate("signalStatsDialog", " dB"))
        self.peakExtensionY2.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label_6.setText(_translate("signalStatsDialog", "Custom Peak"))
        self.label_11.setText(_translate("signalStatsDialog", "Dynamics"))
        self.label_19.setText(_translate("signalStatsDialog", "Average"))
        self.label_2.setText(_translate("signalStatsDialog", "Instantaneous Peak "))
        self.label_15.setText(_translate("signalStatsDialog", "Range"))
        self.averageExtensionX1.setSuffix(_translate("signalStatsDialog", " Hz"))
        self.averageExtensionX2.setSuffix(_translate("signalStatsDialog", " Hz"))
        self.averageExtensionY1.setSuffix(_translate("signalStatsDialog", " dB"))
        self.averageExtensionY2.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label_9.setText(_translate("signalStatsDialog", "Include?"))
        self.label_8.setText(_translate("signalStatsDialog", "Level"))
        self.compositeLevel.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label.setText(_translate("signalStatsDialog", "RMS:"))
        self.label_16.setText(_translate("signalStatsDialog", "Rating"))
        self.instantPeak.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label_3.setText(_translate("signalStatsDialog", "Fast Peak"))
        self.extensionLimit.setSuffix(_translate("signalStatsDialog", " dB"))
        self.label_12.setText(_translate("signalStatsDialog", "Peak"))
        self.customIntegrationTime.setSuffix(_translate("signalStatsDialog", " ms"))
        self.label_5.setText(_translate("signalStatsDialog", "Custom Integration Time"))
        self.dynamics.setSuffix(_translate("signalStatsDialog", " dB"))
        self.fastPeak.setSuffix(_translate("signalStatsDialog", " dB"))
        self.extensionSource.setItemText(1, _translate("signalStatsDialog", "Peak"))
        self.extensionSource.setItemText(2, _translate("signalStatsDialog", "Average"))
