# Form implementation generated from reading ui file 'values.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_valuesDialog(object):
    def setupUi(self, valuesDialog):
        valuesDialog.setObjectName("valuesDialog")
        valuesDialog.resize(400, 393)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(valuesDialog.sizePolicy().hasHeightForWidth())
        valuesDialog.setSizePolicy(sizePolicy)
        valuesDialog.setSizeGripEnabled(True)
        self.formLayout = QtWidgets.QFormLayout(valuesDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=valuesDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.freq = QtWidgets.QDoubleSpinBox(parent=valuesDialog)
        self.freq.setDecimals(1)
        self.freq.setMinimum(1.0)
        self.freq.setMaximum(1000.0)
        self.freq.setObjectName("freq")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.freq)

        self.retranslateUi(valuesDialog)
        self.freq.valueChanged['double'].connect(valuesDialog.updateValues) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(valuesDialog)

    def retranslateUi(self, valuesDialog):
        _translate = QtCore.QCoreApplication.translate
        valuesDialog.setWindowTitle(_translate("valuesDialog", "Values"))
        self.label.setText(_translate("valuesDialog", "Freq (Hz)"))
