# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xofilters.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_xoFiltersDialog(object):
    def setupUi(self, xoFiltersDialog):
        xoFiltersDialog.setObjectName("xoFiltersDialog")
        xoFiltersDialog.resize(400, 504)
        self.verticalLayout = QtWidgets.QVBoxLayout(xoFiltersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filters = QtWidgets.QListWidget(xoFiltersDialog)
        self.filters.setObjectName("filters")
        self.verticalLayout.addWidget(self.filters)
        self.buttonBox = QtWidgets.QDialogButtonBox(xoFiltersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(xoFiltersDialog)
        self.buttonBox.accepted.connect(xoFiltersDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(xoFiltersDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(xoFiltersDialog)

    def retranslateUi(self, xoFiltersDialog):
        _translate = QtCore.QCoreApplication.translate
        xoFiltersDialog.setWindowTitle(_translate("xoFiltersDialog", "Filter List"))
