# Form implementation generated from reading ui file 'xofilters.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_xoFiltersDialog(object):
    def setupUi(self, xoFiltersDialog):
        xoFiltersDialog.setObjectName("xoFiltersDialog")
        xoFiltersDialog.resize(400, 504)
        self.verticalLayout = QtWidgets.QVBoxLayout(xoFiltersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selector = QtWidgets.QComboBox(parent=xoFiltersDialog)
        self.selector.setObjectName("selector")
        self.verticalLayout.addWidget(self.selector)
        self.filters = QtWidgets.QListWidget(parent=xoFiltersDialog)
        self.filters.setObjectName("filters")
        self.verticalLayout.addWidget(self.filters)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copyButton = QtWidgets.QToolButton(parent=xoFiltersDialog)
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout.addWidget(self.copyButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=xoFiltersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(xoFiltersDialog)
        self.selector.currentTextChanged['QString'].connect(xoFiltersDialog.update_list) # type: ignore
        self.buttonBox.accepted.connect(xoFiltersDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(xoFiltersDialog.reject) # type: ignore
        self.copyButton.clicked.connect(xoFiltersDialog.copy_filters) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(xoFiltersDialog)

    def retranslateUi(self, xoFiltersDialog):
        _translate = QtCore.QCoreApplication.translate
        xoFiltersDialog.setWindowTitle(_translate("xoFiltersDialog", "Filter List"))
        self.copyButton.setText(_translate("xoFiltersDialog", "..."))
