/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the service is doing */
        get: operations["status_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notify/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send samples of a target’s configured events */
        post: operations["test_notification_v1_notify_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Automatic extract/design schedule */
        get: operations["get_schedule_v1_schedule_get"];
        /** Save and enable or pause the schedule */
        put: operations["put_schedule_v1_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedule/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run one automatic tick now */
        post: operations["trigger_schedule_v1_schedule_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List titles, filtered */
        get: operations["titles_v1_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/titles/{title_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One title */
        get: operations["title_v1_titles__title_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/titles/{title_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What a person decides a title on: its designs, metadata problems and what is offered */
        get: operations["review_v1_titles__title_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/titles/{title_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The measured curves, and the same after one design */
        get: operations["chart_v1_titles__title_id__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/titles/{title_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a design, or reject the title (refused if what was looked at has changed) */
        post: operations["decision_v1_titles__title_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The next title waiting for a decision after one, in the filtered list (wrapping round) */
        get: operations["next_title_v1_review_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What a run would do (changes nothing) */
        post: operations["plan_v1_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List the sources again */
        post: operations["submit_scan_v1_jobs_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract, design (and, if allowed, publish or commit) the titles a filter selects */
        post: operations["submit_run_v1_jobs_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the designer's top pick for confident titles (needs allow_repository_writes, unless a dry run) */
        post: operations["submit_accept_v1_jobs_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs, newest first */
        get: operations["jobs_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One job */
        get: operations["job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel: a queued job is dropped, a running one stops before its next title */
        post: operations["cancel_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the job has reported so far (the last 500 events) */
        get: operations["log_v1_jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Follow a job: its events as they happen (Server-Sent Events) */
        get: operations["events_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    notification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Completed job notification delivered to a configured target
         * @description Outbound JSON shape. Text, Slack and Discord targets carry a summary of this same event.
         */
        post: operations["notification_webhooknotification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        /** AcceptJob */
        AcceptJob: {
            /** Id */
            id: string;
            origin: components["schemas"]["JobOrigin"];
            state: components["schemas"]["JobState"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            progress: components["schemas"]["Progress"] | null;
            /**
             * Error
             * @description Why the job itself failed (a title that failed is in the result).
             */
            error?: string | null;
            /**
             * Joined To
             * @description The run job this one joined: its titles went into that run, and it ends when that run does, with its result.
             */
            joined_to?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "accept";
            request: components["schemas"]["AcceptJobRequest"];
            result: components["schemas"]["AcceptResult"] | null;
        };
        /** AcceptJobRequest */
        AcceptJobRequest: {
            filter?: components["schemas"]["TitleFilter"];
            /**
             * Threshold
             * @description Accept the designer's top pick at least this confident.
             * @default 0.9
             */
            threshold: number;
            /**
             * Dry Run
             * @description Say what would be accepted and change nothing.
             * @default false
             */
            dry_run: boolean;
        };
        /** AcceptResult */
        AcceptResult: {
            /** Dry Run */
            dry_run: boolean;
            /** Threshold */
            threshold: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Accepted
             * @description Accepted (or, in a dry run, that would be).
             */
            accepted: string[];
            /**
             * Excluded
             * @description Confident enough, but left for a person, and why.
             */
            excluded: components["schemas"]["SkippedTitle"][];
            /** Below Threshold */
            below_threshold: number;
            /** Not For Review */
            not_for_review: number;
        };
        /**
         * AutoThrough
         * @enum {string}
         */
        AutoThrough: "extract" | "design";
        /**
         * Blocked
         * @description Why each decision is not offered now; empty when it is.
         */
        Blocked: {
            /** Accept */
            accept: string;
            /** Reject */
            reject: string;
        };
        /**
         * CandidateView
         * @description One design a person may pick: a candidate, or one the designer rejected (`rejection_reasons`).
         */
        CandidateView: {
            /**
             * Index
             * @description Its position in the designs offered (candidates, then rejected designs): what a Decision names.
             */
            index: number;
            /**
             * Rejected
             * @description The designer judged it unfit to publish: accepting it overrides the designer.
             */
            rejected: boolean;
            /** Method */
            method: string;
            /**
             * Confidence
             * @description None only for a decline's flat "does not require BEQ" design.
             */
            confidence: number | null;
            /** Mv Adjust Db */
            mv_adjust_db: number;
            /** Gain Reduction Db */
            gain_reduction_db?: number | null;
            /** Residual Db */
            residual_db?: number | null;
            /** Residual Band Hz */
            residual_band_hz?: number[] | null;
            /** Commentary */
            commentary?: {
                [key: string]: unknown;
            } | null;
            /** Rejection Reasons */
            rejection_reasons?: string[];
            /**
             * Filters
             * @description The design as a .filter document (docs/schema/filter.schema.json).
             */
            filters: {
                [key: string]: unknown;
            };
        };
        /** CatalogueCommit */
        CatalogueCommit: {
            xml: components["schemas"]["RepoCommit"];
            images?: components["schemas"]["RepoCommit"] | null;
            /** Missing */
            missing: string[];
            /** Not Committed */
            not_committed: string[];
            /** Warnings */
            warnings: string[];
        };
        /** Chart */
        Chart: {
            /** Candidate */
            candidate: number | null;
            /** Series */
            series: components["schemas"]["ChartSeries"][];
        };
        /** ChartSeries */
        ChartSeries: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "average" | "peak";
            /**
             * Filtered
             * @description After the chosen design.
             */
            filtered: boolean;
            /**
             * X
             * @description Frequency, Hz.
             */
            x: number[];
            /**
             * Y
             * @description Magnitude, dB.
             */
            y: number[];
        };
        /** Check */
        Check: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Required
             * @description False: reported, but not a reason for `ready` to be false (a designer that is down does not make the service unready).
             * @default true
             */
            required: boolean;
        };
        /** Decision */
        Decision: {
            decision: components["schemas"]["DecisionKind"];
            /**
             * Candidate
             * @description Required to accept: the index of a design in the Review.
             */
            candidate?: number | null;
            /**
             * Digest
             * @description The Review's digest: what was looked at.
             */
            digest: string;
            /**
             * Override Rejection
             * @description Accept a design the designer rejected (otherwise a 409).
             * @default false
             */
            override_rejection: boolean;
        };
        /**
         * DecisionKind
         * @enum {string}
         */
        DecisionKind: "accept" | "reject";
        /** Decline */
        Decline: {
            /** Reason */
            reason: string;
            /** Message */
            message: string;
        };
        /** DesignerStatus */
        DesignerStatus: {
            /** Name */
            name: string;
            /**
             * Reachable
             * @description Whether its /health answered; null when there is nothing to ask (the manual designer) or the profile cannot be read.
             */
            reachable: boolean | null;
            /**
             * Detail
             * @description Its URL when it answered, else why not.
             */
            detail: string;
            /** Checked At */
            checked_at: string | null;
        };
        /**
         * ExtractProgressEvent
         * @description How far ffmpeg has got extracting a title (one every 5 seconds or so, and the last).
         */
        ExtractProgressEvent: {
            /**
             * Seq
             * @description Its place in the job: events come in this order, and `after` resumes after one.
             */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Text
             * @description What a person reads (redacted).
             */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "extract_progress";
            /** Title */
            title: string;
            /** Title Id */
            title_id: string;
            /**
             * Done Ms
             * @description Audio extracted so far, in milliseconds.
             */
            done_ms: number;
            /**
             * Total Ms
             * @description The audio's length, in milliseconds; absent if ffmpeg did not say.
             */
            total_ms?: number | null;
            /**
             * Percent
             * @description done_ms of total_ms, 0 to 100; absent without total_ms.
             */
            percent?: number | null;
        };
        /**
         * Flag
         * @enum {string}
         */
        Flag: "Ignored" | "Shadowed" | "Gone" | "Possible duplicate" | "Already in catalogue";
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** IndexStatus */
        IndexStatus: {
            /** Generation */
            generation: number;
            /** Last Scan At */
            last_scan_at: string | null;
            /** Titles */
            titles: number;
            /**
             * Counts
             * @description Titles per needs.
             */
            counts: {
                [key: string]: number;
            };
            /** New */
            new: number;
            /** Flags */
            flags: {
                [key: string]: number;
            };
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
        };
        /**
         * JobEvent
         * @description One thing a job reported, in order (`seq`). `type` says which fields it has, and every one has `text`.
         */
        JobEvent: components["schemas"]["StateEvent"] | components["schemas"]["RunProgressEvent"] | components["schemas"]["ExtractProgressEvent"] | components["schemas"]["TitleEvent"];
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "scan" | "run" | "accept";
        /** JobList */
        JobList: {
            /** Jobs */
            jobs: (components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"])[];
        };
        /**
         * JobOrigin
         * @enum {string}
         */
        JobOrigin: "api" | "schedule";
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
        /**
         * Kind
         * @enum {string}
         */
        Kind: "movie" | "tv";
        /**
         * Needs
         * @enum {string}
         */
        Needs: "attention" | "review" | "extract" | "design" | "publish" | "commit" | "done";
        /** NextTitle */
        NextTitle: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** Notification */
        Notification: {
            event: components["schemas"]["NotifyEvent"];
            /** @description The job it is about; null for a scheduled run that was skipped (the designer did not answer), which `failed` names instead. */
            job: components["schemas"]["NotifyJob"] | null;
            /** Designed */
            designed: components["schemas"]["NotifyTitle"][];
            /** Failed */
            failed: components["schemas"]["NotifyFailure"][];
            /** Review Waiting */
            review_waiting: number;
            links: components["schemas"]["NotifyLinks"];
        };
        /**
         * NotifyEvent
         * @enum {string}
         */
        NotifyEvent: "review_waiting" | "failed" | "job_finished";
        /** NotifyFailure */
        NotifyFailure: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Message */
            message: string;
        };
        /** NotifyJob */
        NotifyJob: {
            /** Id */
            id: string;
            kind: components["schemas"]["JobKind"];
            origin: components["schemas"]["JobOrigin"];
            state: components["schemas"]["JobState"];
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** NotifyLinks */
        NotifyLinks: {
            /** Job */
            job: string;
            /** Docs */
            docs: string;
        };
        /** NotifyOutcome */
        NotifyOutcome: {
            /** Name */
            name: string;
            last_event?: components["schemas"]["NotifyEvent"] | null;
            /** Last Attempt At */
            last_attempt_at?: string | null;
            /** Ok */
            ok?: boolean | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** NotifyTest */
        NotifyTest: {
            /** Target */
            target: string;
        };
        /** NotifyTitle */
        NotifyTitle: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Year */
            year: string;
            kind: components["schemas"]["Kind"];
            /** Confidence */
            confidence: number | null;
        };
        /** PlanPreview */
        PlanPreview: {
            through: components["schemas"]["Through"];
            /**
             * Label
             * @description What the work list's action button would say.
             */
            label: string;
            /** Planned */
            planned: components["schemas"]["PlannedTitle"][];
            /** Skipped */
            skipped: components["schemas"]["SkippedTitle"][];
        };
        /** PlannedTitle */
        PlannedTitle: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Stages */
            stages: components["schemas"]["Through"][];
        };
        /**
         * Problem
         * @description An error, as RFC 9457 problem details.
         */
        Problem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Errors
             * @description Field-level validation errors.
             */
            errors?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** Progress */
        Progress: {
            /**
             * Done
             * @description Title-stages finished.
             */
            done: number;
            /** Total */
            total: number;
            /**
             * Title
             * @description The title starting now.
             */
            title: string;
            /** Stage */
            stage: string;
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Per Hour
             * @description Title-stages finished per hour so far (a running job, once one is done).
             */
            per_hour?: number | null;
            /**
             * Remaining Seconds
             * @description At that rate, how long the rest will take.
             */
            remaining_seconds?: number | null;
            /**
             * Estimated Finish
             * @description At that rate, when it will end.
             */
            estimated_finish?: string | null;
        };
        /** PublishError */
        PublishError: {
            /** Id */
            id: string;
            /** Error */
            error: string;
            /** Problems */
            problems?: string[] | null;
            /** Message */
            message?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** PublishedTitle */
        PublishedTitle: {
            /** Id */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /** Republished */
            republished?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * QueueStatus
         * @enum {string}
         */
        QueueStatus: "pending" | "accepted" | "skipped" | "rejected" | "published";
        /** Readiness */
        Readiness: {
            /** Ready */
            ready: boolean;
            /** Checks */
            checks: components["schemas"]["Check"][];
        };
        /** RepoCommit */
        RepoCommit: {
            /** Repo */
            repo: string;
            /** Paths */
            paths: string[];
            /** Commit */
            commit: string | null;
            /** Pushed */
            pushed: boolean;
        };
        /**
         * Review
         * @description What a person decides a title on, and whether they can.
         */
        Review: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Year */
            year: string;
            status: components["schemas"]["QueueStatus"];
            /** Status Text */
            status_text: string;
            /**
             * Digest
             * @description Fingerprint of the designs offered: send it back in a Decision, which is refused if a redesign has changed them since.
             */
            digest: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateView"][];
            /** Rejected */
            rejected: components["schemas"]["CandidateView"][];
            /**
             * Chosen Index
             * @description The design accepted or published, into the designs offered.
             */
            chosen_index: number | null;
            /** @description The designer found nothing to correct; its one candidate is flat. */
            declined: components["schemas"]["Decline"] | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Metadata Problems
             * @description What publish would refuse: Accept is not offered until it is fixed (in the BEQDesigner app).
             */
            metadata_problems: string[];
            blocked: components["schemas"]["Blocked"];
            /**
             * In Flight
             * @description A run is working on this title now.
             */
            in_flight: boolean;
            /**
             * Playback
             * @description The playback chain the designer was told about.
             */
            playback: string;
            /** Designer */
            designer: string | null;
            /** Designer Build */
            designer_build: string | null;
            needs: components["schemas"]["Needs"];
            /** Detail */
            detail: string;
            /** Reviewer Note */
            reviewer_note: string | null;
        };
        /** RunJob */
        RunJob: {
            /** Id */
            id: string;
            origin: components["schemas"]["JobOrigin"];
            state: components["schemas"]["JobState"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            progress: components["schemas"]["Progress"] | null;
            /**
             * Error
             * @description Why the job itself failed (a title that failed is in the result).
             */
            error?: string | null;
            /**
             * Joined To
             * @description The run job this one joined: its titles went into that run, and it ends when that run does, with its result.
             */
            joined_to?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run";
            request: components["schemas"]["RunJobRequest"];
            result: components["schemas"]["RunResult"] | null;
        };
        /** RunJobRequest */
        RunJobRequest: {
            filter?: components["schemas"]["TitleFilter"];
            /**
             * @description Run every stage up to this one that each title still needs. A title waiting for review is never taken past design.
             * @default design
             */
            through: components["schemas"]["Through"];
            /**
             * Scan First
             * @description List the sources before selecting, so new titles are seen.
             * @default true
             */
            scan_first: boolean;
            /**
             * Retry Failed
             * @description Also run titles whose extraction or design failed before.
             * @default false
             */
            retry_failed: boolean;
        };
        /**
         * RunProgressEvent
         * @description The run started a title-stage: `done` of `total` are finished. The last has no title: the run is over.
         */
        RunProgressEvent: {
            /**
             * Seq
             * @description Its place in the job: events come in this order, and `after` resumes after one.
             */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Text
             * @description What a person reads (redacted).
             */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run_progress";
            /** Done */
            done: number;
            /** Total */
            total: number;
            /**
             * Stage
             * @description extract, design, publish or commit; absent once the run is over.
             */
            stage?: string | null;
            /** Title */
            title?: string | null;
            /** Title Id */
            title_id?: string | null;
        };
        /** RunResult */
        RunResult: {
            /** @description The scan taken first, if one was. */
            scan?: components["schemas"]["ScanResult"] | null;
            through: components["schemas"]["Through"];
            /** Selected */
            selected: number;
            /** Extracted */
            extracted: string[];
            /** Cached */
            cached: string[];
            /** Designed */
            designed: string[];
            /** Design Cached */
            design_cached: string[];
            /** Failed */
            failed: components["schemas"]["TitleMessage"][];
            /**
             * Failed Earlier
             * @description Not tried: failed before with the same source and settings.
             */
            failed_earlier: components["schemas"]["TitleMessage"][];
            /**
             * Unavailable
             * @description Not done because something it depends on (the designer, the media storage, JRiver) was unavailable. Not remembered as failed: the next run tries it again.
             */
            unavailable?: components["schemas"]["TitleMessage"][];
            /** Meta Unresolved */
            meta_unresolved: components["schemas"]["TitleMessage"][];
            /** Project Edit Preserved */
            project_edit_preserved: string[];
            /** Seasons */
            seasons: {
                [key: string]: string[];
            };
            /** Published */
            published: components["schemas"]["PublishedTitle"][];
            /** Publish Errors */
            publish_errors: components["schemas"]["PublishError"][];
            committed: components["schemas"]["CatalogueCommit"] | null;
            /** Commit Error */
            commit_error: string;
            /** Skipped */
            skipped: components["schemas"]["SkippedTitle"][];
            /** Cancelled */
            cancelled: boolean;
            /**
             * Stopped
             * @description Why the run stopped before its selection was done, though nobody cancelled it: too many titles in a row met an unavailable dependency.
             * @default
             */
            stopped: string;
            /** Attempted */
            attempted: string[];
            /** Not Run */
            not_run: string[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** ScanJob */
        ScanJob: {
            /** Id */
            id: string;
            origin: components["schemas"]["JobOrigin"];
            state: components["schemas"]["JobState"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            progress: components["schemas"]["Progress"] | null;
            /**
             * Error
             * @description Why the job itself failed (a title that failed is in the result).
             */
            error?: string | null;
            /**
             * Joined To
             * @description The run job this one joined: its titles went into that run, and it ends when that run does, with its result.
             */
            joined_to?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "scan";
            request: components["schemas"]["ScanJobRequest"];
            result: components["schemas"]["ScanResult"] | null;
        };
        /** ScanJobRequest */
        ScanJobRequest: {
            /**
             * Sources
             * @description Sources to list again, by name; none is all of them.
             */
            sources?: string[];
            /**
             * Allow Empty
             * @description A source that now lists nothing replaces its titles (else it keeps them: an unmounted share).
             * @default false
             */
            allow_empty: boolean;
        };
        /** ScanResult */
        ScanResult: {
            /** Generation */
            generation: number;
            /** Titles */
            titles: number;
            /** New */
            new: string[];
            /** Gone */
            gone: string[];
            /** Dropped */
            dropped: string[];
            /**
             * Errors
             * @description Source name -> why it could not be listed (its titles are kept).
             */
            errors: {
                [key: string]: string;
            };
            /**
             * Counts
             * @description Titles per needs.
             */
            counts: {
                [key: string]: number;
            };
            /** Superseded */
            superseded?: string[];
        };
        /** Schedule */
        Schedule: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Interval Minutes
             * @default 60
             */
            interval_minutes: number;
            filter?: components["schemas"]["TitleFilter"];
            /** @default design */
            through: components["schemas"]["AutoThrough"];
            /**
             * Retry Failed
             * @default false
             */
            retry_failed: boolean;
            /** Next Run At */
            next_run_at?: string | null;
            last_run?: components["schemas"]["ScheduleLastRun"] | null;
            /** Last Skip */
            last_skip?: string | null;
            /**
             * Ended
             * @description Why the schedule turned itself off: its filter lists ids, and a run left none of them to do. Cleared by the next save.
             */
            ended?: string | null;
        };
        /** ScheduleLastRun */
        ScheduleLastRun: {
            /** Job Id */
            job_id: string;
            state: components["schemas"]["JobState"];
            /** Finished At */
            finished_at: string | null;
        };
        /** ScheduleUpdate */
        ScheduleUpdate: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Interval Minutes
             * @default 60
             */
            interval_minutes: number;
            filter?: components["schemas"]["TitleFilter"];
            /** @default design */
            through: components["schemas"]["AutoThrough"];
            /**
             * Retry Failed
             * @default false
             */
            retry_failed: boolean;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /** Version */
            version: string;
            /** @description None until the first scan. */
            index: components["schemas"]["IndexStatus"] | null;
            /** Current Job */
            current_job: (components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"]) | null;
            /** Queued */
            queued: number;
            schedule?: components["schemas"]["Schedule"] | null;
            /** Notify */
            notify?: components["schemas"]["NotifyOutcome"][];
            designer?: components["schemas"]["DesignerStatus"] | null;
            /**
             * Tmdb
             * @description Whether a TMDB key is set (TMDB_API_KEY): without one, titles are designed with the library's own metadata only.
             */
            tmdb?: boolean | null;
            /**
             * Repository Writes
             * @description Whether publish, commit and bulk accept are allowed (allow_repository_writes in the service config).
             * @default false
             */
            repository_writes: boolean;
            /**
             * Repositories Configured
             * @description Whether the profile names the filter repository that publish and commit write to.
             * @default false
             */
            repositories_configured: boolean;
        };
        /** SkippedTitle */
        SkippedTitle: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Reason */
            reason: string;
        };
        /** SourceStatus */
        SourceStatus: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Last Scanned */
            last_scanned: string | null;
            /** Last Ok */
            last_ok: string | null;
            /** Last Error */
            last_error: string;
            /** Item Count */
            item_count: number;
        };
        /**
         * StateEvent
         * @description The job entered a state; the stream ends with a finished one.
         */
        StateEvent: {
            /**
             * Seq
             * @description Its place in the job: events come in this order, and `after` resumes after one.
             */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Text
             * @description What a person reads (redacted).
             */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state";
            /**
             * State
             * @description queued, running, cancelling, succeeded, failed, cancelled or interrupted.
             */
            state: string;
        };
        /**
         * Through
         * @enum {string}
         */
        Through: "extract" | "design" | "publish" | "commit";
        /**
         * Tier
         * @enum {string}
         */
        Tier: "attention" | "human" | "machine" | "done";
        /** Title */
        Title: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Display Name */
            display_name: string;
            /** Year */
            year: string;
            kind: components["schemas"]["Kind"];
            /** Source */
            source: string;
            /** Path */
            path: string;
            /** Season */
            season: string;
            /** Episodes */
            episodes: number[];
            /** External Ids */
            external_ids: {
                [key: string]: string;
            };
            needs: components["schemas"]["Needs"];
            tier: components["schemas"]["Tier"];
            /** Detail */
            detail: string;
            /** Flags */
            flags: components["schemas"]["Flag"][];
            /** Extract State */
            extract_state: string;
            /** Design State */
            design_state: string;
            /** Review State */
            review_state: string;
            /** Publish State */
            publish_state: string;
            /** Commit State */
            commit_state: string;
            /** Confidence */
            confidence: number | null;
            /** Candidate Count */
            candidate_count: number;
            /** Failure */
            failure: string;
            /** Is New */
            is_new: boolean;
            /** State Since */
            state_since: string | null;
            /** Last Seen */
            last_seen: string | null;
        };
        /**
         * TitleEvent
         * @description Something that happened to a title: a stage started or finished, a command ran, it failed.
         */
        TitleEvent: {
            /**
             * Seq
             * @description Its place in the job: events come in this order, and `after` resumes after one.
             */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Text
             * @description What a person reads (redacted).
             */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "event";
            /** Title Id */
            title_id: string;
            /** Stage */
            stage: string;
            /**
             * Kind
             * @description stage_started, command_finished, ...
             */
            kind: string;
        };
        /**
         * TitleFilter
         * @description Which titles: the work list's filters. Every field given must hold; none is every title.
         */
        TitleFilter: {
            /**
             * Needs
             * @description What the title needs next (any of these).
             */
            needs?: components["schemas"]["Needs"][];
            /**
             * New Since Scan
             * @description Only titles first seen by the latest scan.
             * @default false
             */
            new_since_scan: boolean;
            /**
             * Source
             * @description Only titles from this source of the profile, by its name.
             */
            source?: string | null;
            /**
             * Match
             * @description Case-insensitive text in the title, name, id or path.
             */
            match?: string | null;
            /**
             * Ids
             * @description Only these titles, by catalogue id.
             */
            ids?: string[];
            kind?: components["schemas"]["Kind"] | null;
            /** Year */
            year?: string | null;
        };
        /** TitleMessage */
        TitleMessage: {
            /** Id */
            id: string;
            /** Message */
            message: string;
        };
        /** TitlePage */
        TitlePage: {
            /**
             * Total
             * @description Titles the filter matches.
             */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Titles */
            titles: components["schemas"]["Title"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    status_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    test_notification_v1_notify_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotifyTest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifyOutcome"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_schedule_v1_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_schedule_v1_schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    trigger_schedule_v1_schedule_trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    titles_v1_titles_get: {
        parameters: {
            query?: {
                /** @description What the title needs next (any of these). */
                needs?: components["schemas"]["Needs"][];
                /** @description Only titles first seen by the latest scan. */
                new_since_scan?: boolean;
                /** @description Only titles from this source of the profile, by its name. */
                source?: string | null;
                /** @description Case-insensitive text in the title, name, id or path. */
                match?: string | null;
                /** @description Only these titles, by catalogue id. */
                ids?: string[];
                kind?: components["schemas"]["Kind"] | null;
                year?: string | null;
                /** @description Include titles that need nothing (as the work list does only on Done). */
                include_done?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitlePage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    title_v1_titles__title_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Title"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    review_v1_titles__title_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    chart_v1_titles__title_id__chart_get: {
        parameters: {
            query?: {
                /** @description A design, by its index; absent: the measured curves only. */
                candidate?: number | null;
            };
            header?: never;
            path: {
                title_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chart"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    decision_v1_titles__title_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                title_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    next_title_v1_review_next_get: {
        parameters: {
            query?: {
                /** @description What the title needs next (any of these). */
                needs?: components["schemas"]["Needs"][];
                /** @description Only titles first seen by the latest scan. */
                new_since_scan?: boolean;
                /** @description Only titles from this source of the profile, by its name. */
                source?: string | null;
                /** @description Case-insensitive text in the title, name, id or path. */
                match?: string | null;
                /** @description Only these titles, by catalogue id. */
                ids?: string[];
                kind?: components["schemas"]["Kind"] | null;
                year?: string | null;
                /** @description The title just decided (or open): the next one after it is found. Absent: the first waiting title in the list. */
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextTitle"];
                };
            };
            /** @description No other title in the list is waiting. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    plan_v1_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanPreview"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    submit_scan_v1_jobs_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanJobRequest"];
            };
        };
        responses: {
            /** @description Queued; `Location` names the job. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    submit_run_v1_jobs_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunJobRequest"];
            };
        };
        responses: {
            /** @description Queued; `Location` names the job. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    submit_accept_v1_jobs_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptJobRequest"];
            };
        };
        responses: {
            /** @description Queued; `Location` names the job. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    jobs_v1_jobs_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["JobState"] | null;
                kind?: components["schemas"]["JobKind"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancel_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"] | components["schemas"]["RunJob"] | components["schemas"]["AcceptJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    log_v1_jobs__job_id__log_get: {
        parameters: {
            query?: {
                /** @description Only events after this seq. */
                after?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEvent"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    events_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A stream of JobEvent, one per `data:` line, until the job ends. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["JobEvent"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    notification_webhooknotification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
