name: create apps
on:
  push:
    tags:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
  build:
    name: Create Binaries
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          if [[ "$RUNNER_OS" == "Windows" ]]
          then
            pipenv run pip install -Iv numpy==1.19.3
          fi
          pip list
          pipenv run pip list
      - name: pytest
        run: |
          PYTHONPATH=./src/main/python pipenv run pytest --cov=./src/main/python
      - name: Install packaging dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
            sudo apt install libblas-dev liblapack-dev libsndfile1
          elif [ "$RUNNER_OS" == "Windows" ]
          then
            choco install openssl.light nsis
          fi
          pipenv run pip install pyinstaller
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Set version
        run: |
          echo ${{ steps.get_version.outputs.version-without-v }} > src/main/python/VERSION
      - name: Create distribution
        id: create_dist
        run: |
          pipenv run pyinstaller --clean --log-level=INFO -F beqdesigner.spec
          if [[ "$RUNNER_OS" == "macOS" ]]
          then
            pushd dist
            rm beqdesigner
            zip -r beqdesigner.app.zip beqdesigner.app
            rm -Rf beqdesigner.app
            popd
            echo ::set-output name=binary_path::"dist/beqdesigner.app.zip"
            echo ::set-output name=binary_name::"beqdesigner.app.zip"
            echo ::set-output name=binary_content_type::"application/zip"
          elif [[ "$RUNNER_OS" == "Windows" ]]
          then
            export USE_NSIS=Y
            mv dist/beqdesigner.exe dist/bak.exe
            pipenv run pyinstaller --clean --log-level=INFO -D beqdesigner.spec
            "/c/Program Files (x86)/NSIS/makensis.exe" src/main/nsis/Installer.nsi
            mv dist/bak.exe dist/beqdesigner.exe
            echo ::set-output name=binary_path::"dist/beqdesigner.exe"
            echo ::set-output name=binary_name::"beqdesigner.exe"
            echo ::set-output name=binary_content_type::"application/vnd.microsoft.portable-executable"
          else
            MATCHES=( dist/beqdesigner_* )
            echo ::set-output name=binary_path::"${MATCHES[0]}"
            echo ::set-output name=binary_name::"${MATCHES[0]:5}"
            echo ::set-output name=binary_content_type::"application/octet-stream"
          fi
      - name: Upload beqdesigner
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ${{ steps.create_dist.outputs.binary_name }}
          asset_path: ${{ steps.create_dist.outputs.binary_path }}
          asset_content_type: ${{ steps.create_dist.outputs.binary_content_type }}
      - name: Upload beqdesignerSetup
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'windows-2019'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: beqdesignerSetup.exe
          asset_path: dist/beqdesignerSetup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
