name: run tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15, windows-2019 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          if [[ "$RUNNER_OS" == "Windows" ]]
          then
            pipenv run pip install -Iv numpy==1.19.3
          fi
          pip list
          pipenv run pip list
      - name: pytest
        run: |
          PYTHONPATH=./src/main/python pipenv run pytest --cov=./src/main/python
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
      - name: Install packaging dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
            sudo apt install libblas-dev liblapack-dev libsndfile1
          elif [ "$RUNNER_OS" == "Windows" ]
          then
            choco install openssl.light nsis
          fi
          pipenv run pip install pyinstaller
      - name: Get version
        id: get_version
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Append version
        run: |
          echo ${{ steps.get_version.outputs.sha_short }} > src/main/python/VERSION
      - name: Create distribution
        run: |
          pipenv run pyinstaller --clean --log-level=INFO -F beqdesigner.spec
          if [[ "$RUNNER_OS" == "macOS" ]]
          then
            pushd dist
            rm beqdesigner
            zip -r beqdesigner.app.${{ matrix.os }}.zip beqdesigner.app
            rm -Rf beqdesigner.app
            popd
          fi
      - name: Archive app binaries
        uses: actions/upload-artifact@v2
        with:
          name: beqdesigner-apps
          path: |
            dist/beqdesigner.exe
            dist/beqdesigner*.zip
            dist/beqdesigner_*
          retention-days: 1
