name: run tests
on: [ push, pull_request ]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15, windows-2019 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          if [[ "$RUNNER_OS" == "Windows" ]]
          then
            pipenv run pip install -Iv numpy==1.19.3
          fi
          pip list
          pipenv run pip list
      - name: pytest
        run: |
          PYTHONPATH=./src/main/python pipenv run pytest --cov=./src/main/python
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
      - name: Install packaging dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
            sudo apt install libblas-dev liblapack-dev libsndfile1
          elif [ "$RUNNER_OS" == "Windows" ]
          then
            choco install openssl.light nsis
          fi
          pipenv run pip install pyinstaller
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Set version
        run: |
          echo ${{ steps.get_version.outputs.version-without-v }} > src/main/python/VERSION
      - name: Create distribution
        run: |
          $PRUN pyinstaller --clean --log-level=INFO -F beqdesigner.spec
          if [[ "$RUNNER_OS" == "macOS" ]]
          then
            pushd dist
            rm beqdesigner
            zip -r beqdesigner.app.10.15.zip beqdesigner.app
            rm -Rf beqdesigner.app
            popd
          elif [[ "$RUNNER_OS" == "Windows" ]]
          then
            export USE_NSIS=Y
            mv dist/beqdesigner.exe dist/bak.exe
            $PRUN pyinstaller --clean --log-level=INFO -D beqdesigner.spec
            "/c/Program Files (x86)/NSIS/makensis.exe" src/main/nsis/Installer.nsi
            mv dist/bak.exe dist/beqdesigner.exe
            mv dist/beqdesigner.exe dist/beqdesigner_small.exe
            mv dist/beqdesignerSetup.exe dist/beqdesignerSetup_small.exe
          fi