name: run tests
on: [ push, pull_request ]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          pip list
          pipenv run pip list
      - name: Test with pytest
        run: |
          PYTHONPATH=./src/main/python pipenv run pytest --cov=./src/main/python